"""Uzupełnienie zwierząt z GBIF (polskie nazwy zwyczajowe).

Wygenerowano skryptem ``scripts/build_fauna_flora_gbif_supplement.py``. Nie edytuj ręcznie — odtwórz skryptem.
"""

from __future__ import annotations

from typing import Final

ANIMALS_GBIF_NORMS: Final[frozenset[str]] = frozenset({
    "(bekas) dubelt",
    "adaks",
    "aksamitka jadowita",
    "alaktaga balikuńska",
    "alaktaga czteropalczasta",
    "alaktaga gobijska",
    "alaktaga hotsona",
    "alaktaga pustynna",
    "aligator missisipijski",
    "aligator missisipski",
    "alka",
    "alka krzywonosa",
    "aloza finta",
    "aloza niebieska",
    "aloza teczowa",
    "aloza wielkooka",
    "ametyścik cienkodzioby",
    "ametyścik wspaniały",
    "amur bialy",
    "antylopowiec szablorogi",
    "ara czerwona",
    "argentyna smukla",
    "arotron szorstki",
    "assapan północny",
    "babka piaskowa",
    "badylarka pospolita",
    "bagiennik żółtorogi",
    "bagniak płaczliwy",
    "bak",
    "balizaur",
    "balizuar obrożny",
    "balizuar północny",
    "balizuar sumatrzański",
    "barasinga bagienna",
    "barwena molukanska",
    "barwena ognista",
    "barwnica (zwyczajna)",
    "barwnica pacyficzna",
    "barwnica zwyczajna",
    "bass sloneczny",
    "bawolec krowi",
    "bażant zwyczajny",
    "bejra somalijska",
    "bekas",
    "bekasnik",
    "bekaśnik drobny",
    "bernikla obrożna (bernicla)",
    "bezrąbek sadowiec",
    "bełtwa włosiennik",
    "białawiec rukiewnik",
    "białorzytka",
    "biedronka dwudziestodwukropka",
    "biegacz urozmaicony",
    "biegus temmincka",
    "biegus zmienny (schinzii)",
    "bielik",
    "bielinek",
    "bielinek bryoniae",
    "bielmica",
    "bieluga z. wyz",
    "billbil tajwański",
    "blotniak zbozowy",
    "bobroszczur papuaski",
    "bobroszczur zachodni",
    "bobroszczur złotobrzuchy",
    "bogatka",
    "bolen amurski",
    "bordziec pisklipwy",
    "borowiec leislera",
    "borowiec leśny",
    "borsucznik amerykański",
    "borówka brunatna",
    "brazosz",
    "brodacz czerwonoboczny",
    "brodacz krasnopręgi (fitzpatricki)",
    "brodawkonos afrykański",
    "brodawkonos drobny",
    "brodawkonos jemeński",
    "brodawkonos pustynny",
    "brzana karpacka",
    "brzana kragloluska",
    "brzanka",
    "brzegówka",
    "buszbok subsaharyjski",
    "bystrzyk pieknopletwy",
    "bączek",
    "bączek (zwyczajny)",
    "bąk",
    "błotniarka bałtycka",
    "błotniarka wędrowna",
    "błyszczka nibyspiżówka",
    "carny bóśon",
    "cefal cienkowargi",
    "cefal pospolity",
    "cefal złocisty",
    "cefal złotogłowy",
    "chimera a. przeraza",
    "chomiczek kaukaski",
    "chrabąszcz kasztanowiec",
    "chruściel wielki",
    "chwastówka",
    "chwastówka (zwyczajna)",
    "cienkodziobek złotobrzuchy",
    "cierniczek",
    "cierniówka wschodnia",
    "cietrzew kaukaski",
    "cietrzew zwyczajny",
    "corcón",
    "crap de iarba",
    "cukrzyk bahamski",
    "cukrzyk bananowy",
    "cukrzyk tropikalny",
    "cyjon rudy",
    "cylindrowcowate",
    "dubelt",
    "edredon turkan",
    "escamón",
    "garnela nakrapiana",
    "garnela pospolita",
    "grzybiec",
    "hóma'e",
    "jaskółka brzegówka",
    "jesiotr europejski",
    "kapiadó audubon",
    "kokonica jeżynówka",
    "kokonica malinówka",
    "kolcomysz złotawa",
    "korsarz bagiennik",
    "kroszela",
    "kszyk",
    "legwan lądowy z santa fe",
    "mazaricu fartón",
    "modroara błękitna",
    "namiotówka dębolistna",
    "nurzec mały",
    "oczatka",
    "ogończyk andyjski",
    "oszynda wiązówkowiec",
    "przeraza",
    "przezierka czyściczanka",
    "przezierka szafranka",
    "przezierka łzawianka",
    "puchowica wełnianka",
    "rukiewnik zachodni",
    "rybożer afrykański",
    "rybożer białobrzuchy",
    "rybożer madagaskarski",
    "saltón",
    "sikora bogatka",
    "singil",
    "sperónzola",
    "srebrzyk smukły",
    "torbik bambusowy",
    "turkan",
    "turkan (edredon okazały)",
    "wiz",
    "wstęgówka księżniczka",
    "wstęgówka znaczona",
    "wyz",
    "zajęczak buszmeński",
    "zębiełek afrykański",
    "zębiełek dżunglowy",
    "zębiełek okopcony",
    "złotka granatowa",
    "ślimak aksamitny",
    "ślimak bielaczek",
    "świrena",
})
