"""Miasta w Polsce z Wikidata (SPARQL), etykiety języka ``pl``.

Wygenerowano: 2026-05-12 05:42:00 UTC
Skrypt: ``scripts/build_polish_cities_wikidata.py``.
Filtr nazw: ``panstwa_miasta.city_name_rules``.

Nie edytuj ręcznie — odtwórz skryptem.
"""

from __future__ import annotations

from typing import Final

CITIES_SEED_PL_WIKI: Final[list[tuple[str, str]]] = [
    ("Aleksandrów Kujawski", "Polska"),
    ("Aleksandrów Łódzki", "Polska"),
    ("Alwernia", "Polska"),
    ("Andrychów", "Polska"),
    ("Annopol", "Polska"),
    ("Augustów", "Polska"),
    ("Babimost", "Polska"),
    ("Baborów", "Polska"),
    ("Baranów Sandomierski", "Polska"),
    ("Barcin", "Polska"),
    ("Barczewo", "Polska"),
    ("Bardo", "Polska"),
    ("Barlinek", "Polska"),
    ("Bartoszyce", "Polska"),
    ("Barwice", "Polska"),
    ("Bezledy", "Polska"),
    ("Bełchatów", "Polska"),
    ("Bełżyce", "Polska"),
    ("Biała", "Polska"),
    ("Biała Piska", "Polska"),
    ("Biała Podlaska", "Polska"),
    ("Biała Rawska", "Polska"),
    ("Białobrzegi", "Polska"),
    ("Białogard", "Polska"),
    ("Biały Bór", "Polska"),
    ("Białystok", "Polska"),
    ("Biecz", "Polska"),
    ("Bielawa", "Polska"),
    ("Bielsk", "Polska"),
    ("Bielsk Podlaski", "Polska"),
    ("Bielsko-Biała", "Polska"),
    ("Bierutów", "Polska"),
    ("Bieruń", "Polska"),
    ("Bieżuń", "Polska"),
    ("Biskupiec", "Polska"),
    ("Bisztynek", "Polska"),
    ("Biłgoraj", "Polska"),
    ("Blachownia", "Polska"),
    ("Bobolice", "Polska"),
    ("Boboszów", "Polska"),
    ("Bobowa", "Polska"),
    ("Bobrowniki", "Polska"),
    ("Bochnia", "Polska"),
    ("Bodzentyn", "Polska"),
    ("Bogatynia", "Polska"),
    ("Boguchwała", "Polska"),
    ("Boguszów-Gorce", "Polska"),
    ("Bojanowo", "Polska"),
    ("Bolesławiec", "Polska"),
    ("Bolimów", "Polska"),
    ("Borek Wielkopolski", "Polska"),
    ("Borne Sulinowo", "Polska"),
    ("Braniewo", "Polska"),
    ("Brańsk", "Polska"),
    ("Brdów", "Polska"),
    ("Brodnica", "Polska"),
    ("Brok", "Polska"),
    ("Brusy", "Polska"),
    ("Brwinów", "Polska"),
    ("Brzeg", "Polska"),
    ("Brzeg Dolny", "Polska"),
    ("Brzesko", "Polska"),
    ("Brzeszcze", "Polska"),
    ("Brzeziny", "Polska"),
    ("Brześć Kujawski", "Polska"),
    ("Brzostek", "Polska"),
    ("Brzozów", "Polska"),
    ("Brójce", "Polska"),
    ("Budziszewice", "Polska"),
    ("Budzyń", "Polska"),
    ("Buk", "Polska"),
    ("Bukowno", "Polska"),
    ("Busko-Zdrój", "Polska"),
    ("Bychawa", "Polska"),
    ("Byczyna", "Polska"),
    ("Bydgoszcz", "Polska"),
    ("Bystrzyca Kłodzka", "Polska"),
    ("Bytom", "Polska"),
    ("Będzin", "Polska"),
    ("Błaszki", "Polska"),
    ("Błażowa", "Polska"),
    ("Błonie", "Polska"),
    ("Carrodunum", "Polska"),
    ("Cedynia", "Polska"),
    ("Cegłów", "Polska"),
    ("Chełm", "Polska"),
    ("Chełmek", "Polska"),
    ("Chełmno", "Polska"),
    ("Chełmża", "Polska"),
    ("Chmielnik", "Polska"),
    ("Chocianów", "Polska"),
    ("Chociwel", "Polska"),
    ("Chocz", "Polska"),
    ("Chodecz", "Polska"),
    ("Chodzież", "Polska"),
    ("Chojna", "Polska"),
    ("Chojnice", "Polska"),
    ("Chojnów", "Polska"),
    ("Choroszcz", "Polska"),
    ("Chorzele", "Polska"),
    ("Chorzów", "Polska"),
    ("Choszczno", "Polska"),
    ("Chrzanów", "Polska"),
    ("Chęciny", "Polska"),
    ("Ciechanowiec", "Polska"),
    ("Ciechanów", "Polska"),
    ("Ciechocinek", "Polska"),
    ("Cieszanów", "Polska"),
    ("Cieszyn", "Polska"),
    ("Ciężkowice", "Polska"),
    ("Cybinka", "Polska"),
    ("Czaplinek", "Polska"),
    ("Czarna Białostocka", "Polska"),
    ("Czarna Woda", "Polska"),
    ("Czarne", "Polska"),
    ("Czarnków", "Polska"),
    ("Czchów", "Polska"),
    ("Czechowice-Dziedzice", "Polska"),
    ("Czeladź", "Polska"),
    ("Czempiń", "Polska"),
    ("Czerniejewo", "Polska"),
    ("Czersk", "Polska"),
    ("Czerwieńsk", "Polska"),
    ("Czerwionka-Leszczyny", "Polska"),
    ("Czerwińsk nad Wisłą", "Polska"),
    ("Czyżew", "Polska"),
    ("Częstochowa", "Polska"),
    ("Człopa", "Polska"),
    ("Człuchów", "Polska"),
    ("Daleszyce", "Polska"),
    ("Darłowo", "Polska"),
    ("Debrzno", "Polska"),
    ("Dobczyce", "Polska"),
    ("Dobiegniew", "Polska"),
    ("Dobieszczyn", "Polska"),
    ("Dobra", "Polska"),
    ("Dobre Miasto", "Polska"),
    ("Dobrodzień", "Polska"),
    ("Dobrzany", "Polska"),
    ("Dobrzyca", "Polska"),
    ("Dobrzyń (Golub-Dobrzyń)", "Polska"),
    ("Dobrzyń nad Wisłą", "Polska"),
    ("Dolsk", "Polska"),
    ("Dorohusk", "Polska"),
    ("Drawno", "Polska"),
    ("Drawsko Pomorskie", "Polska"),
    ("Drobin", "Polska"),
    ("Drohiczyn", "Polska"),
    ("Drzewica", "Polska"),
    ("Dukla", "Polska"),
    ("Duszniki-Zdrój", "Polska"),
    ("Dynów", "Polska"),
    ("Działdowo", "Polska"),
    ("Działoszyce", "Polska"),
    ("Działoszyn", "Polska"),
    ("Dzierzgoń", "Polska"),
    ("Dzierżoniów", "Polska"),
    ("Dziwnów", "Polska"),
    ("Dąbie", "Polska"),
    ("Dąbrowa Białostocka", "Polska"),
    ("Dąbrowa Górnicza", "Polska"),
    ("Dąbrowa Tarnowska", "Polska"),
    ("Dąbrowice", "Polska"),
    ("Dębica", "Polska"),
    ("Dęblin", "Polska"),
    ("Dębno", "Polska"),
    ("Elbląg", "Polska"),
    ("Ełk", "Polska"),
    ("Fordon", "Polska"),
    ("Frampol", "Polska"),
    ("Frombork", "Polska"),
    ("Garwolin", "Polska"),
    ("Gdańsk", "Polska"),
    ("Gdynia", "Polska"),
    ("Giżycko", "Polska"),
    ("Glinojeck", "Polska"),
    ("Gliwice", "Polska"),
    ("Gmina Bolimów", "Polska"),
    ("Gniew", "Polska"),
    ("Gniewkowo", "Polska"),
    ("Gniezno", "Polska"),
    ("Gogolin", "Polska"),
    ("Golczewo", "Polska"),
    ("Goleniów", "Polska"),
    ("Golina", "Polska"),
    ("Golub", "Polska"),
    ("Golub-Dobrzyń", "Polska"),
    ("Goniądz", "Polska"),
    ("Gorlice", "Polska"),
    ("Gorzyczki", "Polska"),
    ("Gorzów Wielkopolski", "Polska"),
    ("Gorzów Śląski", "Polska"),
    ("Gostynin", "Polska"),
    ("Gostyń", "Polska"),
    ("Goszczyn", "Polska"),
    ("Gozdnica", "Polska"),
    ("Gołańcz", "Polska"),
    ("Gołdap", "Polska"),
    ("Gościno", "Polska"),
    ("Grabów", "Polska"),
    ("Grabów nad Prosną", "Polska"),
    ("Grajewo", "Polska"),
    ("Grodków", "Polska"),
    ("Grodzisk Mazowiecki", "Polska"),
    ("Grodzisk Wielkopolski", "Polska"),
    ("Grudziądz", "Polska"),
    ("Grybów", "Polska"),
    ("Gryfice", "Polska"),
    ("Gryfino", "Polska"),
    ("Gryfów Śląski", "Polska"),
    ("Grzechotki", "Polska"),
    ("Grójec", "Polska"),
    ("Gubin", "Polska"),
    ("Góra", "Polska"),
    ("Góra Kalwaria", "Polska"),
    ("Górowo Iławeckie", "Polska"),
    ("Górzno", "Polska"),
    ("Gąbin", "Polska"),
    ("Gębice", "Polska"),
    ("Głogów", "Polska"),
    ("Głogów Małopolski", "Polska"),
    ("Głogówek", "Polska"),
    ("Głowno", "Polska"),
    ("Głubczyce", "Polska"),
    ("Głuchołazy", "Polska"),
    ("Głuszyca", "Polska"),
    ("Hajnówka", "Polska"),
    ("Halinów", "Polska"),
    ("Hel", "Polska"),
    ("Hrebenne", "Polska"),
    ("Hrubieszów", "Polska"),
    ("Imielin", "Polska"),
    ("Inowrocław", "Polska"),
    ("Inowłódz", "Polska"),
    ("Iwaniska", "Polska"),
    ("Iwonicz-Zdrój", "Polska"),
    ("Izbica Kujawska", "Polska"),
    ("Iława", "Polska"),
    ("Iłowa", "Polska"),
    ("Iłża", "Polska"),
    ("Ińsko", "Polska"),
    ("Jabłonowo Pomorskie", "Polska"),
    ("Jadów", "Polska"),
    ("Janikowo", "Polska"),
    ("Janowiec Wielkopolski", "Polska"),
    ("Janowo", "Polska"),
    ("Janów Lubelski", "Polska"),
    ("Jaraczewo", "Polska"),
    ("Jarocin", "Polska"),
    ("Jarosław", "Polska"),
    ("Jastarnia", "Polska"),
    ("Jastrowie", "Polska"),
    ("Jastrzębie-Zdrój", "Polska"),
    ("Jasło", "Polska"),
    ("Jawor", "Polska"),
    ("Jedlicze", "Polska"),
    ("Jedlina-Zdrój", "Polska"),
    ("Jedwabne", "Polska"),
    ("Jelcz-Laskowice", "Polska"),
    ("Jelenia Góra", "Polska"),
    ("Jeziorany", "Polska"),
    ("Jeżów", "Polska"),
    ("Jordanów", "Polska"),
    ("Jutrosin", "Polska"),
    ("Józefów", "Polska"),
    ("Józefów nad Wisłą", "Polska"),
    ("Jędrzejów", "Polska"),
    ("Jędrzychowice", "Polska"),
    ("Kalety", "Polska"),
    ("Kalisz", "Polska"),
    ("Kalisz Pomorski", "Polska"),
    ("Kalwaria Zebrzydowska", "Polska"),
    ("Kamienna Góra", "Polska"),
    ("Kamień Krajeński", "Polska"),
    ("Kamień Pomorski", "Polska"),
    ("Kamieńczyk", "Polska"),
    ("Kamieńsk", "Polska"),
    ("Karczew", "Polska"),
    ("Kargowa", "Polska"),
    ("Karlino", "Polska"),
    ("Karpacz", "Polska"),
    ("Kartuzy", "Polska"),
    ("Katowice", "Polska"),
    ("Kazimierz Dolny", "Polska"),
    ("Kazimierza Wielka", "Polska"),
    ("Kałuszyn", "Polska"),
    ("Kańczuga", "Polska"),
    ("Kcynia", "Polska"),
    ("Kielce", "Polska"),
    ("Kietrz", "Polska"),
    ("Kisielice", "Polska"),
    ("Kleczew", "Polska"),
    ("Kleszczele", "Polska"),
    ("Klimontów", "Polska"),
    ("Kluczbork", "Polska"),
    ("Knurów", "Polska"),
    ("Knyszyn", "Polska"),
    ("Kobylin", "Polska"),
    ("Kobyłka", "Polska"),
    ("Kock", "Polska"),
    ("Kodeń", "Polska"),
    ("Kolbuszowa", "Polska"),
    ("Kolno", "Polska"),
    ("Kolonowskie", "Polska"),
    ("Koluszki", "Polska"),
    ("Koniecpol", "Polska"),
    ("Konin", "Polska"),
    ("Konstancin-Jeziorna", "Polska"),
    ("Konstantynów Łódzki", "Polska"),
    ("Konurbacja górnośląska", "Polska"),
    ("Koprzywnica", "Polska"),
    ("Korczowa", "Polska"),
    ("Korfantów", "Polska"),
    ("Koronowo", "Polska"),
    ("Korsze", "Polska"),
    ("Kostrzyn", "Polska"),
    ("Kostrzyn nad Odrą", "Polska"),
    ("Koszalin", "Polska"),
    ("Koszyce", "Polska"),
    ("Kosów Lacki", "Polska"),
    ("Kowal", "Polska"),
    ("Kowalewo Pomorskie", "Polska"),
    ("Kowary", "Polska"),
    ("Koziegłowy", "Polska"),
    ("Kozienice", "Polska"),
    ("Kołaczyce", "Polska"),
    ("Kołbaskowo", "Polska"),
    ("Koło", "Polska"),
    ("Kołobrzeg", "Polska"),
    ("Końskie", "Polska"),
    ("Kościan", "Polska"),
    ("Kościerzyna", "Polska"),
    ("Koźle", "Polska"),
    ("Koźmin Wielkopolski", "Polska"),
    ("Kożuchów", "Polska"),
    ("Krajenka", "Polska"),
    ("Krajnik Dolny", "Polska"),
    ("Kraków", "Polska"),
    ("Krapkowice", "Polska"),
    ("Krasnobród", "Polska"),
    ("Krasnystaw", "Polska"),
    ("Kraśnik", "Polska"),
    ("Krobia", "Polska"),
    ("Krosno", "Polska"),
    ("Krosno Odrzańskie", "Polska"),
    ("Krotoszyn", "Polska"),
    ("Krośniewice", "Polska"),
    ("Kruszwica", "Polska"),
    ("Krynica Morska", "Polska"),
    ("Krynica-Zdrój", "Polska"),
    ("Krynki", "Polska"),
    ("Krzanowice", "Polska"),
    ("Krzepice", "Polska"),
    ("Krzeszowice", "Polska"),
    ("Krzywiń", "Polska"),
    ("Krzyż Wielkopolski", "Polska"),
    ("Książ Wielkopolski", "Polska"),
    ("Kudowa-Zdrój", "Polska"),
    ("Kukuryki", "Polska"),
    ("Kunowice", "Polska"),
    ("Kunów", "Polska"),
    ("Kutno", "Polska"),
    ("Kuźnia Raciborska", "Polska"),
    ("Kuźnica", "Polska"),
    ("Kwidzyn", "Polska"),
    ("Kórnik", "Polska"),
    ("Kąty Wrocławskie", "Polska"),
    ("Kędzierzyn-Koźle", "Polska"),
    ("Kępice", "Polska"),
    ("Kępno", "Polska"),
    ("Kętrzyn", "Polska"),
    ("Kęty", "Polska"),
    ("Kłecko", "Polska"),
    ("Kłobuck", "Polska"),
    ("Kłodawa", "Polska"),
    ("Kłodzko", "Polska"),
    ("Latowicz", "Polska"),
    ("Legionowo", "Polska"),
    ("Legnica", "Polska"),
    ("Lesko", "Polska"),
    ("Leszna Górna", "Polska"),
    ("Leszno", "Polska"),
    ("Lewin Brzeski", "Polska"),
    ("Leśna", "Polska"),
    ("Leśnica", "Polska"),
    ("Leżajsk", "Polska"),
    ("Libiąż", "Polska"),
    ("Lidzbark", "Polska"),
    ("Lidzbark Warmiński", "Polska"),
    ("Lipiany", "Polska"),
    ("Lipno", "Polska"),
    ("Lipsk", "Polska"),
    ("Litzmannstadt", "Polska"),
    ("Lubaczów", "Polska"),
    ("Lubartów", "Polska"),
    ("Lubawa", "Polska"),
    ("Lubawka", "Polska"),
    ("Lubań", "Polska"),
    ("Lubień Kujawski", "Polska"),
    ("Lubin", "Polska"),
    ("Lublin", "Polska"),
    ("Lubliniec", "Polska"),
    ("Lubniewice", "Polska"),
    ("Lubowidz", "Polska"),
    ("Luboń", "Polska"),
    ("Lubraniec", "Polska"),
    ("Lubsko", "Polska"),
    ("Lubusz", "Polska"),
    ("Lubycza Królewska", "Polska"),
    ("Lutomiersk", "Polska"),
    ("Lututów", "Polska"),
    ("Lwówek", "Polska"),
    ("Lwówek Śląski", "Polska"),
    ("Lębork", "Polska"),
    ("Lędziny", "Polska"),
    ("Maków Mazowiecki", "Polska"),
    ("Maków Podhalański", "Polska"),
    ("Malbork", "Polska"),
    ("Margonin", "Polska"),
    ("Marki", "Polska"),
    ("Maszewo", "Polska"),
    ("Małogoszcz", "Polska"),
    ("Małomice", "Polska"),
    ("Medyka", "Polska"),
    ("Miasteczko Śląskie", "Polska"),
    ("Miastko", "Polska"),
    ("Michałowo", "Polska"),
    ("Miechów", "Polska"),
    ("Miejska Górka", "Polska"),
    ("Mielec", "Polska"),
    ("Mielno", "Polska"),
    ("Mieroszów", "Polska"),
    ("Mieszkowice", "Polska"),
    ("Mieścisko", "Polska"),
    ("Mikołajki", "Polska"),
    ("Mikołów", "Polska"),
    ("Mikstat", "Polska"),
    ("Milanówek", "Polska"),
    ("Milicz", "Polska"),
    ("Mirsk", "Polska"),
    ("Międzybórz", "Polska"),
    ("Międzychód", "Polska"),
    ("Międzyrzec Podlaski", "Polska"),
    ("Międzyrzecz", "Polska"),
    ("Międzyzdroje", "Polska"),
    ("Miękinia", "Polska"),
    ("Miłakowo", "Polska"),
    ("Miłomłyn", "Polska"),
    ("Miłosław", "Polska"),
    ("Mińsk Mazowiecki", "Polska"),
    ("Modliborzyce", "Polska"),
    ("Mogielnica", "Polska"),
    ("Mogilno", "Polska"),
    ("Morawica", "Polska"),
    ("Mordy", "Polska"),
    ("Moryń", "Polska"),
    ("Morąg", "Polska"),
    ("Mosina", "Polska"),
    ("Mońki", "Polska"),
    ("Mrocza", "Polska"),
    ("Mrozy", "Polska"),
    ("Mrągowo", "Polska"),
    ("Mszana Dolna", "Polska"),
    ("Mszczonów", "Polska"),
    ("Murowana Goślina", "Polska"),
    ("Muszyna", "Polska"),
    ("Myszków", "Polska"),
    ("Myszyniec", "Polska"),
    ("Mysłowice", "Polska"),
    ("Myślenice", "Polska"),
    ("Myślibórz", "Polska"),
    ("Mława", "Polska"),
    ("Młynary", "Polska"),
    ("Nakło nad Notecią", "Polska"),
    ("Namysłów", "Polska"),
    ("Narol", "Polska"),
    ("Nasielsk", "Polska"),
    ("Nałęczów", "Polska"),
    ("Nekla", "Polska"),
    ("Nidzica", "Polska"),
    ("Niemodlin", "Polska"),
    ("Niepołomice", "Polska"),
    ("Nieszawa", "Polska"),
    ("Nisko", "Polska"),
    ("Nowa Dęba", "Polska"),
    ("Nowa Ruda", "Polska"),
    ("Nowa Sarzyna", "Polska"),
    ("Nowa Sól", "Polska"),
    ("Nowa Słupia", "Polska"),
    ("Nowe Brzesko", "Polska"),
    ("Nowe Miasto", "Polska"),
    ("Nowe Miasto Lubawskie", "Polska"),
    ("Nowe Miasto nad Pilicą", "Polska"),
    ("Nowe Skalmierzyce", "Polska"),
    ("Nowogard", "Polska"),
    ("Nowogród", "Polska"),
    ("Nowogród Bobrzański", "Polska"),
    ("Nowy Dwór Gdański", "Polska"),
    ("Nowy Dwór Mazowiecki", "Polska"),
    ("Nowy Korczyn", "Polska"),
    ("Nowy Staw", "Polska"),
    ("Nowy Sącz", "Polska"),
    ("Nowy Targ", "Polska"),
    ("Nowy Tomyśl", "Polska"),
    ("Nowy Wiśnicz", "Polska"),
    ("Nysa", "Polska"),
    ("Oborniki", "Polska"),
    ("Oborniki Śląskie", "Polska"),
    ("Obrzycko", "Polska"),
    ("Odolanów", "Polska"),
    ("Ogrodzieniec", "Polska"),
    ("Okonek", "Polska"),
    ("Olecko", "Polska"),
    ("Olesno", "Polska"),
    ("Oleszyce", "Polska"),
    ("Oleśnica", "Polska"),
    ("Olkusz", "Polska"),
    ("Olsztyn", "Polska"),
    ("Olsztynek", "Polska"),
    ("Olszyna", "Polska"),
    ("Opalenica", "Polska"),
    ("Opatowiec", "Polska"),
    ("Opatów", "Polska"),
    ("Opatówek", "Polska"),
    ("Opoczno", "Polska"),
    ("Opole", "Polska"),
    ("Opole Lubelskie", "Polska"),
    ("Orneta", "Polska"),
    ("Orzesze", "Polska"),
    ("Osieczna", "Polska"),
    ("Osiek", "Polska"),
    ("Osinów Dolny", "Polska"),
    ("Ostroróg", "Polska"),
    ("Ostrowiec Świętokrzyski", "Polska"),
    ("Ostrołęka", "Polska"),
    ("Ostrzeszów", "Polska"),
    ("Ostróda", "Polska"),
    ("Ostrów Lubelski", "Polska"),
    ("Ostrów Mazowiecka", "Polska"),
    ("Ostrów Wielkopolski", "Polska"),
    ("Otmuchów", "Polska"),
    ("Otwock", "Polska"),
    ("Otyń", "Polska"),
    ("Ozimek", "Polska"),
    ("Ozorków", "Polska"),
    ("Oława", "Polska"),
    ("Ośno Lubuskie", "Polska"),
    ("Oświęcim", "Polska"),
    ("Ożarów", "Polska"),
    ("Ożarów Mazowiecki", "Polska"),
    ("Pabianice", "Polska"),
    ("Pacanów", "Polska"),
    ("Paczków", "Polska"),
    ("Pajęczno", "Polska"),
    ("Pakość", "Polska"),
    ("Parczew", "Polska"),
    ("Pasym", "Polska"),
    ("Pasłęk", "Polska"),
    ("Pelplin", "Polska"),
    ("Pełczyce", "Polska"),
    ("Piaseczno", "Polska"),
    ("Piaski", "Polska"),
    ("Piastów", "Polska"),
    ("Piechowice", "Polska"),
    ("Piekary Śląskie", "Polska"),
    ("Pielgrzymów", "Polska"),
    ("Pieniężno", "Polska"),
    ("Pierzchnica", "Polska"),
    ("Pieńsk", "Polska"),
    ("Pilawa", "Polska"),
    ("Pilica", "Polska"),
    ("Pilzno", "Polska"),
    ("Pionki", "Polska"),
    ("Piotrków Kujawski", "Polska"),
    ("Piotrków Trybunalski", "Polska"),
    ("Pisz", "Polska"),
    ("Piwniczna-Zdrój", "Polska"),
    ("Piątek", "Polska"),
    ("Piła", "Polska"),
    ("Piława Górna", "Polska"),
    ("Pińczów", "Polska"),
    ("Pleszew", "Polska"),
    ("Pniewy", "Polska"),
    ("Pobiedziska", "Polska"),
    ("Poddębice", "Polska"),
    ("Podkowa Leśna", "Polska"),
    ("Pogorzela", "Polska"),
    ("Polanica-Zdrój", "Polska"),
    ("Polanów", "Polska"),
    ("Police", "Polska"),
    ("Polkowice", "Polska"),
    ("Poniatowa", "Polska"),
    ("Poniec", "Polska"),
    ("Porajów", "Polska"),
    ("Porąbka", "Polska"),
    ("Poręba", "Polska"),
    ("Poznań", "Polska"),
    ("Połaniec", "Polska"),
    ("Połczyn-Zdrój", "Polska"),
    ("Połowce", "Polska"),
    ("Prabuty", "Polska"),
    ("Praszka", "Polska"),
    ("Prochowice", "Polska"),
    ("Proszowice", "Polska"),
    ("Pruchnik", "Polska"),
    ("Prudnik", "Polska"),
    ("Prusice", "Polska"),
    ("Pruszcz", "Polska"),
    ("Pruszcz Gdański", "Polska"),
    ("Pruszków", "Polska"),
    ("Przasnysz", "Polska"),
    ("Przecław", "Polska"),
    ("Przedbórz", "Polska"),
    ("Przedecz", "Polska"),
    ("Przemków", "Polska"),
    ("Przemyśl", "Polska"),
    ("Przeworsk", "Polska"),
    ("Przewóz", "Polska"),
    ("Przysucha", "Polska"),
    ("Prószków", "Polska"),
    ("Psie Pole", "Polska"),
    ("Pszczyna", "Polska"),
    ("Pszów", "Polska"),
    ("Puck", "Polska"),
    ("Puszczykowo", "Polska"),
    ("Puławy", "Polska"),
    ("Pułtusk", "Polska"),
    ("Pyrzyce", "Polska"),
    ("Pyskowice", "Polska"),
    ("Pyzdry", "Polska"),
    ("Płock", "Polska"),
    ("Płoty", "Polska"),
    ("Płońsk", "Polska"),
    ("Rabka-Zdrój", "Polska"),
    ("Racibórz", "Polska"),
    ("Raciąż", "Polska"),
    ("Radków", "Polska"),
    ("Radlin", "Polska"),
    ("Radom", "Polska"),
    ("Radomsko", "Polska"),
    ("Radomyśl Wielki", "Polska"),
    ("Radoszyce", "Polska"),
    ("Radymno", "Polska"),
    ("Radziejów", "Polska"),
    ("Radzionków", "Polska"),
    ("Radzymin", "Polska"),
    ("Radzyń Chełmiński", "Polska"),
    ("Radzyń Podlaski", "Polska"),
    ("Radłów", "Polska"),
    ("Rajgród", "Polska"),
    ("Rakoniewice", "Polska"),
    ("Raszków", "Polska"),
    ("Rawa Mazowiecka", "Polska"),
    ("Rawicz", "Polska"),
    ("Recz", "Polska"),
    ("Rejowiec", "Polska"),
    ("Rejowiec Fabryczny", "Polska"),
    ("Reszel", "Polska"),
    ("Rezydencja Prezydenta RP na Mierzei Helskiej", "Polska"),
    ("Rogoźno", "Polska"),
    ("Ropczyce", "Polska"),
    ("Rozprza", "Polska"),
    ("Ruciane-Nida", "Polska"),
    ("Ruda Śląska", "Polska"),
    ("Rudnik nad Sanem", "Polska"),
    ("Rybnik", "Polska"),
    ("Rychwał", "Polska"),
    ("Rydułtowy", "Polska"),
    ("Rydzyna", "Polska"),
    ("Ryglice", "Polska"),
    ("Ryki", "Polska"),
    ("Rymanów", "Polska"),
    ("Rypin", "Polska"),
    ("Rzepin", "Polska"),
    ("Rzeszów", "Polska"),
    ("Rzgów", "Polska"),
    ("Różan", "Polska"),
    ("Sandomierz", "Polska"),
    ("Sanniki", "Polska"),
    ("Sanok", "Polska"),
    ("Sejny", "Polska"),
    ("Serock", "Polska"),
    ("Sianów", "Polska"),
    ("Siechnice", "Polska"),
    ("Siedlce", "Polska"),
    ("Siedliszcze", "Polska"),
    ("Siemianowice Śląskie", "Polska"),
    ("Siemiatycze", "Polska"),
    ("Sieniawa", "Polska"),
    ("Sieradz", "Polska"),
    ("Sieraków", "Polska"),
    ("Sierpc", "Polska"),
    ("Skalbmierz", "Polska"),
    ("Skarszewy", "Polska"),
    ("Skaryszew", "Polska"),
    ("Skarżysko-Kamienna", "Polska"),
    ("Skawina", "Polska"),
    ("Skała", "Polska"),
    ("Skierniewice", "Polska"),
    ("Skoczów", "Polska"),
    ("Skoki", "Polska"),
    ("Skórcz", "Polska"),
    ("Skępe", "Polska"),
    ("Sobótka", "Polska"),
    ("Sochaczew", "Polska"),
    ("Sochocin", "Polska"),
    ("Sokołów Małopolski", "Polska"),
    ("Sokołów Podlaski", "Polska"),
    ("Sokółka", "Polska"),
    ("Solec Kujawski", "Polska"),
    ("Sompolno", "Polska"),
    ("Sopot", "Polska"),
    ("Sosnowiec", "Polska"),
    ("Sośnicowice", "Polska"),
    ("Stalowa Wola", "Polska"),
    ("Starachowice", "Polska"),
    ("Stargard", "Polska"),
    ("Starogard Gdański", "Polska"),
    ("Stary Sącz", "Polska"),
    ("Staszów", "Polska"),
    ("Stawiski", "Polska"),
    ("Stawiszyn", "Polska"),
    ("Stoczek Łukowski", "Polska"),
    ("Stopnica", "Polska"),
    ("Stronie Śląskie", "Polska"),
    ("Strumień", "Polska"),
    ("Stryków", "Polska"),
    ("Strzegom", "Polska"),
    ("Strzelce Krajeńskie", "Polska"),
    ("Strzelce Opolskie", "Polska"),
    ("Strzelno", "Polska"),
    ("Strzyżów", "Polska"),
    ("Stąporków", "Polska"),
    ("Stęszew", "Polska"),
    ("Sucha Beskidzka", "Polska"),
    ("Suchań", "Polska"),
    ("Suchedniów", "Polska"),
    ("Suchowola", "Polska"),
    ("Sulechów", "Polska"),
    ("Sulejów", "Polska"),
    ("Sulejówek", "Polska"),
    ("Sulmierzyce", "Polska"),
    ("Sulęcin", "Polska"),
    ("Supraśl", "Polska"),
    ("Suraż", "Polska"),
    ("Susz", "Polska"),
    ("Suwałki", "Polska"),
    ("Sułkowice", "Polska"),
    ("Swarzędz", "Polska"),
    ("Syców", "Polska"),
    ("Szadek", "Polska"),
    ("Szamocin", "Polska"),
    ("Szamotuły", "Polska"),
    ("Szczawnica", "Polska"),
    ("Szczawno-Zdrój", "Polska"),
    ("Szczebrzeszyn", "Polska"),
    ("Szczecin", "Polska"),
    ("Szczecinek", "Polska"),
    ("Szczekociny", "Polska"),
    ("Szczucin", "Polska"),
    ("Szczuczyn", "Polska"),
    ("Szczyrk", "Polska"),
    ("Szczytno", "Polska"),
    ("Szepietowo", "Polska"),
    ("Szklarska Poręba", "Polska"),
    ("Szlichtyngowa", "Polska"),
    ("Szprotawa", "Polska"),
    ("Sztum", "Polska"),
    ("Szubin", "Polska"),
    ("Szydłowiec", "Polska"),
    ("Szydłów", "Polska"),
    ("Sędziszów", "Polska"),
    ("Sędziszów Małopolski", "Polska"),
    ("Sępopol", "Polska"),
    ("Sępólno Krajeńskie", "Polska"),
    ("Sława", "Polska"),
    ("Sławatycze", "Polska"),
    ("Sławków", "Polska"),
    ("Sławniowice", "Polska"),
    ("Sławno", "Polska"),
    ("Słomniki", "Polska"),
    ("Słubice", "Polska"),
    ("Słupca", "Polska"),
    ("Słupsk", "Polska"),
    ("Tarnobrzeg", "Polska"),
    ("Tarnogród", "Polska"),
    ("Tarnowskie Góry", "Polska"),
    ("Tarnów", "Polska"),
    ("Tczew", "Polska"),
    ("Terespol", "Polska"),
    ("Tolkmicko", "Polska"),
    ("Tomaszów Lubelski", "Polska"),
    ("Tomaszów Mazowiecki", "Polska"),
    ("Toruń", "Polska"),
    ("Torzym", "Polska"),
    ("Toszek", "Polska"),
    ("Trakiszki", "Polska"),
    ("Truso", "Polska"),
    ("Trzcianka", "Polska"),
    ("Trzciel", "Polska"),
    ("Trzcińsko-Zdrój", "Polska"),
    ("Trzebiatów", "Polska"),
    ("Trzebinia", "Polska"),
    ("Trzebnica", "Polska"),
    ("Trzemeszno", "Polska"),
    ("Tuchola", "Polska"),
    ("Tuchów", "Polska"),
    ("Tuczno", "Polska"),
    ("Tuliszków", "Polska"),
    ("Turek", "Polska"),
    ("Tuszyn", "Polska"),
    ("Tułowice", "Polska"),
    ("Twardogóra", "Polska"),
    ("Tychowo", "Polska"),
    ("Tychy", "Polska"),
    ("Tyczyn", "Polska"),
    ("Tykocin", "Polska"),
    ("Tyszowce", "Polska"),
    ("Tłuszcz", "Polska"),
    ("Ujazd", "Polska"),
    ("Ujście", "Polska"),
    ("Ulanów", "Polska"),
    ("Uniejów", "Polska"),
    ("Urzędów", "Polska"),
    ("Ustka", "Polska"),
    ("Ustroń", "Polska"),
    ("Ustrzyki Dolne", "Polska"),
    ("Wadowice", "Polska"),
    ("Warka", "Polska"),
    ("Warszawa", "Polska"),
    ("Warta", "Polska"),
    ("Wasilków", "Polska"),
    ("Wałbrzych", "Polska"),
    ("Wałcz", "Polska"),
    ("Wejherowo", "Polska"),
    ("Werchrata", "Polska"),
    ("Wesoła", "Polska"),
    ("Wieleń", "Polska"),
    ("Wielichowo", "Polska"),
    ("Wieliczka", "Polska"),
    ("Wieluń", "Polska"),
    ("Wieruszów", "Polska"),
    ("Wierzchlas", "Polska"),
    ("Wilamowice", "Polska"),
    ("Wiskitki", "Polska"),
    ("Wisła", "Polska"),
    ("Witkowo", "Polska"),
    ("Więcbork", "Polska"),
    ("Wiślica", "Polska"),
    ("Wleń", "Polska"),
    ("Wodzisław Śląski", "Polska"),
    ("Wojcieszów", "Polska"),
    ("Wojkowice", "Polska"),
    ("Wojnicz", "Polska"),
    ("Wolbrom", "Polska"),
    ("Wolbórz", "Polska"),
    ("Wolin", "Polska"),
    ("Wolsztyn", "Polska"),
    ("Wołczyn", "Polska"),
    ("Wołomin", "Polska"),
    ("Wołów", "Polska"),
    ("Woźniki", "Polska"),
    ("Wrocław", "Polska"),
    ("Wronki", "Polska"),
    ("Września", "Polska"),
    ("Wyrzysk", "Polska"),
    ("Wysoka", "Polska"),
    ("Wysokie Mazowieckie", "Polska"),
    ("Wyszków", "Polska"),
    ("Wyszogród", "Polska"),
    ("Wyśmierzyce", "Polska"),
    ("Wąchock", "Polska"),
    ("Wągrowiec", "Polska"),
    ("Węgliniec", "Polska"),
    ("Węgorzewo", "Polska"),
    ("Węgorzyno", "Polska"),
    ("Węgrów", "Polska"),
    ("Władysławowo", "Polska"),
    ("Włocławek", "Polska"),
    ("Włodawa", "Polska"),
    ("Włoszczowa", "Polska"),
    ("Zabrze", "Polska"),
    ("Zabłudów", "Polska"),
    ("Zagórz", "Polska"),
    ("Zagórze", "Polska"),
    ("Zagórów", "Polska"),
    ("Zakliczyn", "Polska"),
    ("Zaklików", "Polska"),
    ("Zakopane", "Polska"),
    ("Zakroczym", "Polska"),
    ("Zalewo", "Polska"),
    ("Zambrów", "Polska"),
    ("Zamość", "Polska"),
    ("Zasieki", "Polska"),
    ("Zator", "Polska"),
    ("Zawadzkie", "Polska"),
    ("Zawichost", "Polska"),
    ("Zawidów", "Polska"),
    ("Zawiercie", "Polska"),
    ("Zbąszynek", "Polska"),
    ("Zbąszyń", "Polska"),
    ("Zduny", "Polska"),
    ("Zduńska Wola", "Polska"),
    ("Zdzieszowice", "Polska"),
    ("Zebrzydowice", "Polska"),
    ("Zelów", "Polska"),
    ("Zgierz", "Polska"),
    ("Zgorzelec", "Polska"),
    ("Zielona Góra", "Polska"),
    ("Zielonka", "Polska"),
    ("Ziębice", "Polska"),
    ("Zosin", "Polska"),
    ("Zwardoń", "Polska"),
    ("Zwierzyniec", "Polska"),
    ("Zwoleń", "Polska"),
    ("Ząbki", "Polska"),
    ("Ząbkowice Śląskie", "Polska"),
    ("Złocieniec", "Polska"),
    ("Złoczew", "Polska"),
    ("Złotoryja", "Polska"),
    ("Złotów", "Polska"),
    ("Ćmielów", "Polska"),
    ("Łabiszyn", "Polska"),
    ("Łagów", "Polska"),
    ("Łapy", "Polska"),
    ("Łasin", "Polska"),
    ("Łask", "Polska"),
    ("Łaskarzew", "Polska"),
    ("Łaszczów", "Polska"),
    ("Łaziska Górne", "Polska"),
    ("Łańcut", "Polska"),
    ("Łeba", "Polska"),
    ("Łobez", "Polska"),
    ("Łobżenica", "Polska"),
    ("Łochów", "Polska"),
    ("Łomianki", "Polska"),
    ("Łomża", "Polska"),
    ("Łosice", "Polska"),
    ("Łowicz", "Polska"),
    ("Łuków", "Polska"),
    ("Łódź", "Polska"),
    ("Łęczna", "Polska"),
    ("Łęczyca", "Polska"),
    ("Łęknica", "Polska"),
    ("Ścinawa", "Polska"),
    ("Ślesin", "Polska"),
    ("Śmigiel", "Polska"),
    ("Śrem", "Polska"),
    ("Środa Wielkopolska", "Polska"),
    ("Środa Śląska", "Polska"),
    ("Świdnica", "Polska"),
    ("Świdnik", "Polska"),
    ("Świdwin", "Polska"),
    ("Świebodzice", "Polska"),
    ("Świebodzin", "Polska"),
    ("Świecie", "Polska"),
    ("Świecko", "Polska"),
    ("Świeradów-Zdrój", "Polska"),
    ("Świerzawa", "Polska"),
    ("Świnoujście", "Polska"),
    ("Świątniki Górne", "Polska"),
    ("Świętochłowice", "Polska"),
    ("Żabno", "Polska"),
    ("Żagań", "Polska"),
    ("Żarki", "Polska"),
    ("Żary", "Polska"),
    ("Żarów", "Polska"),
    ("Żelechów", "Polska"),
    ("Żerków", "Polska"),
    ("Żmigród", "Polska"),
    ("Żnin", "Polska"),
    ("Żory", "Polska"),
    ("Żukowo", "Polska"),
    ("Żuromin", "Polska"),
    ("Żychlin", "Polska"),
    ("Żyrardów", "Polska"),
    ("Żywiec", "Polska"),
]
