"""Seed data for the ``jobs`` SQL table.

Wygenerowano przez ``scripts/build_jobs_seed.py`` (bez ``--liniowy``: brak kodów PKD).
Edytuj wiersze tutaj — ``init_db()`` robi ``INSERT OR IGNORE``.
"""

from __future__ import annotations

from typing import Final, TypedDict


class JobSeed(TypedDict):
    """Jedna pozycja słownika zawodów (tekst gry + opcjonalny kod PKD)."""

    opis: str
    kod: str | None


JOBS_SEED: Final[list[JobSeed]] = [
    {"opis": "adwokat", "kod": None},
    {"opis": "agenci ubezpieczeniowi", "kod": None},
    {"opis": "agent celny", "kod": None},
    {"opis": "agent klarujący", "kod": None},
    {"opis": "agent ubezpieczeniowy", "kod": None},
    {"opis": "agrochemik", "kod": None},
    {"opis": "akredytowany asystent parlamentarny", "kod": None},
    {"opis": "akrobata", "kod": None},
    {"opis": "aktor", "kod": None},
    {"opis": "aktor cyrkowy", "kod": None},
    {"opis": "aktor lalkarz", "kod": None},
    {"opis": "aktorzy", "kod": None},
    {"opis": "aktuariusz", "kod": None},
    {"opis": "akupunkturzysta", "kod": None},
    {"opis": "akwizytor", "kod": None},
    {"opis": "alpinista przemysłowy", "kod": None},
    {"opis": "analitycy finansowi", "kod": None},
    {"opis": "analityk biznesowy", "kod": None},
    {"opis": "analityk finansowy", "kod": None},
    {"opis": "analityk giełdowy", "kod": None},
    {"opis": "analityk inwestycyjny", "kod": None},
    {"opis": "analityk kredytowy", "kod": None},
    {"opis": "analityk kryminalny", "kod": None},
    {"opis": "andragog", "kod": None},
    {"opis": "animator rynku książki", "kod": None},
    {"opis": "ankieter", "kod": None},
    {"opis": "ankieterzy", "kod": None},
    {"opis": "antropolog", "kod": None},
    {"opis": "antykwariusz", "kod": None},
    {"opis": "aparatowy produkcji drożdży", "kod": None},
    {"opis": "aparatowy produkcji octu", "kod": None},
    {"opis": "aparatura medyczna", "kod": None},
    {"opis": "aparatura pomiarowa", "kod": None},
    {"opis": "aptekarz", "kod": None},
    {"opis": "archeolog", "kod": None},
    {"opis": "architekci", "kod": None},
    {"opis": "architekci krajobrazu", "kod": None},
    {"opis": "architekt", "kod": None},
    {"opis": "architekt krajobrazu", "kod": None},
    {"opis": "architekt wnętrz", "kod": None},
    {"opis": "archiwista", "kod": None},
    {"opis": "archiwista zakładowy", "kod": None},
    {"opis": "archiwiści i muzealnicy", "kod": None},
    {"opis": "arkadownik", "kod": None},
    {"opis": "arteterapeuta", "kod": None},
    {"opis": "artysta fotografik", "kod": None},
    {"opis": "artysta grafik", "kod": None},
    {"opis": "artysta malarz", "kod": None},
    {"opis": "artysta rzeźbiarz", "kod": None},
    {"opis": "artyści plastycy", "kod": None},
    {"opis": "astrofizyk", "kod": None},
    {"opis": "astrolog", "kod": None},
    {"opis": "astronom", "kod": None},
    {"opis": "asystenci dentystyczni", "kod": None},
    {"opis": "asystenci nauczycieli", "kod": None},
    {"opis": "asystent dyrektora", "kod": None},
    {"opis": "asystent fryzjera", "kod": None},
    {"opis": "asystent międzykulturowy", "kod": None},
    {"opis": "asystent nauczyciela przedszkola", "kod": None},
    {"opis": "asystent operatora dźwięku", "kod": None},
    {"opis": "asystent operatora obrazu", "kod": None},
    {"opis": "asystent osobisty", "kod": None},
    {"opis": "asystent parlamentarny", "kod": None},
    {"opis": "asystent prawny", "kod": None},
    {"opis": "asystent prokuratora", "kod": None},
    {"opis": "asystent rodziny", "kod": None},
    {"opis": "asystent zarządu", "kod": None},
    {"opis": "asystentka stomatologiczna", "kod": None},
    {"opis": "audiofonolodzy i logopedzi", "kod": None},
    {"opis": "audiofonolog", "kod": None},
    {"opis": "audytor", "kod": None},
    {"opis": "audytor  środowiskowy", "kod": None},
    {"opis": "audytor / kontroler", "kod": None},
    {"opis": "audytor energetyczny", "kod": None},
    {"opis": "automatyk", "kod": None},
    {"opis": "baca", "kod": None},
    {"opis": "bagażowy", "kod": None},
    {"opis": "bandażysta ortopedyczny", "kod": None},
    {"opis": "barista", "kod": None},
    {"opis": "barman", "kod": None},
    {"opis": "barmani", "kod": None},
    {"opis": "bazarze", "kod": None},
    {"opis": "bednarz", "kod": None},
    {"opis": "betoniarz", "kod": None},
    {"opis": "betoniarz-zbrojarz", "kod": None},
    {"opis": "bez zawodu", "kod": None},
    {"opis": "bibliotekarz", "kod": None},
    {"opis": "bibliotekoznawca", "kod": None},
    {"opis": "biegły rewident", "kod": None},
    {"opis": "bieliźniarz", "kod": None},
    {"opis": "bieliźniarz-kołdrzarz", "kod": None},
    {"opis": "bileter", "kod": None},
    {"opis": "biochemik", "kod": None},
    {"opis": "bioenergoterapeuta", "kod": None},
    {"opis": "biofizyk", "kod": None},
    {"opis": "bioinformatyk", "kod": None},
    {"opis": "bioinżynier", "kod": None},
    {"opis": "biolodzy i pokrewni", "kod": None},
    {"opis": "biolog", "kod": None},
    {"opis": "biomasażysta", "kod": None},
    {"opis": "biotechnolog", "kod": None},
    {"opis": "blacharz", "kod": None},
    {"opis": "blacharz budowlany", "kod": None},
    {"opis": "blacharz lotniczy", "kod": None},
    {"opis": "blacharz okrętowy", "kod": None},
    {"opis": "blacharz samochodowy", "kod": None},
    {"opis": "blacharze", "kod": None},
    {"opis": "bloger", "kod": None},
    {"opis": "bloger / vloger", "kod": None},
    {"opis": "bosman portu", "kod": None},
    {"opis": "botanik", "kod": None},
    {"opis": "boy hotelowy", "kod": None},
    {"opis": "brakarz ceramiki", "kod": None},
    {"opis": "brakarz szkła", "kod": None},
    {"opis": "broker edukacyjny", "kod": None},
    {"opis": "broker informacji", "kod": None},
    {"opis": "broker reasekuracyjny", "kod": None},
    {"opis": "broker ubezpieczeniowy", "kod": None},
    {"opis": "brukarz", "kod": None},
    {"opis": "brązownik", "kod": None},
    {"opis": "budownictwo ogólne", "kod": None},
    {"opis": "budownictwo przemysłowe", "kod": None},
    {"opis": "bufetowy", "kod": None},
    {"opis": "bukieciarz", "kod": None},
    {"opis": "bukmacher", "kod": None},
    {"opis": "bursztyniarz", "kod": None},
    {"opis": "cechowniczy", "kod": None},
    {"opis": "ceramicy i pokrewni", "kod": None},
    {"opis": "charakteryzator", "kod": None},
    {"opis": "chemicy", "kod": None},
    {"opis": "chemik", "kod": None},
    {"opis": "chiropraktyk", "kod": None},
    {"opis": "chirurg pielęgniarz drzew", "kod": None},
    {"opis": "cholewkarz", "kod": None},
    {"opis": "choreograf", "kod": None},
    {"opis": "choreografowie i tancerze", "kod": None},
    {"opis": "chóru", "kod": None},
    {"opis": "ciastkarska", "kod": None},
    {"opis": "cieplno", "kod": None},
    {"opis": "cieśla", "kod": None},
    {"opis": "cieśla szalunkowy", "kod": None},
    {"opis": "ciągacz rur", "kod": None},
    {"opis": "cukiernik", "kod": None},
    {"opis": "cukrownictwo", "kod": None},
    {"opis": "cykliniarz", "kod": None},
    {"opis": "cyrku", "kod": None},
    {"opis": "czapnik", "kod": None},
    {"opis": "dekarz", "kod": None},
    {"opis": "dekarze", "kod": None},
    {"opis": "dekorator wnętrz", "kod": None},
    {"opis": "demograf", "kod": None},
    {"opis": "dentysta", "kod": None},
    {"opis": "detektyw prywatny", "kod": None},
    {"opis": "diagnosta kolejowy", "kod": None},
    {"opis": "diagnosta laboratoryjny", "kod": None},
    {"opis": "diagności laboratoryjni", "kod": None},
    {"opis": "diagności laboratoryjni specjaliści", "kod": None},
    {"opis": "dietetycy i żywieniowcy", "kod": None},
    {"opis": "dietetyk", "kod": None},
    {"opis": "docieracz", "kod": None},
    {"opis": "docieracz-polerowacz", "kod": None},
    {"opis": "dojarz", "kod": None},
    {"opis": "doradca emerytalny", "kod": None},
    {"opis": "doradca eures", "kod": None},
    {"opis": "doradca finansowy", "kod": None},
    {"opis": "doradca inwestycyjny", "kod": None},
    {"opis": "doradca klienta", "kod": None},
    {"opis": "doradca personalny", "kod": None},
    {"opis": "doradca podatkowy", "kod": None},
    {"opis": "doradca rolniczy", "kod": None},
    {"opis": "doradca zawodowy", "kod": None},
    {"opis": "dorożkarz", "kod": None},
    {"opis": "dostawca potraw", "kod": None},
    {"opis": "dozorca", "kod": None},
    {"opis": "drobiarskie", "kod": None},
    {"opis": "drukarz", "kod": None},
    {"opis": "drukarz fleksograficzny", "kod": None},
    {"opis": "drukarz offsetowy", "kod": None},
    {"opis": "drukarz sitodrukowy", "kod": None},
    {"opis": "drukarz tkanin", "kod": None},
    {"opis": "drukarze", "kod": None},
    {"opis": "drwal", "kod": None},
    {"opis": "dróżnik obchodowy", "kod": None},
    {"opis": "dróżnik przejazdowy", "kod": None},
    {"opis": "dydaktyk multimedialny", "kod": None},
    {"opis": "dyrektor departamentu", "kod": None},
    {"opis": "dyrektor finansowy", "kod": None},
    {"opis": "dyrektor generalny", "kod": None},
    {"opis": "dyrektor handlowy", "kod": None},
    {"opis": "dyrektor logistyki", "kod": None},
    {"opis": "dyrektor operacyjny", "kod": None},
    {"opis": "dyrektor placówki opiekuńczo", "kod": None},
    {"opis": "dyrektor rozwoju biznesu", "kod": None},
    {"opis": "dyrektor sprzedaży", "kod": None},
    {"opis": "dyrektor szkoły", "kod": None},
    {"opis": "dyrektor sądu", "kod": None},
    {"opis": "dyrektor teatru", "kod": None},
    {"opis": "dyrektor techniczny", "kod": None},
    {"opis": "dyrektor wykonawczy", "kod": None},
    {"opis": "dyrygent", "kod": None},
    {"opis": "dyspozytor lotniczy", "kod": None},
    {"opis": "dyspozytor radiotaxi", "kod": None},
    {"opis": "dyspozytor ruchu metra", "kod": None},
    {"opis": "dystrybutor ulotek", "kod": None},
    {"opis": "dyżurny ruchu", "kod": None},
    {"opis": "dziekan", "kod": None},
    {"opis": "dziennikarz", "kod": None},
    {"opis": "dziennikarze", "kod": None},
    {"opis": "dziewiarz", "kod": None},
    {"opis": "dźwigowy", "kod": None},
    {"opis": "edukator ekologiczny", "kod": None},
    {"opis": "eguterzysta", "kod": None},
    {"opis": "egzaminator on", "kod": None},
    {"opis": "egzaminator on-line", "kod": None},
    {"opis": "ekolog", "kod": None},
    {"opis": "ekonometryk", "kod": None},
    {"opis": "ekonomista", "kod": None},
    {"opis": "ekonomiści", "kod": None},
    {"opis": "ekspedient pocztowy", "kod": None},
    {"opis": "ekspedient wypożyczalni", "kod": None},
    {"opis": "ekspedytor", "kod": None},
    {"opis": "eksploatator portu", "kod": None},
    {"opis": "elektroenergetyk nastawni", "kod": None},
    {"opis": "elektromechanicy i elektromonterzy", "kod": None},
    {"opis": "elektromechanik", "kod": None},
    {"opis": "elektromonter", "kod": None},
    {"opis": "elektromonter  zakładowy", "kod": None},
    {"opis": "elektromonter lotniczy", "kod": None},
    {"opis": "elektromonter okrętowy", "kod": None},
    {"opis": "elektroniczne instrumenty muzyczne", "kod": None},
    {"opis": "elektronik", "kod": None},
    {"opis": "elektroradiolog", "kod": None},
    {"opis": "elektrycy i elektronicy", "kod": None},
    {"opis": "elektryk", "kod": None},
    {"opis": "elektryk budowlany", "kod": None},
    {"opis": "epidemiolog", "kod": None},
    {"opis": "etnograf", "kod": None},
    {"opis": "fajkarz", "kod": None},
    {"opis": "fakturzystka", "kod": None},
    {"opis": "farmaceuci", "kod": None},
    {"opis": "farmaceuci specjaliści", "kod": None},
    {"opis": "farmaceuta", "kod": None},
    {"opis": "felczer", "kod": None},
    {"opis": "filolodzy i tłumacze", "kod": None},
    {"opis": "filolog klasyczny", "kod": None},
    {"opis": "filolog polski", "kod": None},
    {"opis": "filozof", "kod": None},
    {"opis": "fitoterapeuta", "kod": None},
    {"opis": "fizjolog", "kod": None},
    {"opis": "fizjoterapeuci", "kod": None},
    {"opis": "fizjoterapeuta", "kod": None},
    {"opis": "fizjoterapeuta koni", "kod": None},
    {"opis": "fizycy i astronomowie", "kod": None},
    {"opis": "fizyk", "kod": None},
    {"opis": "fizyk medyczny", "kod": None},
    {"opis": "flisak", "kod": None},
    {"opis": "flisak-retman", "kod": None},
    {"opis": "florysta", "kod": None},
    {"opis": "foniatra", "kod": None},
    {"opis": "formierz odlewnik", "kod": None},
    {"opis": "formowacz ściernic", "kod": None},
    {"opis": "fotoedytor", "kod": None},
    {"opis": "fotograf", "kod": None},
    {"opis": "fotograf poligraficzny", "kod": None},
    {"opis": "fotografowie", "kod": None},
    {"opis": "fotogrametria i teledetekcja", "kod": None},
    {"opis": "fotoreporter", "kod": None},
    {"opis": "fotosista", "kod": None},
    {"opis": "fototechnik", "kod": None},
    {"opis": "frezer", "kod": None},
    {"opis": "frezer drewna", "kod": None},
    {"opis": "fryzjer", "kod": None},
    {"opis": "fryzjer damski", "kod": None},
    {"opis": "fryzjer męski", "kod": None},
    {"opis": "fryzjer zwierząt", "kod": None},
    {"opis": "fryzjerzy", "kod": None},
    {"opis": "funkcjonariusz celny", "kod": None},
    {"opis": "funkcjonariusz służby celno", "kod": None},
    {"opis": "funkcjonariusz służby ochrony", "kod": None},
    {"opis": "galwanizer", "kod": None},
    {"opis": "garbarz skór", "kod": None},
    {"opis": "garderobiana", "kod": None},
    {"opis": "garmażer", "kod": None},
    {"opis": "garncarz", "kod": None},
    {"opis": "gemmolog", "kod": None},
    {"opis": "genetyk", "kod": None},
    {"opis": "geodezja górnicza", "kod": None},
    {"opis": "geodezja inżynieryjno", "kod": None},
    {"opis": "geodeta", "kod": None},
    {"opis": "geofizyk", "kod": None},
    {"opis": "geofizyka górnicza", "kod": None},
    {"opis": "geograf", "kod": None},
    {"opis": "geolog", "kod": None},
    {"opis": "geomatyka", "kod": None},
    {"opis": "giloszer poligraficzny", "kod": None},
    {"opis": "giloszer szkła", "kod": None},
    {"opis": "gięciarz drewna", "kod": None},
    {"opis": "glazurnik", "kod": None},
    {"opis": "gleboznawca", "kod": None},
    {"opis": "goniec", "kod": None},
    {"opis": "gorseciarka", "kod": None},
    {"opis": "gospodarz domu", "kod": None},
    {"opis": "gospodyni", "kod": None},
    {"opis": "grabarz", "kod": None},
    {"opis": "grafik komputerowy dtp", "kod": None},
    {"opis": "grafolog", "kod": None},
    {"opis": "grawer", "kod": None},
    {"opis": "grawer poligraficzny", "kod": None},
    {"opis": "grawer szkła", "kod": None},
    {"opis": "grzyboznawca", "kod": None},
    {"opis": "górnictwo odkrywkowe", "kod": None},
    {"opis": "górnictwo otworowe", "kod": None},
    {"opis": "górnictwo podziemne", "kod": None},
    {"opis": "główny księgowy", "kod": None},
    {"opis": "główny technolog", "kod": None},
    {"opis": "hafciarka", "kod": None},
    {"opis": "hartownik", "kod": None},
    {"opis": "higienistka stomatologiczna", "kod": None},
    {"opis": "higienistka szkolna", "kod": None},
    {"opis": "historyk", "kod": None},
    {"opis": "hodowca bydła", "kod": None},
    {"opis": "hodowca drobiu", "kod": None},
    {"opis": "hodowca koni", "kod": None},
    {"opis": "hodowca owiec", "kod": None},
    {"opis": "hodowca ryb", "kod": None},
    {"opis": "hodowcy drobiu", "kod": None},
    {"opis": "hodowcy ryb", "kod": None},
    {"opis": "hodowcy zwierząt", "kod": None},
    {"opis": "homeopata", "kod": None},
    {"opis": "hostessa", "kod": None},
    {"opis": "hutnik dmuchacz szkła", "kod": None},
    {"opis": "hydraulik", "kod": None},
    {"opis": "hydrograf morski", "kod": None},
    {"opis": "hydrolog", "kod": None},
    {"opis": "hydrologia górnicza", "kod": None},
    {"opis": "hydrometeorolog", "kod": None},
    {"opis": "ilustrator", "kod": None},
    {"opis": "iluzjonista", "kod": None},
    {"opis": "impregnator drewna", "kod": None},
    {"opis": "informacji", "kod": None},
    {"opis": "informatyk", "kod": None},
    {"opis": "informatyk medyczny", "kod": None},
    {"opis": "inkasent", "kod": None},
    {"opis": "inspektor bezpieczeństwa żeglugi", "kod": None},
    {"opis": "inspektor budowlany", "kod": None},
    {"opis": "inspektor budowy dróg", "kod": None},
    {"opis": "inspektor farmaceutyczny", "kod": None},
    {"opis": "inspektor hotelowy", "kod": None},
    {"opis": "inspektor sanitarny", "kod": None},
    {"opis": "inspicjent", "kod": None},
    {"opis": "instalacja anten", "kod": None},
    {"opis": "instalacje sanitarne", "kod": None},
    {"opis": "instruktor fitness", "kod": None},
    {"opis": "instruktor higieny", "kod": None},
    {"opis": "instruktor nauki jazdy", "kod": None},
    {"opis": "instruktor rytmiki", "kod": None},
    {"opis": "instruktor strzałowy", "kod": None},
    {"opis": "instruktor sztuki walki", "kod": None},
    {"opis": "instruktor tańca", "kod": None},
    {"opis": "instruktor techniki jazdy", "kod": None},
    {"opis": "instruktor terapii uzależnień", "kod": None},
    {"opis": "instruktorzy nauki jazdy", "kod": None},
    {"opis": "instrumentalista", "kod": None},
    {"opis": "intendent", "kod": None},
    {"opis": "interwent kryzysowy", "kod": None},
    {"opis": "introligator", "kod": None},
    {"opis": "introligator galanteryjny", "kod": None},
    {"opis": "introligator poligraficzny", "kod": None},
    {"opis": "introligatorzy i pokrewni", "kod": None},
    {"opis": "inwentaryzator", "kod": None},
    {"opis": "inżynier akustyk", "kod": None},
    {"opis": "inżynier awionik", "kod": None},
    {"opis": "inżynier budowy dróg", "kod": None},
    {"opis": "inżynier dekontaminacji", "kod": None},
    {"opis": "inżynier elektroenergetyk", "kod": None},
    {"opis": "inżynier elektronik", "kod": None},
    {"opis": "inżynier elektryk", "kod": None},
    {"opis": "inżynier elektryk automatyk", "kod": None},
    {"opis": "inżynier energetyki", "kod": None},
    {"opis": "inżynier geodeta", "kod": None},
    {"opis": "inżynier geofizyk", "kod": None},
    {"opis": "inżynier geolog", "kod": None},
    {"opis": "inżynier geotechnik", "kod": None},
    {"opis": "inżynier górnik", "kod": None},
    {"opis": "inżynier hutnik", "kod": None},
    {"opis": "inżynier internetu rzeczy", "kod": None},
    {"opis": "inżynier kliniczny", "kod": None},
    {"opis": "inżynier mechanik", "kod": None},
    {"opis": "inżynier mechanik lotniczy", "kod": None},
    {"opis": "inżynier mechatronik", "kod": None},
    {"opis": "inżynier odlewnik", "kod": None},
    {"opis": "inżynier ogrodnictwa", "kod": None},
    {"opis": "inżynier optyk", "kod": None},
    {"opis": "inżynier papiernictwa", "kod": None},
    {"opis": "inżynier pożarnictwa", "kod": None},
    {"opis": "inżynier procesu malowania", "kod": None},
    {"opis": "inżynier rybactwa", "kod": None},
    {"opis": "inżynier spawalnik", "kod": None},
    {"opis": "inżynier sprzedaży", "kod": None},
    {"opis": "inżynier technologii ceramiki", "kod": None},
    {"opis": "inżynier technologii drewna", "kod": None},
    {"opis": "inżynier technologii szkła", "kod": None},
    {"opis": "inżynier technologii żywności", "kod": None},
    {"opis": "inżynier teleinformatyk", "kod": None},
    {"opis": "inżynier telekomunikacji", "kod": None},
    {"opis": "inżynier utrzymania ruchu", "kod": None},
    {"opis": "inżynier włókiennik", "kod": None},
    {"opis": "inżynier zootechniki", "kod": None},
    {"opis": "inżynierowie", "kod": None},
    {"opis": "inżynierowie elektronicy", "kod": None},
    {"opis": "inżynierowie elektrycy", "kod": None},
    {"opis": "inżynierowie mechanicy", "kod": None},
    {"opis": "inżynierowie telekomunikacji", "kod": None},
    {"opis": "jeździec", "kod": None},
    {"opis": "jubiler", "kod": None},
    {"opis": "juhas", "kod": None},
    {"opis": "kaletnik", "kod": None},
    {"opis": "kamieniarz", "kod": None},
    {"opis": "kapelusznik", "kod": None},
    {"opis": "kapelusznik-czapnik", "kod": None},
    {"opis": "karmelarz", "kod": None},
    {"opis": "kartograf", "kod": None},
    {"opis": "kartografowie i geodeci", "kod": None},
    {"opis": "kasjer bankowy", "kod": None},
    {"opis": "kasjer biletowy", "kod": None},
    {"opis": "kasjer handlowy", "kod": None},
    {"opis": "kasjer walutowy", "kod": None},
    {"opis": "kaskader filmowy", "kod": None},
    {"opis": "kelner", "kod": None},
    {"opis": "kelnerzy", "kod": None},
    {"opis": "kelnerzy i barmani", "kod": None},
    {"opis": "kierowca", "kod": None},
    {"opis": "kierowca autobusu", "kod": None},
    {"opis": "kierowca autocysterny", "kod": None},
    {"opis": "kierowca mechanik", "kod": None},
    {"opis": "kierowca trolejbusu", "kod": None},
    {"opis": "kierowcy motocykli", "kod": None},
    {"opis": "kierownicy", "kod": None},
    {"opis": "kierownicy biura", "kod": None},
    {"opis": "kierownicy w górnictwie", "kod": None},
    {"opis": "kierownicy w hotelarstwie", "kod": None},
    {"opis": "kierownik", "kod": None},
    {"opis": "kierownik apteki", "kod": None},
    {"opis": "kierownik archiwum", "kod": None},
    {"opis": "kierownik biblioteki", "kod": None},
    {"opis": "kierownik biura", "kod": None},
    {"opis": "kierownik biura podroży", "kod": None},
    {"opis": "kierownik biura tłumaczeń", "kod": None},
    {"opis": "kierownik budowy", "kod": None},
    {"opis": "kierownik działu administracyjno", "kod": None},
    {"opis": "kierownik działu badawczo", "kod": None},
    {"opis": "kierownik działu logistyki", "kod": None},
    {"opis": "kierownik działu reklamy", "kod": None},
    {"opis": "kierownik działu szkoleń", "kod": None},
    {"opis": "kierownik hospicjum", "kod": None},
    {"opis": "kierownik hostelu", "kod": None},
    {"opis": "kierownik hotelu", "kod": None},
    {"opis": "kierownik hurtowni", "kod": None},
    {"opis": "kierownik kas", "kod": None},
    {"opis": "kierownik kasyna", "kod": None},
    {"opis": "kierownik kempingu", "kod": None},
    {"opis": "kierownik kina", "kod": None},
    {"opis": "kierownik klubu fitness", "kod": None},
    {"opis": "kierownik magazynu", "kod": None},
    {"opis": "kierownik muzeum", "kod": None},
    {"opis": "kierownik parku rozrywki", "kod": None},
    {"opis": "kierownik pensjonatu", "kod": None},
    {"opis": "kierownik pociągu", "kod": None},
    {"opis": "kierownik projektu", "kod": None},
    {"opis": "kierownik przedszkola", "kod": None},
    {"opis": "kierownik punktu skupu", "kod": None},
    {"opis": "kierownik rewiru", "kod": None},
    {"opis": "kierownik sali sprzedaży", "kod": None},
    {"opis": "kierownik siłowni", "kod": None},
    {"opis": "kierownik sklepu", "kod": None},
    {"opis": "kierownik szkoły tańca", "kod": None},
    {"opis": "kierownik utrzymania ruchu", "kod": None},
    {"opis": "kierownik wydawnictwa", "kod": None},
    {"opis": "kierownik wydziału", "kod": None},
    {"opis": "kierownik żłobka", "kod": None},
    {"opis": "kierujący tramwajem", "kod": None},
    {"opis": "kinooperator", "kod": None},
    {"opis": "kioskarz", "kod": None},
    {"opis": "klasyfikator ryb", "kod": None},
    {"opis": "klasyfikator skór", "kod": None},
    {"opis": "klaun", "kod": None},
    {"opis": "klimatolog", "kod": None},
    {"opis": "klubie dziecięcym", "kod": None},
    {"opis": "kodowacz", "kod": None},
    {"opis": "kolektury", "kod": None},
    {"opis": "kolporter", "kod": None},
    {"opis": "kombajnista", "kod": None},
    {"opis": "komendant policji", "kod": None},
    {"opis": "komendant powiatowy", "kod": None},
    {"opis": "komentator sportowy", "kod": None},
    {"opis": "komik", "kod": None},
    {"opis": "kominiarz", "kod": None},
    {"opis": "komornik sądowy", "kod": None},
    {"opis": "kompozytor", "kod": None},
    {"opis": "komputerowy składacz tekstu", "kod": None},
    {"opis": "konduktor", "kod": None},
    {"opis": "konduktorzy i pokrewni", "kod": None},
    {"opis": "konferansjer", "kod": None},
    {"opis": "konserwator części", "kod": None},
    {"opis": "konserwator zabytków architektury", "kod": None},
    {"opis": "konstruktor odzieży", "kod": None},
    {"opis": "konstruktor rozkładów jazdy", "kod": None},
    {"opis": "konsultant", "kod": None},
    {"opis": "kontroler", "kod": None},
    {"opis": "kontroler finansowy", "kod": None},
    {"opis": "kontroler higieny mięsa", "kod": None},
    {"opis": "kontroler kolejowy", "kod": None},
    {"opis": "kontroler państwowy", "kod": None},
    {"opis": "kontroler pocztowy", "kod": None},
    {"opis": "koordynator", "kod": None},
    {"opis": "kopacz", "kod": None},
    {"opis": "korektor tekstu", "kod": None},
    {"opis": "korepetytor", "kod": None},
    {"opis": "koronkarka", "kod": None},
    {"opis": "kosmetolog", "kod": None},
    {"opis": "kosmetyczka", "kod": None},
    {"opis": "kosmetyczki i pokrewni", "kod": None},
    {"opis": "kostiumograf", "kod": None},
    {"opis": "kosztorysant budowlany", "kod": None},
    {"opis": "koszykarz", "kod": None},
    {"opis": "koszykarz-plecionkarz", "kod": None},
    {"opis": "kowal", "kod": None},
    {"opis": "kołdrzarz", "kod": None},
    {"opis": "kościelny", "kod": None},
    {"opis": "kożusznik", "kod": None},
    {"opis": "krajacz szkła", "kod": None},
    {"opis": "krawiec", "kod": None},
    {"opis": "kremator", "kod": None},
    {"opis": "kreślarze", "kod": None},
    {"opis": "krojczy", "kod": None},
    {"opis": "krupier", "kod": None},
    {"opis": "kryminolog", "kod": None},
    {"opis": "krytyk artystyczny", "kod": None},
    {"opis": "krytyk kulinarny", "kod": None},
    {"opis": "rachmistrz", "kod": None},
    {"opis": "księgowi", "kod": None},
    {"opis": "księgowy", "kod": None},
    {"opis": "kucharz", "kod": None},
    {"opis": "kucharze", "kod": None},
    {"opis": "kulturoznawca", "kod": None},
    {"opis": "kurator sądowy", "kod": None},
    {"opis": "kurier", "kod": None},
    {"opis": "kurier motocyklowy", "kod": None},
    {"opis": "kuśnierz", "kod": None},
    {"opis": "kynoterapeuta", "kod": None},
    {"opis": "laborant biochemiczny", "kod": None},
    {"opis": "laborant budowlany", "kod": None},
    {"opis": "laborant chemiczny", "kod": None},
    {"opis": "laborant mikrobiologiczny", "kod": None},
    {"opis": "laborant nasiennictwa", "kod": None},
    {"opis": "laborant weterynaryjny", "kod": None},
    {"opis": "lagowacz", "kod": None},
    {"opis": "lakiernicy", "kod": None},
    {"opis": "lakiernik", "kod": None},
    {"opis": "lakiernik proszkowy", "kod": None},
    {"opis": "lakiernik samochodowy", "kod": None},
    {"opis": "lakiernik samolotowy", "kod": None},
    {"opis": "latarnik", "kod": None},
    {"opis": "legalizator", "kod": None},
    {"opis": "legislator", "kod": None},
    {"opis": "lekarz", "kod": None},
    {"opis": "lekarz dentysta", "kod": None},
    {"opis": "lekarz ordynator oddziału", "kod": None},
    {"opis": "lekarze", "kod": None},
    {"opis": "lekarze dentyści", "kod": None},
    {"opis": "lekarze dentyści specjaliści", "kod": None},
    {"opis": "lekarze specjaliści", "kod": None},
    {"opis": "lekarze weterynarii specjaliści", "kod": None},
    {"opis": "leśnicy i rybacy", "kod": None},
    {"opis": "licytator", "kod": None},
    {"opis": "liczarz", "kod": None},
    {"opis": "likwidator szkód", "kod": None},
    {"opis": "line", "kod": None},
    {"opis": "liniowy", "kod": None},
    {"opis": "listonosz", "kod": None},
    {"opis": "listonosze i pokrewni", "kod": None},
    {"opis": "lobbysta", "kod": None},
    {"opis": "logistyk", "kod": None},
    {"opis": "logopeda", "kod": None},
    {"opis": "ludwisarz", "kod": None},
    {"opis": "lustrzarz", "kod": None},
    {"opis": "lutowacz", "kod": None},
    {"opis": "magazynier", "kod": None},
    {"opis": "magazynier-logistyk", "kod": None},
    {"opis": "magazynierzy i pokrewni", "kod": None},
    {"opis": "maglarz", "kod": None},
    {"opis": "makler morski", "kod": None},
    {"opis": "makler nadzorujący", "kod": None},
    {"opis": "malarz", "kod": None},
    {"opis": "malarz budowlany", "kod": None},
    {"opis": "malarz-lakiernik samolotowy", "kod": None},
    {"opis": "malarz-tapeciarz", "kod": None},
    {"opis": "manewrowy", "kod": None},
    {"opis": "manewrowy metra", "kod": None},
    {"opis": "manikiurzystka", "kod": None},
    {"opis": "marynarze i pokrewni", "kod": None},
    {"opis": "masztalerz", "kod": None},
    {"opis": "maszynista", "kod": None},
    {"opis": "maszynista chłodni", "kod": None},
    {"opis": "maszynista doku", "kod": None},
    {"opis": "maszynista kotła", "kod": None},
    {"opis": "maszynista pociągu metra", "kod": None},
    {"opis": "maszynista sprężarek", "kod": None},
    {"opis": "maszynista urządzeń nawęglania", "kod": None},
    {"opis": "maszynowy szlifierz", "kod": None},
    {"opis": "maszynowy szlifierz-polerowacz szkła", "kod": None},
    {"opis": "matematyk", "kod": None},
    {"opis": "maślarz", "kod": None},
    {"opis": "mechanicy precyzyjni", "kod": None},
    {"opis": "mechanik", "kod": None},
    {"opis": "mechanik motocyklowy", "kod": None},
    {"opis": "mechanik okrętowy", "kod": None},
    {"opis": "mechanik pokładowy", "kod": None},
    {"opis": "mechanik precyzyjny", "kod": None},
    {"opis": "mechanika precyzyjna", "kod": None},
    {"opis": "mechatronik", "kod": None},
    {"opis": "mediator", "kod": None},
    {"opis": "mediator sądowy", "kod": None},
    {"opis": "melioracje", "kod": None},
    {"opis": "meliorant", "kod": None},
    {"opis": "menedżer artystyczny", "kod": None},
    {"opis": "menedżer marki", "kod": None},
    {"opis": "menedżer produktu", "kod": None},
    {"opis": "metaloplastyk", "kod": None},
    {"opis": "meteorolodzy", "kod": None},
    {"opis": "meteorolog", "kod": None},
    {"opis": "metrolog", "kod": None},
    {"opis": "miejski", "kod": None},
    {"opis": "mikrobiolog", "kod": None},
    {"opis": "mikser dźwięku", "kod": None},
    {"opis": "mikser obrazu", "kod": None},
    {"opis": "mim", "kod": None},
    {"opis": "model", "kod": None},
    {"opis": "modelarz odlewniczy", "kod": None},
    {"opis": "modelka", "kod": None},
    {"opis": "modelka / model", "kod": None},
    {"opis": "modelki i modele", "kod": None},
    {"opis": "modystka", "kod": None},
    {"opis": "moletownik", "kod": None},
    {"opis": "montażysta dekoracji", "kod": None},
    {"opis": "montażysta dźwięku", "kod": None},
    {"opis": "montażysta obrazu", "kod": None},
    {"opis": "montażysta reprodukcyjny", "kod": None},
    {"opis": "monter", "kod": None},
    {"opis": "monter bram", "kod": None},
    {"opis": "monter fasad", "kod": None},
    {"opis": "monter konstrukcji targowo", "kod": None},
    {"opis": "monter mebli", "kod": None},
    {"opis": "monter mechatronik", "kod": None},
    {"opis": "monter obrabiarek", "kod": None},
    {"opis": "monter ogrodzeń", "kod": None},
    {"opis": "monter płyt kartonowo", "kod": None},
    {"opis": "monter reklam", "kod": None},
    {"opis": "monter rusztowań", "kod": None},
    {"opis": "monter wiertni", "kod": None},
    {"opis": "monter żaluzji", "kod": None},
    {"opis": "monter-elektronik", "kod": None},
    {"opis": "monterzy", "kod": None},
    {"opis": "monterzy izolacji", "kod": None},
    {"opis": "mostowniczy", "kod": None},
    {"opis": "motelu", "kod": None},
    {"opis": "motorzysta wachtowy", "kod": None},
    {"opis": "murarz", "kod": None},
    {"opis": "murarz-tynkarz", "kod": None},
    {"opis": "murarze i pokrewni", "kod": None},
    {"opis": "murawy", "kod": None},
    {"opis": "muzealnik", "kod": None},
    {"opis": "muzeum", "kod": None},
    {"opis": "muzycy i pokrewni", "kod": None},
    {"opis": "muzyk", "kod": None},
    {"opis": "muzykolog", "kod": None},
    {"opis": "muzykoterapeuta", "kod": None},
    {"opis": "mygłowacz", "kod": None},
    {"opis": "młynarz", "kod": None},
    {"opis": "naczelnik", "kod": None},
    {"opis": "nanotechnolog", "kod": None},
    {"opis": "napełniający zbiorniki przenośne", "kod": None},
    {"opis": "nastawniczy", "kod": None},
    {"opis": "naturopata", "kod": None},
    {"opis": "nauczyciel akademicki", "kod": None},
    {"opis": "nauczyciel bibliotekarz", "kod": None},
    {"opis": "nauczyciel domowy", "kod": None},
    {"opis": "nauczyciel doradca metodyczny", "kod": None},
    {"opis": "nauczyciel konsultant", "kod": None},
    {"opis": "nauczyciel logopeda", "kod": None},
    {"opis": "nauczyciel niedostosowanych społecznie", "kod": None},
    {"opis": "nauczyciel przedszkola", "kod": None},
    {"opis": "nauczyciel psycholog", "kod": None},
    {"opis": "nauczyciele akademiccy", "kod": None},
    {"opis": "nauki humanistyczne", "kod": None},
    {"opis": "nauki inżynieryjno", "kod": None},
    {"opis": "nauki o rodzinie", "kod": None},
    {"opis": "nauki rolnicze", "kod": None},
    {"opis": "nauki społeczne", "kod": None},
    {"opis": "nauki teologiczne", "kod": None},
    {"opis": "nauki weterynaryjne", "kod": None},
    {"opis": "nawigator lotniczy", "kod": None},
    {"opis": "negocjator biznesowy", "kod": None},
    {"opis": "negocjator policyjny", "kod": None},
    {"opis": "neurologopeda", "kod": None},
    {"opis": "normalizator", "kod": None},
    {"opis": "noszowy", "kod": None},
    {"opis": "notariusz", "kod": None},
    {"opis": "nurek", "kod": None},
    {"opis": "nurkowie", "kod": None},
    {"opis": "obchodowy bloku", "kod": None},
    {"opis": "obuwnicy i pokrewni", "kod": None},
    {"opis": "obuwnik", "kod": None},
    {"opis": "obuwnik miarowy", "kod": None},
    {"opis": "obuwnik ortopedyczny", "kod": None},
    {"opis": "obuwnik przemysłowy", "kod": None},
    {"opis": "oceanolog", "kod": None},
    {"opis": "oczyszczacz kanalizacyjny", "kod": None},
    {"opis": "oficer automatyk okrętowy", "kod": None},
    {"opis": "oficer mechanik", "kod": None},
    {"opis": "oficer pokładowy", "kod": None},
    {"opis": "oficer portu", "kod": None},
    {"opis": "ogrodnicy", "kod": None},
    {"opis": "ogrodnik", "kod": None},
    {"opis": "ogrodnik producent nasion", "kod": None},
    {"opis": "ogrodnik szkółkarz", "kod": None},
    {"opis": "ogrodnik terenów zieleni", "kod": None},
    {"opis": "operator", "kod": None},
    {"opis": "operator  stacji pomp", "kod": None},
    {"opis": "operator cad", "kod": None},
    {"opis": "operator drukarek 3d", "kod": None},
    {"opis": "operator dtp", "kod": None},
    {"opis": "operator dźwięku", "kod": None},
    {"opis": "operator edytorów tekstu", "kod": None},
    {"opis": "operator fotoskładu", "kod": None},
    {"opis": "operator kamery", "kod": None},
    {"opis": "operator koparki", "kod": None},
    {"opis": "operator koparko", "kod": None},
    {"opis": "operator koparko-ładowarki", "kod": None},
    {"opis": "operator kserokopiarek", "kod": None},
    {"opis": "operator myjni", "kod": None},
    {"opis": "operator obrazu", "kod": None},
    {"opis": "operator pergaminiarki", "kod": None},
    {"opis": "operator pociągowy", "kod": None},
    {"opis": "operator reaktora", "kod": None},
    {"opis": "operator skrawarek drewna", "kod": None},
    {"opis": "operator spycharki", "kod": None},
    {"opis": "operator suwnic", "kod": None},
    {"opis": "operator urządzeń walcowni", "kod": None},
    {"opis": "operator urządzeń warzelni", "kod": None},
    {"opis": "operator wirówek", "kod": None},
    {"opis": "operator wtryskarki", "kod": None},
    {"opis": "operator zgrzewarek", "kod": None},
    {"opis": "operator ładowarki", "kod": None},
    {"opis": "operetki", "kod": None},
    {"opis": "opery", "kod": None},
    {"opis": "opiekun dzikich zwierząt", "kod": None},
    {"opis": "opiekun klienta", "kod": None},
    {"opis": "opiekun medyczny", "kod": None},
    {"opis": "opiekunka domowa", "kod": None},
    {"opis": "opiekunka dziecięca", "kod": None},
    {"opis": "opiekunka dziecięca domowa", "kod": None},
    {"opis": "opiekunka w żłobku", "kod": None},
    {"opis": "opiekunka środowiskowa", "kod": None},
    {"opis": "opiekunowie dziecięcy", "kod": None},
    {"opis": "optoelektronik", "kod": None},
    {"opis": "optometrysta", "kod": None},
    {"opis": "optometryści", "kod": None},
    {"opis": "optycy okularowi", "kod": None},
    {"opis": "optyk", "kod": None},
    {"opis": "optyk okularowy", "kod": None},
    {"opis": "optyk-mechanik", "kod": None},
    {"opis": "organista", "kod": None},
    {"opis": "organizator widowni", "kod": None},
    {"opis": "organomistrz", "kod": None},
    {"opis": "orkiestry", "kod": None},
    {"opis": "ortopeda mechanik", "kod": None},
    {"opis": "ortoptystka", "kod": None},
    {"opis": "osteopata", "kod": None},
    {"opis": "ostrzarz", "kod": None},
    {"opis": "oświetlacz filmowy", "kod": None},
    {"opis": "pakowacz ręczny", "kod": None},
    {"opis": "paleontolog", "kod": None},
    {"opis": "palowniczy", "kod": None},
    {"opis": "pamiątkarz", "kod": None},
    {"opis": "parasolnik", "kod": None},
    {"opis": "parkieciarz", "kod": None},
    {"opis": "parkingowy", "kod": None},
    {"opis": "parlamentarzysta", "kod": None},
    {"opis": "parzelniczy drewna", "kod": None},
    {"opis": "patroszacz ryb", "kod": None},
    {"opis": "pedagog", "kod": None},
    {"opis": "pedagog specjalny", "kod": None},
    {"opis": "pedagog szkolny", "kod": None},
    {"opis": "pedikiurzystka", "kod": None},
    {"opis": "perfumiarz", "kod": None},
    {"opis": "perfuzjonista", "kod": None},
    {"opis": "perukarz", "kod": None},
    {"opis": "piaskarz", "kod": None},
    {"opis": "piekarz", "kod": None},
    {"opis": "pielęgniarka", "kod": None},
    {"opis": "pielęgniarka oddziałowa", "kod": None},
    {"opis": "pielęgniarki", "kod": None},
    {"opis": "pilarz", "kod": None},
    {"opis": "pilarz drzew", "kod": None},
    {"opis": "pilarz kamienia", "kod": None},
    {"opis": "pilot balonowy", "kod": None},
    {"opis": "pilot morski", "kod": None},
    {"opis": "pilot pionowzlotu", "kod": None},
    {"opis": "pilot samolotowy zawodowy", "kod": None},
    {"opis": "pilot sterowcowy zawodowy", "kod": None},
    {"opis": "pilot szybowcowy", "kod": None},
    {"opis": "pilot wiatrakowcowy zawodowy", "kod": None},
    {"opis": "pilot wycieczek", "kod": None},
    {"opis": "pilot śmigłowcowy zawodowy", "kod": None},
    {"opis": "piosenkarz", "kod": None},
    {"opis": "pirotechnik", "kod": None},
    {"opis": "pisarz", "kod": None},
    {"opis": "pizzer", "kod": None},
    {"opis": "planista produkcyjny", "kod": None},
    {"opis": "planiści produkcyjni", "kod": None},
    {"opis": "plastyk", "kod": None},
    {"opis": "plecionkarz", "kod": None},
    {"opis": "poborca skarbowy", "kod": None},
    {"opis": "podiatra", "kod": None},
    {"opis": "podkuwacz koni", "kod": None},
    {"opis": "podolog", "kod": None},
    {"opis": "poeta", "kod": None},
    {"opis": "pokojowa", "kod": None},
    {"opis": "polerowacz", "kod": None},
    {"opis": "polerowacz szkła", "kod": None},
    {"opis": "policjanci", "kod": None},
    {"opis": "policjant", "kod": None},
    {"opis": "policjant służby prewencji", "kod": None},
    {"opis": "politolog", "kod": None},
    {"opis": "polityk", "kod": None},
    {"opis": "pomoc apteczna", "kod": None},
    {"opis": "pomoc dentystyczna", "kod": None},
    {"opis": "pomoc domowa", "kod": None},
    {"opis": "pomoc krawiecka", "kod": None},
    {"opis": "pomoc kuchenna", "kod": None},
    {"opis": "pomoc laboratoryjna", "kod": None},
    {"opis": "pomoc nauczyciela", "kod": None},
    {"opis": "pomoce kuchenne", "kod": None},
    {"opis": "pomocnicy biblioteczni", "kod": None},
    {"opis": "pomocniczy personel medyczny", "kod": None},
    {"opis": "pomocniczy robotnik budowlany", "kod": None},
    {"opis": "pomocniczy robotnik drogowy", "kod": None},
    {"opis": "pomocniczy robotnik leśny", "kod": None},
    {"opis": "pomocniczy robotnik mostowy", "kod": None},
    {"opis": "pomocniczy robotnik polowy", "kod": None},
    {"opis": "pomocniczy robotnik przemysłowy", "kod": None},
    {"opis": "pomocniczy robotnik szklarniowy", "kod": None},
    {"opis": "pomocniczy robotnik torowy", "kod": None},
    {"opis": "pomocnik biblioteczny", "kod": None},
    {"opis": "pomocnik ciastkarza", "kod": None},
    {"opis": "pomocnik elektromontera", "kod": None},
    {"opis": "pomocnik lakiernika", "kod": None},
    {"opis": "pomocnik mechanika", "kod": None},
    {"opis": "pomocnik mleczarski", "kod": None},
    {"opis": "pomocnik piekarza", "kod": None},
    {"opis": "portier", "kod": None},
    {"opis": "posadzkarz", "kod": None},
    {"opis": "posterunku policji", "kod": None},
    {"opis": "pozłotnik", "kod": None},
    {"opis": "położna", "kod": None},
    {"opis": "położna oddziałowa", "kod": None},
    {"opis": "położne", "kod": None},
    {"opis": "pośrednicy handlowi", "kod": None},
    {"opis": "pośrednik finansowy", "kod": None},
    {"opis": "pracownicy biur informacji", "kod": None},
    {"opis": "pracownicy biurowi", "kod": None},
    {"opis": "pracownicy działów kadr", "kod": None},
    {"opis": "pracownicy obsługi klienta", "kod": None},
    {"opis": "pracownicy usług ochrony", "kod": None},
    {"opis": "pracownik biura podróży", "kod": None},
    {"opis": "pracownik biura przepustek", "kod": None},
    {"opis": "pracownik biurowy", "kod": None},
    {"opis": "pracownik cmentarza", "kod": None},
    {"opis": "pracownik działu logistyki", "kod": None},
    {"opis": "pracownik kolektury", "kod": None},
    {"opis": "pracownik lombardu", "kod": None},
    {"opis": "pracownik obsługi monitoringu", "kod": None},
    {"opis": "pracownik obsługi sklepu", "kod": None},
    {"opis": "pracownik ochrony roślin", "kod": None},
    {"opis": "pracownik parafialny", "kod": None},
    {"opis": "pracownik parku rozrywki", "kod": None},
    {"opis": "pracownik pomocniczy fryzjera", "kod": None},
    {"opis": "pracownik pomocniczy krawca", "kod": None},
    {"opis": "pracownik pomocniczy mechanika", "kod": None},
    {"opis": "pracownik pomocniczy stolarza", "kod": None},
    {"opis": "pracownik pomocniczy ślusarza", "kod": None},
    {"opis": "pracownik przeprowadzkowy", "kod": None},
    {"opis": "pracownik punktu skupu", "kod": None},
    {"opis": "pracownik rozbioru mięsa", "kod": None},
    {"opis": "pracownik socjalny", "kod": None},
    {"opis": "pracownik solarium", "kod": None},
    {"opis": "pracownik utrzymania czystości", "kod": None},
    {"opis": "pracownik wylęgarni drobiu", "kod": None},
    {"opis": "praczka", "kod": None},
    {"opis": "prasowaczka ręczna", "kod": None},
    {"opis": "prasowy", "kod": None},
    {"opis": "prawnik", "kod": None},
    {"opis": "preparator medyczny", "kod": None},
    {"opis": "prezenter muzyczny", "kod": None},
    {"opis": "prezenter telewizyjny", "kod": None},
    {"opis": "prezes", "kod": None},
    {"opis": "probierz", "kod": None},
    {"opis": "producent filmowy", "kod": None},
    {"opis": "producent muzyczny", "kod": None},
    {"opis": "producent teatralny", "kod": None},
    {"opis": "producent telewizyjny", "kod": None},
    {"opis": "produkcja cukiernicza", "kod": None},
    {"opis": "produkcja piekarsko", "kod": None},
    {"opis": "profilaktyk", "kod": None},
    {"opis": "programista", "kod": None},
    {"opis": "programista aplikacji", "kod": None},
    {"opis": "programista obrabiarek", "kod": None},
    {"opis": "programiści aplikacji", "kod": None},
    {"opis": "projektant", "kod": None},
    {"opis": "projektant grafiki", "kod": None},
    {"opis": "projektant interfejsu użytkownika", "kod": None},
    {"opis": "projektant mody", "kod": None},
    {"opis": "prokurator", "kod": None},
    {"opis": "promocji", "kod": None},
    {"opis": "promotor marki", "kod": None},
    {"opis": "protetyk słuchu", "kod": None},
    {"opis": "protokolant", "kod": None},
    {"opis": "przedstawiciel handlowy", "kod": None},
    {"opis": "przedstawiciel medyczny", "kod": None},
    {"opis": "przemysłowa", "kod": None},
    {"opis": "przetwórca mięsa", "kod": None},
    {"opis": "przetwórca ryb", "kod": None},
    {"opis": "przetwórstwo fermentacyjne", "kod": None},
    {"opis": "przetwórstwo jajczarsko", "kod": None},
    {"opis": "przetwórstwo mięsne", "kod": None},
    {"opis": "przetwórstwo mleczarskie", "kod": None},
    {"opis": "przetwórstwo owocowo", "kod": None},
    {"opis": "przetwórstwo rybne", "kod": None},
    {"opis": "przetwórstwo zbożowe", "kod": None},
    {"opis": "przetwórstwo ziemniaczane", "kod": None},
    {"opis": "przewodnik turystyczny górski", "kod": None},
    {"opis": "przewodnik turystyczny miejski", "kod": None},
    {"opis": "przewodnik turystyczny terenowy", "kod": None},
    {"opis": "przewoźnik osób", "kod": None},
    {"opis": "przygotowywacz włókna", "kod": None},
    {"opis": "przędzarz", "kod": None},
    {"opis": "psycholodzy i pokrewni", "kod": None},
    {"opis": "psycholog", "kod": None},
    {"opis": "psycholog biznesu", "kod": None},
    {"opis": "psycholog kliniczny", "kod": None},
    {"opis": "psycholog organizacji", "kod": None},
    {"opis": "psycholog sportowy", "kod": None},
    {"opis": "psycholog wychowawczy", "kod": None},
    {"opis": "psychoonkolog", "kod": None},
    {"opis": "psychoterapeuta", "kod": None},
    {"opis": "psychotraumatolog", "kod": None},
    {"opis": "pszczelarz", "kod": None},
    {"opis": "public relations", "kod": None},
    {"opis": "płatnerz", "kod": None},
    {"opis": "płetwonurek ratownik", "kod": None},
    {"opis": "radca prawny", "kod": None},
    {"opis": "radiesteta", "kod": None},
    {"opis": "radiowy", "kod": None},
    {"opis": "ratownicy medyczni", "kod": None},
    {"opis": "ratownik górniczy", "kod": None},
    {"opis": "ratownik górski", "kod": None},
    {"opis": "ratownik medyczny", "kod": None},
    {"opis": "ratownik morski", "kod": None},
    {"opis": "ratownik pokładowy", "kod": None},
    {"opis": "ratownik wodny", "kod": None},
    {"opis": "realizator dźwięku", "kod": None},
    {"opis": "realizator filmu wideo", "kod": None},
    {"opis": "realizator rekonstrukcji dźwięku", "kod": None},
    {"opis": "realizator światła", "kod": None},
    {"opis": "recepcjonista", "kod": None},
    {"opis": "recepcjonista hotelowy", "kod": None},
    {"opis": "recepcjoniści", "kod": None},
    {"opis": "recepcjoniści hotelowi", "kod": None},
    {"opis": "redaktor naczelny", "kod": None},
    {"opis": "redaktor programowy", "kod": None},
    {"opis": "redaktor wydawniczy", "kod": None},
    {"opis": "referendarz sądowy", "kod": None},
    {"opis": "refleksolog", "kod": None},
    {"opis": "regionalny kierownik sprzedaży", "kod": None},
    {"opis": "rejestratorka medyczna", "kod": None},
    {"opis": "rektor", "kod": None},
    {"opis": "rekwizytor", "kod": None},
    {"opis": "religioznawca", "kod": None},
    {"opis": "renowator zabytków architektury", "kod": None},
    {"opis": "reporter radiowy", "kod": None},
    {"opis": "retman", "kod": None},
    {"opis": "rewident taboru", "kod": None},
    {"opis": "reżyser dźwięku", "kod": None},
    {"opis": "reżyser filmowy", "kod": None},
    {"opis": "reżyser teatralny", "kod": None},
    {"opis": "reżyser telewizyjny", "kod": None},
    {"opis": "robotnicy budowy dróg", "kod": None},
    {"opis": "robotnicy obróbki kamienia", "kod": None},
    {"opis": "robotnicy poligraficzni", "kod": None},
    {"opis": "robotnik budowlany", "kod": None},
    {"opis": "robotnik gospodarczy", "kod": None},
    {"opis": "robotnik górniczy dołowy", "kod": None},
    {"opis": "robotnik leśny", "kod": None},
    {"opis": "robotnik magazynowy", "kod": None},
    {"opis": "robotnik oczyszczania miasta", "kod": None},
    {"opis": "robotnik placowy", "kod": None},
    {"opis": "robotnik portowy", "kod": None},
    {"opis": "robotnik rozbiórki budowli", "kod": None},
    {"opis": "rodzic zastępczy", "kod": None},
    {"opis": "rolnik", "kod": None},
    {"opis": "rolnik chmielarz", "kod": None},
    {"opis": "rolnik łąkarz", "kod": None},
    {"opis": "rozbieracz", "kod": None},
    {"opis": "rozbieracz-wykrawacz", "kod": None},
    {"opis": "rozlepiacz afiszy", "kod": None},
    {"opis": "rusznikarz", "kod": None},
    {"opis": "rybacy", "kod": None},
    {"opis": "rybacy morscy", "kod": None},
    {"opis": "rybacy śródlądowi", "kod": None},
    {"opis": "rybak śródlądowy", "kod": None},
    {"opis": "rykszarz", "kod": None},
    {"opis": "rymarz", "kod": None},
    {"opis": "rysownik geodezyjny", "kod": None},
    {"opis": "rysownik kartograficzny", "kod": None},
    {"opis": "rysownik litograficzny", "kod": None},
    {"opis": "rytownik", "kod": None},
    {"opis": "rzecznik patentowy", "kod": None},
    {"opis": "rzecznik praw konsumenta", "kod": None},
    {"opis": "rzeczoznawca", "kod": None},
    {"opis": "rzeczoznawca budowlany", "kod": None},
    {"opis": "rzeczoznawca majątkowy", "kod": None},
    {"opis": "rzeczoznawca rolniczy", "kod": None},
    {"opis": "rzeczoznawca samochodowy", "kod": None},
    {"opis": "rzeczoznawcy", "kod": None},
    {"opis": "rzemieślnicy", "kod": None},
    {"opis": "rzeźbiarz szkła", "kod": None},
    {"opis": "rzeźbiarz w drewnie", "kod": None},
    {"opis": "rzeźnik", "kod": None},
    {"opis": "rzeźnik-wędliniarz", "kod": None},
    {"opis": "ręczny polerowacz szkła", "kod": None},
    {"opis": "rękawicznik", "kod": None},
    {"opis": "sadownicy", "kod": None},
    {"opis": "sadownik", "kod": None},
    {"opis": "salowa", "kod": None},
    {"opis": "sanitariusz szpitalny", "kod": None},
    {"opis": "scenarzysta", "kod": None},
    {"opis": "scenograf", "kod": None},
    {"opis": "sekretarka", "kod": None},
    {"opis": "sekretarka medyczna", "kod": None},
    {"opis": "sekretarka notarialna", "kod": None},
    {"opis": "sekretarki", "kod": None},
    {"opis": "sekretarz konsularny", "kod": None},
    {"opis": "sekretarz sądowy", "kod": None},
    {"opis": "sekretarze prawni", "kod": None},
    {"opis": "serowar", "kod": None},
    {"opis": "siostra pck", "kod": None},
    {"opis": "sitarz", "kod": None},
    {"opis": "siły zbrojne", "kod": None},
    {"opis": "skarbnik bankowy", "kod": None},
    {"opis": "skażenia promieniotwórcze", "kod": None},
    {"opis": "skoczek spadochronowy", "kod": None},
    {"opis": "składacz okien", "kod": None},
    {"opis": "socjolog", "kod": None},
    {"opis": "sommelier", "kod": None},
    {"opis": "sortowacz", "kod": None},
    {"opis": "sortowacz-brakarz ceramiki", "kod": None},
    {"opis": "sortowacz-brakarz szkła", "kod": None},
    {"opis": "spawacz", "kod": None},
    {"opis": "spawacze i pokrewni", "kod": None},
    {"opis": "specjalista bezpieczeństwa oprogramowania", "kod": None},
    {"opis": "specjalista chirurgii szczękowo", "kod": None},
    {"opis": "specjalista chorób koni", "kod": None},
    {"opis": "specjalista chorób przeżuwaczy", "kod": None},
    {"opis": "specjalista chorób płuc", "kod": None},
    {"opis": "specjalista chorób ryb", "kod": None},
    {"opis": "specjalista etyki biznesu", "kod": None},
    {"opis": "specjalista kontroli jakości", "kod": None},
    {"opis": "specjalista okulistyki", "kod": None},
    {"opis": "specjalista ortodoncji", "kod": None},
    {"opis": "specjalista pielęgniarstwa ginekologiczno", "kod": None},
    {"opis": "specjalista psychoterapii uzależnień", "kod": None},
    {"opis": "specjalista radiofarmacji", "kod": None},
    {"opis": "specjalista resocjalizacji", "kod": None},
    {"opis": "specjalista rozrodu zwierząt", "kod": None},
    {"opis": "specjalista terapii uzależnień", "kod": None},
    {"opis": "specjalista zarządzania dokumentacją", "kod": None},
    {"opis": "specjalista zarządzania informacją", "kod": None},
    {"opis": "specjalista żywienia człowieka", "kod": None},
    {"opis": "specjaliści", "kod": None},
    {"opis": "spedytor", "kod": None},
    {"opis": "spedytorzy i pokrewni", "kod": None},
    {"opis": "spiker radiowy", "kod": None},
    {"opis": "sportowcy i dżokeje", "kod": None},
    {"opis": "sprzedawca", "kod": None},
    {"opis": "sprzedawca na targowisku", "kod": None},
    {"opis": "sprzedawca na telefon", "kod": None},
    {"opis": "sprzedawcy i pokrewni", "kod": None},
    {"opis": "sprzedawcy sklepowi", "kod": None},
    {"opis": "sprzątaczka domowa", "kod": None},
    {"opis": "sprzęt komputerowy", "kod": None},
    {"opis": "sprzętu", "kod": None},
    {"opis": "statysta", "kod": None},
    {"opis": "statystyk", "kod": None},
    {"opis": "stenograf", "kod": None},
    {"opis": "stenograf-protokolant", "kod": None},
    {"opis": "steward", "kod": None},
    {"opis": "stewardesa", "kod": None},
    {"opis": "stewardesa / steward", "kod": None},
    {"opis": "stewardzi", "kod": None},
    {"opis": "stokażowy", "kod": None},
    {"opis": "stolarz", "kod": None},
    {"opis": "stolarz budowlany", "kod": None},
    {"opis": "stolarz meblowy", "kod": None},
    {"opis": "strażacy", "kod": None},
    {"opis": "strażak", "kod": None},
    {"opis": "strażnik gminny", "kod": None},
    {"opis": "strażnik leśny", "kod": None},
    {"opis": "strażnik ochrony przyrody", "kod": None},
    {"opis": "strażnik rybacki", "kod": None},
    {"opis": "strażnik łowiecki", "kod": None},
    {"opis": "strugacz", "kod": None},
    {"opis": "strugacz drewna", "kod": None},
    {"opis": "strzałowi i pokrewni", "kod": None},
    {"opis": "strzałowy", "kod": None},
    {"opis": "studniarz", "kod": None},
    {"opis": "stylistka", "kod": None},
    {"opis": "sufler", "kod": None},
    {"opis": "supermarketu", "kod": None},
    {"opis": "surdologopeda", "kod": None},
    {"opis": "suszarniowy drewna", "kod": None},
    {"opis": "sygnalista szybowy", "kod": None},
    {"opis": "syndyk", "kod": None},
    {"opis": "synoptyk", "kod": None},
    {"opis": "szaleciarz", "kod": None},
    {"opis": "szatniarz", "kod": None},
    {"opis": "szczotkarz", "kod": None},
    {"opis": "szef kuchni", "kod": None},
    {"opis": "szewc", "kod": None},
    {"opis": "szklarz", "kod": None},
    {"opis": "szklarz budowlany", "kod": None},
    {"opis": "szklarze", "kod": None},
    {"opis": "szkliwierz ceramiki", "kod": None},
    {"opis": "szkutnik", "kod": None},
    {"opis": "szlifierz", "kod": None},
    {"opis": "szlifierz ceramiki", "kod": None},
    {"opis": "szlifierz kamienia", "kod": None},
    {"opis": "szlifierz metali", "kod": None},
    {"opis": "szlifierz-ostrzarz", "kod": None},
    {"opis": "szpachlarz", "kod": None},
    {"opis": "sztauer", "kod": None},
    {"opis": "sztauer-trymer", "kod": None},
    {"opis": "sztukator", "kod": None},
    {"opis": "szwaczka maszynowa", "kod": None},
    {"opis": "szwaczka ręczna", "kod": None},
    {"opis": "szyldziarz", "kod": None},
    {"opis": "szyper", "kod": None},
    {"opis": "sędzia", "kod": None},
    {"opis": "sędzia sportowy", "kod": None},
    {"opis": "sędziowie", "kod": None},
    {"opis": "tajemniczy klient", "kod": None},
    {"opis": "takielarz", "kod": None},
    {"opis": "taksator", "kod": None},
    {"opis": "taksówkarz", "kod": None},
    {"opis": "tanatoprakser", "kod": None},
    {"opis": "tancerz", "kod": None},
    {"opis": "tancerz baletowy", "kod": None},
    {"opis": "tancerze", "kod": None},
    {"opis": "tapeciarz", "kod": None},
    {"opis": "tapicer", "kod": None},
    {"opis": "tapicer meblowy", "kod": None},
    {"opis": "tapicerzy i pokrewni", "kod": None},
    {"opis": "tartacznik", "kod": None},
    {"opis": "tatuażysta", "kod": None},
    {"opis": "technicy elektrycy", "kod": None},
    {"opis": "technicy farmaceutyczni", "kod": None},
    {"opis": "technicy informatycy", "kod": None},
    {"opis": "technicy mechanicy", "kod": None},
    {"opis": "technicy technologii żywności", "kod": None},
    {"opis": "techniczne", "kod": None},
    {"opis": "technik agrobiznesu", "kod": None},
    {"opis": "technik akustyk", "kod": None},
    {"opis": "technik analityk", "kod": None},
    {"opis": "technik aranżacji wnętrz", "kod": None},
    {"opis": "technik architekt", "kod": None},
    {"opis": "technik architektury krajobrazu", "kod": None},
    {"opis": "technik archiwista", "kod": None},
    {"opis": "technik automatyk", "kod": None},
    {"opis": "technik awionik", "kod": None},
    {"opis": "technik budowy dróg", "kod": None},
    {"opis": "technik ceramik", "kod": None},
    {"opis": "technik dentystyczny", "kod": None},
    {"opis": "technik dozymetrysta", "kod": None},
    {"opis": "technik drogownictwa", "kod": None},
    {"opis": "technik dźwięku", "kod": None},
    {"opis": "technik ekonomista", "kod": None},
    {"opis": "technik elektroautomatyk okrętowy", "kod": None},
    {"opis": "technik elektromobilności", "kod": None},
    {"opis": "technik elektronik", "kod": None},
    {"opis": "technik elektroradiolog", "kod": None},
    {"opis": "technik elektryk", "kod": None},
    {"opis": "technik elektryk samochodowy", "kod": None},
    {"opis": "technik energetyk", "kod": None},
    {"opis": "technik farmaceutyczny", "kod": None},
    {"opis": "technik garbarz", "kod": None},
    {"opis": "technik gazownictwa", "kod": None},
    {"opis": "technik geodeta", "kod": None},
    {"opis": "technik geofizyk", "kod": None},
    {"opis": "technik geolog", "kod": None},
    {"opis": "technik handlowiec", "kod": None},
    {"opis": "technik hodowca koni", "kod": None},
    {"opis": "technik hodowca zwierząt", "kod": None},
    {"opis": "technik hutnik", "kod": None},
    {"opis": "technik hydrolog", "kod": None},
    {"opis": "technik informatyk", "kod": None},
    {"opis": "technik kryminalistyki", "kod": None},
    {"opis": "technik leśnik", "kod": None},
    {"opis": "technik logistyk", "kod": None},
    {"opis": "technik masażysta", "kod": None},
    {"opis": "technik mechanik", "kod": None},
    {"opis": "technik mechanik lotniczy", "kod": None},
    {"opis": "technik mechanik okrętowy", "kod": None},
    {"opis": "technik mechanik precyzyjny", "kod": None},
    {"opis": "technik mechatronik", "kod": None},
    {"opis": "technik meteorolog", "kod": None},
    {"opis": "technik metrolog", "kod": None},
    {"opis": "technik nawigator morski", "kod": None},
    {"opis": "technik obuwnik", "kod": None},
    {"opis": "technik odlewnik", "kod": None},
    {"opis": "technik ogrodnik", "kod": None},
    {"opis": "technik optyk", "kod": None},
    {"opis": "technik organizacji reklamy", "kod": None},
    {"opis": "technik ortopeda", "kod": None},
    {"opis": "technik papiernictwa", "kod": None},
    {"opis": "technik poligraf", "kod": None},
    {"opis": "technik pożarnictwa", "kod": None},
    {"opis": "technik procesów drukowania", "kod": None},
    {"opis": "technik programista", "kod": None},
    {"opis": "technik przemysłu mody", "kod": None},
    {"opis": "technik pszczelarz", "kod": None},
    {"opis": "technik rachunkowości", "kod": None},
    {"opis": "technik realizacji dźwięku", "kod": None},
    {"opis": "technik realizacji nagrań", "kod": None},
    {"opis": "technik realizacji nagłośnień", "kod": None},
    {"opis": "technik reklamy", "kod": None},
    {"opis": "technik robotyk", "kod": None},
    {"opis": "technik rolnik", "kod": None},
    {"opis": "technik spawalnictwa", "kod": None},
    {"opis": "technik spedytor", "kod": None},
    {"opis": "technik stylista", "kod": None},
    {"opis": "technik teatralny", "kod": None},
    {"opis": "technik technologii drewna", "kod": None},
    {"opis": "technik technologii odzieży", "kod": None},
    {"opis": "technik technologii szkła", "kod": None},
    {"opis": "technik technologii żywności", "kod": None},
    {"opis": "technik teleinformatyk", "kod": None},
    {"opis": "technik telekomunikacji", "kod": None},
    {"opis": "technik tyfloinformatyk", "kod": None},
    {"opis": "technik utrzymania ruchu", "kod": None},
    {"opis": "technik wiertnik", "kod": None},
    {"opis": "technik włókiennik", "kod": None},
    {"opis": "technolog", "kod": None},
    {"opis": "technologia chemiczna", "kod": None},
    {"opis": "technologia mechaniczna", "kod": None},
    {"opis": "teleankieter", "kod": None},
    {"opis": "telemarketer", "kod": None},
    {"opis": "telewizyjne", "kod": None},
    {"opis": "telewizyjny", "kod": None},
    {"opis": "teolog", "kod": None},
    {"opis": "terapeuta zajęciowy", "kod": None},
    {"opis": "terapeuta środowiskowy", "kod": None},
    {"opis": "termoizoler", "kod": None},
    {"opis": "tkacz", "kod": None},
    {"opis": "tokarz", "kod": None},
    {"opis": "tokarz w drewnie", "kod": None},
    {"opis": "tokarz w metalu", "kod": None},
    {"opis": "toksykolog", "kod": None},
    {"opis": "topiarz fryty", "kod": None},
    {"opis": "topiarz szkła", "kod": None},
    {"opis": "toromistrz", "kod": None},
    {"opis": "towaroznawca", "kod": None},
    {"opis": "tragarz", "kod": None},
    {"opis": "transportowych i pokrewni", "kod": None},
    {"opis": "traser", "kod": None},
    {"opis": "trawiacz poligraficzny", "kod": None},
    {"opis": "trener osobisty", "kod": None},
    {"opis": "trymer", "kod": None},
    {"opis": "trzciniarz", "kod": None},
    {"opis": "twórca ludowy", "kod": None},
    {"opis": "twórcy i artyści", "kod": None},
    {"opis": "tynkarz", "kod": None},
    {"opis": "tynkarze i pokrewni", "kod": None},
    {"opis": "tłoczarz w metalu", "kod": None},
    {"opis": "tłumacz", "kod": None},
    {"opis": "tłumacz przysięgły", "kod": None},
    {"opis": "ubojowy", "kod": None},
    {"opis": "układacz", "kod": None},
    {"opis": "urbanista", "kod": None},
    {"opis": "urzędnik podatkowy", "kod": None},
    {"opis": "ustawiacz", "kod": None},
    {"opis": "wloger", "kod": None},
    {"opis": "wagowy", "kod": None},
    {"opis": "warzywne", "kod": None},
    {"opis": "weterynaryjny kontroler sanitarny", "kod": None},
    {"opis": "wiertacz", "kod": None},
    {"opis": "wiertacz studni", "kod": None},
    {"opis": "wiertacz w drewnie", "kod": None},
    {"opis": "wiertacz w metalu", "kod": None},
    {"opis": "wiertnictwo", "kod": None},
    {"opis": "windykator", "kod": None},
    {"opis": "windykatorzy i pokrewni", "kod": None},
    {"opis": "witrażownik", "kod": None},
    {"opis": "wizażystka", "kod": None},
    {"opis": "wizażystka / stylistka", "kod": None},
    {"opis": "wizytator", "kod": None},
    {"opis": "wokalista", "kod": None},
    {"opis": "wozak", "kod": None},
    {"opis": "wozak zrywkarz", "kod": None},
    {"opis": "woźny", "kod": None},
    {"opis": "wróżbita", "kod": None},
    {"opis": "wulkanizator", "kod": None},
    {"opis": "wybieracz monet", "kod": None},
    {"opis": "wykrawacz", "kod": None},
    {"opis": "wykładowca na kursach", "kod": None},
    {"opis": "wyższy urzędnik państwowy", "kod": None},
    {"opis": "wyższy urzędnik samorządowy", "kod": None},
    {"opis": "wędliniarz", "kod": None},
    {"opis": "wędzarz", "kod": None},
    {"opis": "właściciel małego sklepu", "kod": None},
    {"opis": "właściciel stacji paliw", "kod": None},
    {"opis": "właściciel szkoły jazdy", "kod": None},
    {"opis": "zabawkarz", "kod": None},
    {"opis": "zabiegowy balneologiczny", "kod": None},
    {"opis": "zakonnik", "kod": None},
    {"opis": "zalewacz form", "kod": None},
    {"opis": "zamiatacz", "kod": None},
    {"opis": "zamiatacze i pokrewni", "kod": None},
    {"opis": "zaopatrzeniowcy", "kod": None},
    {"opis": "zaopatrzeniowiec", "kod": None},
    {"opis": "zarządca energią", "kod": None},
    {"opis": "zawiadowca stacji", "kod": None},
    {"opis": "zbrojarz", "kod": None},
    {"opis": "zdobnik ceramiki", "kod": None},
    {"opis": "zdobnik szkła", "kod": None},
    {"opis": "zdun", "kod": None},
    {"opis": "zegarmistrz", "kod": None},
    {"opis": "zgrzewacz", "kod": None},
    {"opis": "zielarz", "kod": None},
    {"opis": "zielarz-fitoterapeuta", "kod": None},
    {"opis": "zmywacz graffiti", "kod": None},
    {"opis": "zmywacz naczyń", "kod": None},
    {"opis": "zmywacz okien", "kod": None},
    {"opis": "zmywacze okien", "kod": None},
    {"opis": "zoofizjoterapeuta", "kod": None},
    {"opis": "zoopsycholog", "kod": None},
    {"opis": "zwrotniczy", "kod": None},
    {"opis": "złotnik", "kod": None},
    {"opis": "złotnik-jubiler", "kod": None},
    {"opis": "ładowacz", "kod": None},
    {"opis": "ładowarki", "kod": None},
    {"opis": "łazienkowa", "kod": None},
    {"opis": "łubiankarz", "kod": None},
    {"opis": "ślusarz", "kod": None},
    {"opis": "ślusarz narzędziowy", "kod": None},
    {"opis": "świecki krzewiciel wiary", "kod": None},
    {"opis": "żaglownik", "kod": None},
    {"opis": "żałobnik", "kod": None},
    {"opis": "żongler", "kod": None},
    {"opis": "alergolog", "kod": None},
    {"opis": "anestezjolog", "kod": None},
    {"opis": "angiolog", "kod": None},
    {"opis": "audiolog", "kod": None},
    {"opis": "balneolog", "kod": None},
    {"opis": "chirurg dziecięcy", "kod": None},
    {"opis": "torakochirurg", "kod": None},
    {"opis": "chirurg naczyniowy", "kod": None},
    {"opis": "chirurg ogólny", "kod": None},
    {"opis": "chirurg onkologiczny", "kod": None},
    {"opis": "chirurg plastyczny", "kod": None},
    {"opis": "chirurg szczękowo-twarzowy", "kod": None},
    {"opis": "ortodonta", "kod": None},
    {"opis": "stomatolog", "kod": None},
    {"opis": "chirurg stomatologiczny", "kod": None},
    {"opis": "dermatolog", "kod": None},
    {"opis": "diabetolog", "kod": None},
    {"opis": "endokrynolog", "kod": None},
    {"opis": "endokrynolog ginekologiczny", "kod": None},
    {"opis": "farmakolog kliniczny", "kod": None},
    {"opis": "gastroenterolog", "kod": None},
    {"opis": "gastroenterolog dziecięcy", "kod": None},
    {"opis": "genetyk kliniczny", "kod": None},
    {"opis": "geriatra", "kod": None},
    {"opis": "ginekolog onkolog", "kod": None},
    {"opis": "hematolog", "kod": None},
    {"opis": "hipertensjolog", "kod": None},
    {"opis": "immunolog kliniczny", "kod": None},
    {"opis": "intensywista", "kod": None},
    {"opis": "internista", "kod": None},
    {"opis": "kardiochirurg", "kod": None},
    {"opis": "kardiolog", "kod": None},
    {"opis": "kardiolog dziecięcy", "kod": None},
    {"opis": "laryngolog", "kod": None},
    {"opis": "laryngolog dziecięcy", "kod": None},
    {"opis": "lekarz chorób zakaźnych", "kod": None},
    {"opis": "lekarz medycyny lotniczej", "kod": None},
    {"opis": "lekarz medycyny morskiej i tropikalnej", "kod": None},
    {"opis": "lekarz medycyny nuklearnej", "kod": None},
    {"opis": "lekarz medycyny paliatywnej", "kod": None},
    {"opis": "lekarz medycyny pracy", "kod": None},
    {"opis": "lekarz medycyny ratunkowej", "kod": None},
    {"opis": "lekarz medycyny sądowej", "kod": None},
    {"opis": "lekarz medycyny transportu", "kod": None},
    {"opis": "lekarz rehabilitacji medycznej", "kod": None},
    {"opis": "lekarz rodzinny", "kod": None},
    {"opis": "mikrobiolog lekarski", "kod": None},
    {"opis": "nefrolog", "kod": None},
    {"opis": "nefrolog dziecięcy", "kod": None},
    {"opis": "neonatolog", "kod": None},
    {"opis": "neurochirurg", "kod": None},
    {"opis": "neurolog", "kod": None},
    {"opis": "neurolog dziecięcy", "kod": None},
    {"opis": "neuropatolog", "kod": None},
    {"opis": "okulista", "kod": None},
    {"opis": "onkolog", "kod": None},
    {"opis": "onkolog kliniczny", "kod": None},
    {"opis": "ortopeda", "kod": None},
    {"opis": "ornitolog", "kod": None},
    {"opis": "operator maszyn", "kod": None},
    {"opis": "opiekun", "kod": None},
    {"opis": "traumatolog", "kod": None},
    {"opis": "patomorfolog", "kod": None},
    {"opis": "pediatra", "kod": None},
    {"opis": "pediatra metaboliczny", "kod": None},
    {"opis": "perinatolog", "kod": None},
    {"opis": "położnik", "kod": None},
    {"opis": "ginekolog", "kod": None},
    {"opis": "psychiatra", "kod": None},
    {"opis": "psychiatra dziecięcy", "kod": None},
    {"opis": "pulmonolog", "kod": None},
    {"opis": "pulmonolog dziecięcy", "kod": None},
    {"opis": "radiolog", "kod": None},
    {"opis": "radioterapeuta onkologiczny", "kod": None},
    {"opis": "reumatolog", "kod": None},
    {"opis": "seksuolog", "kod": None},
    {"opis": "specjalista zdrowia publicznego", "kod": None},
    {"opis": "toksykolog kliniczny", "kod": None},
    {"opis": "transfuzjolog kliniczny", "kod": None},
    {"opis": "transplantolog kliniczny", "kod": None},
    {"opis": "urolog", "kod": None},
    {"opis": "urolog dziecięcy", "kod": None},
    {"opis": "weterynarz", "kod": None},
    {"opis": "taternik", "kod": None},
]
