"""Flora (pole Roślina): zielonyogrodek.pl — byliny, drzewa, krzewy, owoce/warzywa, zioła, … + en.wikipedia.

Wygenerowano skryptem ``scripts/build_plants_bs4.py``. Nie edytuj ręcznie — odtwórz skryptem.
"""

from __future__ import annotations

from typing import Final

PLANTS_NORMS: Final[frozenset[str]] = frozenset(
    {
        "abelia 'edward goucher'abelia",
        "abelia chińska autumn festivalabelia chinensis",
        "abelia mosańska",
        "abelia wielkokwiatowa",
        "acena drobnolistna",
        "adiantum stopowate / niekropień stopowate",
        "afelandra stercząca",
        "afelandra stercząca / afelandra czworokątna",
        "african rice",
        "african sheepbush",
        "african violet",
        "agapant afrykański",
        "agawa",
        "aglaonema zmienna",
        "agrest",
        "akacja srebrzysta",
        "akacja uzbrojona",
        "akant miękki",
        "akebia pięciolistkowa",
        "akebia trójlistkowa",
        "aksamitka",
        "aksamitka rozpierzchła",
        "aksamitka wyniosła",
        "aksamitka wąskolistna",
        "aktinidia",
        "aktinidia ostrolistna 'vitikwi'actinidia arguta 'vitikwi'",
        "aktinidia ostrolistna hokey pokeyactinidia arguta 'hokey pokey'",
        "albicja jedwabista",
        "albuca spiralis 'frizzle sizzle'albuca spiralis",
        "aleppo pine",
        "algerian oak",
        "allamanda przeczyszczająca / allamanda pnąca",
        "almond",
        "aloe vera",
        "aloes drzewiasty",
        "aloes ościsty",
        "aloes zwyczajny / aloes barbadoski",
        "alokazja 'mythic dragonite'alocasia melo mythic dragonite",
        "alokazja / zakleśń",
        "alstremeria indian summer 'tesronto'alstroemeria 'tesronto'",
        "alstremeria river valley 'tessumriver'alstremeria 'river valley'",
        "alstromeria / alstremeria",
        "amaranth",
        "ambrosia tall ambrosia",
        "ambrowiec balsamiczny / ambrowiec amerykański",
        "ambrozja bylicolistna",
        "american cress",
        "american dogwood",
        "american nightshade",
        "american white hellebore",
        "american winterberry",
        "amsonia nadreńska",
        "amsonia nadreńska 'storm cloud'amsonia tabernaemontana storm cloud",
        "amy root",
        "ananas jadalny",
        "angel trumpet",
        "angel's tears",
        "annual sow thistle",
        "anturium",
        "anturium andrego",
        "apache pine",
        "appalachian tea",
        "apple",
        "apricot",
        "aptenia sercolistna",
        "aralia wysoka / aralia japońska",
        "araukaria wyniosła",
        "arbuz zwyczajny / kawon",
        "arcydzięgiel litwor",
        "arcydzięgiel olbrzymi",
        "ardizja karbowana",
        "areka",
        "arfaj",
        "arizona sycamore",
        "aronia czarna",
        "arrowwood",
        "ash leaved maple",
        "ashwagandha / witania ospała",
        "asian rice",
        "aspidistra wyniosła",
        "aster",
        "aster alpejski",
        "aster chiński",
        "aster gawędka",
        "aster krzaczasty",
        "aster nowoangielski",
        "aster nowobelgijski",
        "atlas pistachio",
        "austrian pine",
        "azalia",
        "azalia 'anna'rhododendron",
        "azalia 'venus'rhododendron",
        "azalia indyjska",
        "azalia pontyjska",
        "azalia starstyle® pinkrhododendron",
        "azalia wielkokwiatowa",
        "azolla",
        "ałycza / śliwa wiśniowa",
        "babka lancetowata",
        "baby rose",
        "baja datura",
        "bakopa / sutera",
        "bakłażan / psianka podłużna",
        "bakłażan etiopski",
        "bamboo",
        "banana",
        "bank cress",
        "baobab",
        "baptysja błękitna",
        "barbula klandońska",
        "barbula klandońska 'hint of gold'caryopteris clandonensis 'hint of gold'",
        "barbula klandońska 'white surprise'caryopteris clandonensis 'white surprise'",
        "barwinek pospolity / barwinek mniejszy",
        "bastard pellitory",
        "bay laurel",
        "bazylia pospolita",
        "bażyna czarna",
        "beaked hazelnut",
        "bean",
        "bear corn",
        "bearberry",
        "beech",
        "begonia barszczolistna",
        "begonia bowera",
        "begonia bulwiasta",
        "begonia koralowa",
        "begonia królewska",
        "begonia masona",
        "begonia mieszańcowa 'dragon wing'begonia hybrida 'dragon wing'",
        "begonia stale kwitnąca",
        "begonia zimowa / begonia elatior",
        "belle isle cress",
        "berberys bukszpanolistny",
        "berberys gruczołkowaty",
        "berberys juliany",
        "berberys ottawski",
        "berberys thunberga",
        "berberys thunberga 'anna'berberis thunbergii 'anna'",
        "berberys thunberga 'atropurpurea'berberis thunbergii 'atropurpurea'",
        "berberys thunberga 'aurea'berberis thunbergii 'aurea'",
        "berberys thunberga 'neon gold'berberis thunbergii",
        "berberys thunberga 'orange dream'berberis thunbergii",
        "berberys zwyczajny",
        "bergenia sercolistna",
        "bermuda cress",
        "bermuda grass",
        "beukarnea wygięta / nolina wygięta / noga słonia",
        "bez czarny",
        "bez czarny 'black beauty'sambucus nigra black beauty",
        "bez czarny laced upsambucus nigra laced up",
        "bez hebd",
        "bez koralowy 'lemony lace'sambucus racemosa",
        "biedrzeniec anyż / anyżek",
        "bieluń / datura",
        "bieluń dziędzierzawa",
        "big hellebore",
        "bindweed blue bindweed",
        "bird of paradise",
        "bird's nest",
        "bird's nest plant",
        "bitter nightshade",
        "bittercress",
        "bittersweet",
        "black alder",
        "black ash",
        "black birch",
        "black cap",
        "black cherry",
        "black datura",
        "black eyed susan",
        "black hellebore",
        "black maple",
        "black nightshade",
        "black pine",
        "black raspberry",
        "black weed",
        "blackhaw",
        "blackhaw viburnum",
        "blood ragweed",
        "blue ash",
        "blue atlas cedar",
        "blue bindweed",
        "blue oak",
        "blue of the heavens",
        "bluebell",
        "blueberry",
        "blueberry cornel",
        "blunt leaved milkweed",
        "bluszcz kanaryjski",
        "bluszcz kolchidzki",
        "bluszcz pospolity",
        "bluszczyk kurdybanek",
        "bodziszek",
        "bodziszek błotny",
        "bodziszek czerwony / bodziszek krwisty",
        "bodziszek dalmacki",
        "bodziszek himalajski",
        "bodziszek korzeniasty",
        "bodziszek popielaty",
        "bodziszek wallicha 'bloom me away'geranium wallichianum",
        "bodziszek wallicha 'kelly anne'geranium wallichianum",
        "bodziszek wspaniały",
        "bola verde",
        "bolean birch",
        "borówka amerykańska / borówka wysoka",
        "borówka brusznica",
        "borówka wysoka 'cabernet splash'vaccinium corymbosum 'cabernet splash'",
        "bosnian pine",
        "boston fern or sword fern",
        "bow wood",
        "box",
        "boxelder",
        "boxelder maple",
        "boxwood",
        "bożodrzew gruczołowaty / ajlant gruczołkowaty",
        "bracken's brown beauty magnolia",
        "bratek ogrodowy / fiołek ogrodowy",
        "brier sand brier",
        "brilliant coneflower",
        "bristly dewberry",
        "bristly groundberry",
        "brittlebush",
        "broad leaf bottle tree",
        "broadleaf",
        "brokuł włoski",
        "brown betty",
        "brown daisy",
        "brown eyed susan",
        "brugmansja",
        "brukselka / kapusta brukselska",
        "brunera wielkolistna / brunnera",
        "brzoskwinia zwyczajna",
        "brzoza brodawkowata",
        "brzoza brodawkowata 'golden cloud'betula pendula 'golden cloud'",
        "brzoza brodawkowata 'youngii'betula pendula 'youngii'",
        "brzoza karłowata",
        "brzoza omszona",
        "brzoza papierowa",
        "brzoza pożyteczna",
        "brzoza pożyteczna 'doorenbos'betula utilis 'doorenbos'",
        "buckeye",
        "buckeye ( california buckeye )",
        "budleja davida",
        "budleja davida 'adonis blue'buddleja davidii 'adonis blue'",
        "budleja davida 'butterfly tower'buddleja davidii 'butterfly tower'",
        "budleja davida 'peacock'buddleja davidii 'peacock'",
        "budleja davida 'purple chip'buddleja davidii 'purple chip'",
        "budleja davida 'white profusion'buddleja davidii 'white profusion'",
        "budleja davida berries & creambuddleja davidii",
        "budleja davida butterfly candy® lila sweetheartbuddleja davidii",
        "budleja davida butterfly candy® little purplebuddleja davidii",
        "budleja davida butterfly candy® little rubybuddleja davidii",
        "budleja davida rocketstar indigo 'smnbdbt'buddleja davidii 'rocketstar indigo'",
        "budleja skrętolistna",
        "buffalo weed",
        "bugenwilla",
        "bugle",
        "buk pospolity",
        "buk pospolity 'atropunicea'fagus sylvatica 'atropunicea'",
        "buk pospolity 'purpurea'fagus sylvatica 'purpurea'",
        "buk pospolity midnight featherfagus sylvatica 'midnight feather'",
        "bukszpan wieczniezielony",
        "bulbous cress",
        "bull nettle",
        "bur oak",
        "burak zwyczajny",
        "butelua smukła",
        "butterfly flower",
        "butterfly weed",
        "buwardia",
        "bylica luizjańska",
        "bylica piołun",
        "bylica schmidta",
        "bób",
        "błonczatka",
        "cabinet cherry",
        "california bay",
        "california buckeye",
        "california jimsonweed",
        "california sycamore",
        "california thistle",
        "california walnut",
        "canada holly",
        "canada root",
        "canada thistle",
        "canary island pine",
        "cancer jalap",
        "candia tulip",
        "cane ash",
        "canoe birch",
        "cantedeskia / kalia",
        "carolina azolla",
        "carolina horse nettle",
        "carrot",
        "carrot weed",
        "cart track plant",
        "catalina ironwood",
        "cebula siedmiolatka / czosnek dęty",
        "cebula wielopiętrowa / cebula egipska",
        "cebula zwyczajna",
        "cebulica dwulistna",
        "cebulica miszczenki",
        "cebulica peruwiańska",
        "cebulica syberyjska",
        "cedar",
        "cedr libański",
        "cefalocereus / głowa starca",
        "celozja",
        "ceropegia wooda / lampion chiński",
        "chaber bławatek",
        "chaber wielkogłówkowy",
        "chaber łąkowy",
        "chalk milkwort",
        "chamedora wytworna / palma koralowa",
        "champion oak",
        "charlock",
        "cherry birch",
        "chestnut",
        "chigger flower",
        "chinese pistache",
        "chinese red pine",
        "chinese thorn apple",
        "chinese wolfsbane",
        "chir pine",
        "chittick",
        "chmiel japoński",
        "chmiel zwyczajny",
        "choina kanadyjska",
        "christia obcordata / trójlistna christia",
        "christmas fern",
        "chrobotek reniferowy",
        "chruścina jagodna / drzewo truskawkowe",
        "chrysanthemum",
        "chryzantema / złocień ogrodowy",
        "chrzan pospolity",
        "cibora papirusowa",
        "cibora zmienna",
        "ciecierzyca",
        "ciemiernik biały",
        "ciemiernik cuchnący",
        "ciemiernik czerwonawy",
        "ciemiernik ogrodowy",
        "ciemiernik wschodni",
        "ciemiernik wschodni 'double ellen purple'helleborus orientalis 'double ellen purple'",
        "ciemnotka okrągłolistna",
        "cienistka roberta",
        "cis japoński",
        "cis pospolity 'aurea'taxus baccata 'aurea'",
        "cis pospolity 'fastigiata aurea'taxus baccata 'fastigiata aurea'",
        "cis pospolity 'kazimierz nowak'taxus baccata",
        "cis pośredni",
        "cis pośredni 'baby'taxus ×media",
        "cis pośredni 'hicksii'taxus x media 'hicksii'",
        "cissus australijski",
        "cissus rombolistny",
        "cissus różnobarwny",
        "climbing nightshade",
        "clove",
        "clover",
        "clumpfoot cabbage",
        "coakum",
        "coast live oak",
        "coast polypody",
        "coconut",
        "coffee plant",
        "colic weed",
        "collard",
        "columbine",
        "colwort hare's colwort",
        "comfrey",
        "common alder",
        "common fig",
        "common milkweed",
        "common onion",
        "common plantain",
        "common ragweed",
        "common ragwort",
        "common serviceberry",
        "common tansy",
        "common yarrow",
        "coralberry",
        "cork oak",
        "corn sow thistle",
        "corn speedwell",
        "corn thistle",
        "cornel blueberry cornel",
        "cornelian tree",
        "corokia cotoneaster",
        "cotton plant",
        "coyote willow",
        "creek maple",
        "creeping thistle",
        "creeping yellowcress",
        "crow's nest",
        "crow's toes",
        "crowfoot",
        "ctenanthe",
        "cucumber",
        "cukinia / kabaczek",
        "cursed thistle",
        "cutleaf coneflower",
        "cutleaf maple",
        "cutleaf toothwort",
        "cyanotis somalijski / trzykrotka somalijska",
        "cyklamen bluszczolistny",
        "cyklamen perski / fiołek alpejski",
        "cykoria sałatowa, cykoria czerwona, radicchio",
        "cynia wytworna",
        "cyperus haspan / papirus karłowaty",
        "cyprys wiecznie zielony",
        "cyprysik groszkowy",
        "cyprysik lawsona",
        "cyprysik nutkajski 'pendula'chamaecyparis nootkatensis 'pendula'",
        "cyprysik tępołuskowy",
        "cytryniec",
        "czarnuszka damasceńska",
        "czarny zamiokulkas 'raven'zamioculcas zamiifolia 'raven'",
        "czeremcha późna / czeremcha amerykańska",
        "czeremcha zwyczajna",
        "czereśnia 'regina'prunus avium 'regina'",
        "czereśnia / wiśnia ptasia",
        "czermień błotna",
        "czermiówka",
        "czosnek białawy",
        "czosnek błękitny",
        "czosnek grzebieniasty",
        "czosnek główkowaty",
        "czosnek karatawski",
        "czosnek neapolitański",
        "czosnek niedźwiedzi",
        "czosnek ozdobny",
        "czosnek ozdobny 'globemaster'allium 'globemaster'",
        "czosnek ozdobny 'purple sensation'allium 'purple sensation'",
        "czosnek pospolity",
        "czosnek szuberta",
        "czubatka ubiorkolistna",
        "czyściec wełnisty",
        "cząber ogrodowy",
        "dabecja kantabryjska",
        "daglezja zielona",
        "daktylowiec kanaryjski",
        "daktylowiec niski",
        "dalia ogrodowa",
        "damask violet",
        "dame's gilliflower",
        "dame's rocket",
        "dame's violet",
        "dandelion",
        "dawidia chińska",
        "deadly nightshade",
        "deciduous holly",
        "deodar cedar",
        "dereń biały",
        "dereń biały 'elegantissima'cornus alba 'elegantissima'",
        "dereń biały 'miracle'cornus alba 'miracle'",
        "dereń biały nightfallcornus alba 'verpaalen3'",
        "dereń biały ‘sibirica’cornus alba ‘sibirica’",
        "dereń jadalny",
        "dereń kanadyjski",
        "dereń kousa flower towercornus kousa",
        "dereń kwiecisty",
        "dereń pagodowy",
        "dereń świdwa",
        "desert rose",
        "desert thorn apple",
        "devil's bite",
        "devil's cucumber",
        "devil's darning needle",
        "devil's nose",
        "devil's plague",
        "devil's snare",
        "devil's trumpet",
        "devil's weed",
        "dewberry bristly dewberry",
        "diaskia",
        "dichondra srebrzysta",
        "dierama",
        "difenbachia",
        "dimorfoteka zatokowa / dimorfoteka pomarańczowa",
        "dindle",
        "dipladenia / mandewilla",
        "dischidia okrągłolistna",
        "dizygoteka / szeflera najwytworniejsza",
        "dmuszek jajowaty",
        "dog's tooth violet or dogtooth violet",
        "downy serviceberry",
        "downy thorn apple",
        "dracena deremeńska",
        "dracena obrzeżona",
        "dracena rozgałęziona",
        "dracena sandera / lucky bamboo",
        "dracena wonna",
        "dracena wonna 'lemon lime'dracaena fragrans 'lemon lime'",
        "dragon tree dragons blood tree",
        "dragons blood tree",
        "drakunkulus zwyczajny",
        "driakiew gołębia",
        "driakiew gwiaździsta",
        "drzewo papierowe",
        "duck retten",
        "durian kura kura",
        "durian munjit",
        "durian pulu",
        "duscle",
        "dwarf wild rose",
        "dye leaves",
        "dyer's oak",
        "dynia hokkaido",
        "dynia makaronowa",
        "dynia olbrzymia",
        "dynia piżmowa",
        "dynia zwyczajna",
        "dyptam jesionolistny",
        "dzielżan",
        "dzielżan ogrodowy 'pumilum magnificum'helenium × hybridum 'pumilum magnificum'",
        "dziewanna ogrodowa",
        "dziewanna pospolita",
        "dziewięćsił bezłodygowy",
        "dziurawiec 'rheingold'hypericum x indorum 'rheingold'",
        "dziurawiec kielichowaty",
        "dziurawiec zwyczajny",
        "dziwaczek jalapa",
        "dzwonek brzoskwiniolistny",
        "dzwonek dalmatyński",
        "dzwonek gargański",
        "dzwonek irlandzki",
        "dzwonek karpacki",
        "dzwonek karpacki 'karl foerster'campanula carpatica 'karl foerster'",
        "dzwonek kropkowany",
        "dzwonek pokrzywolistny",
        "dzwonek poszarskiego",
        "dzwonek skupiony",
        "dzwonek szerokolistny",
        "dąb bezszypułkowy",
        "dąb burgundzki",
        "dąb błotny",
        "dąb czerwony",
        "dąb omszony",
        "dąb szypułkowy",
        "dąbrówka feathered friends cordial canaryajuga",
        "dąbrówka feathered friends fancy finchajuga",
        "dąbrówka rozłogowa",
        "dąbrówka rozłogowa 'atropurpurea'ajuga reptans 'atropurpurea'",
        "dąbrówka rozłogowa 'gold chang'ajuga reptans",
        "dębik ośmiopłatkowy",
        "dławisz okrągłolistny",
        "długosz królewski",
        "early wintercress",
        "earth gall",
        "easter orchid",
        "eastern black oak",
        "eastern coneflower",
        "eastern redbud",
        "echinocereus",
        "echinokaktus grusona",
        "echinopsis",
        "echmea wstęgowata",
        "elderberry",
        "elegant lupine",
        "elephant apple",
        "elf maple",
        "endywia",
        "english bull's eye",
        "english oak",
        "eonium drzewiaste 'schwarzkopf'aeonium arboreum",
        "eonium drzewiaste / aeonium",
        "epimedium",
        "epipremnum złociste",
        "estragon / bylica estragon / bylica draganek",
        "eszeweria",
        "eszynantus marmurkowy",
        "eucalyptus",
        "eukaliptus",
        "eukaliptus górski / eukaliptus gunni",
        "european ash",
        "european flax",
        "european holly",
        "european pellitory",
        "european weeping birch",
        "european white birch",
        "european white hellebore",
        "euryops / euryops chrysanthemoides",
        "eustoma wielkokwiatowa",
        "evergreen huckleberry",
        "evergreen winterberry",
        "extinguisher moss",
        "eytelia",
        "facelia błękitna",
        "fair maid of france",
        "fairall's honeysuckle",
        "false alder",
        "false box",
        "false boxwood",
        "false hellebore",
        "false pineapple",
        "fanaberia pospolita",
        "farbownik lazurowy",
        "fargesia lśniąca",
        "fargezja",
        "fargezja 'obelisk'fargesia 'obelisk'",
        "fasola mung / fasola złota",
        "fasola szparagowa / fasola zwyczajna",
        "fasola wielokwiatowa",
        "fasolnik chiński",
        "fatsja japońska",
        "fatsjobluszcz lizjański",
        "felicja gawędkowa",
        "fellenwort",
        "felonwood",
        "felonwort",
        "fennel",
        "fern leaf corydalis",
        "fernleaf yarrow",
        "feverbush",
        "feverfew",
        "field forget me not",
        "field sow thistle",
        "fierce thorn apple",
        "fig",
        "figa / figowiec pospolity",
        "figowiec bengalski / fikus bengalski",
        "figowiec benjamina / fikus benjamina",
        "figowiec czepny / fikus czepny",
        "figowiec deltolistny / fikus deltolistny",
        "figowiec lirolistny / fikus dębolistny",
        "figowiec pnący / fikus pnący",
        "figowiec sprężysty / fikus sprężysty",
        "figowiec tępy / fikus tępy",
        "filirea wąskolistna",
        "filodendron",
        "filodendron birkin",
        "filodendron pnący",
        "fiołek afrykański / sępolia fiołkowa",
        "fiołek motylkowaty",
        "fiołek motylkowy",
        "fiołek rogaty",
        "fiołek wonny",
        "firletka chalcedońska",
        "firletka kwiecista",
        "fitonia",
        "flame bottle tree",
        "flax european flax",
        "flebodium złociste / paproć złocista",
        "floks douglasa / płomyk douglasa",
        "floks drummonda / płomyk drummonda",
        "floks kanadyjski / płomyk kanadyjski",
        "floks szydlasty / płomyk szydlasty",
        "floks wiechowaty 'skubianka'phlox paniculata",
        "floks wiechowaty 'warsaw sunrise'phlox paniculata 'warsaw sunrise'",
        "floks wiechowaty / płomyk wiechowaty",
        "floks śnieżny / płomyk śnieżny",
        "flowering dogwood",
        "fluxroot",
        "forsycja",
        "fotergilla",
        "fotergilla gardena / fotergilla olszolistna",
        "foxglove",
        "foxtail amaranth",
        "frezja",
        "frizea lśniąca",
        "fuksja / ułanka",
        "fuksja magellańska",
        "fumewort yellow fumewort",
        "funkia / hosta",
        "funkia / hosta 'diamond lake'hosta diamond lake",
        "funkia / hosta 'empress wu'hosta",
        "funkia / hosta 'gypsy lemon'hosta 'gypsy lemon'",
        "funkia / hosta 'hudson bay'hosta shadowland® hudson bay",
        "funkia fortune'a / hosta fortunea",
        "funkia japońska / hosta japońska",
        "funkia siebolda / hosta siebolda",
        "fylostachys",
        "gailardia oścista",
        "gajowiec żółty",
        "galaxy magnolia",
        "gallberry",
        "galtonia biaława / hiacynt letni",
        "garden nightshade",
        "gardenia jaśminowata",
        "garget",
        "garlic golden garlic",
        "garlic mustard",
        "garlic root",
        "gaulteria rozesłana",
        "gaura lindheimera",
        "gazania",
        "gerbera",
        "gerbera jamesona / gerbera doniczkowa",
        "gerbera miniaturowa",
        "germander speedwell",
        "gewa (bangladesh)",
        "giant onion",
        "giant ragweed",
        "ginura pomarańczowa",
        "gipsówka rozesłana",
        "gipsówka wiechowata",
        "gipsówka wytworna",
        "glediczja trójcierniowa",
        "glediczja trójcierniowa 'sunburst'gleditsia triacanthos 'sunburst'",
        "glicynia chińska",
        "glicynia kwiecista",
        "glistnik jaskółcze ziele",
        "gloriosa daisy",
        "glorioza rotszylda",
        "glorioza wspaniała",
        "godecja wielkokwiatowa / klarkia wdzięczna",
        "gojnik",
        "golden buttons",
        "golden chain",
        "golden corydalis",
        "golden garlic",
        "golden jerusalem",
        "goldenglow",
        "golteria rozesłana",
        "gomfrena",
        "goodding willow",
        "goose tongue",
        "gorczyca biała",
        "gorczyca polna",
        "gorczycznik wiosenny",
        "gordaldo",
        "goryczka chińska",
        "goździk",
        "goździk 'paint the town magenta'dianthus hybrid paint the town magenta",
        "goździk alpejski",
        "goździk brodaty",
        "goździk chiński",
        "goździk kartuzek",
        "goździk kropkowany",
        "goździk ogrodowy",
        "goździk pierzasty / goździk postrzępiony",
        "goździk siny",
        "grab japoński",
        "grab pospolity / grab zwyczajny",
        "grapefruit",
        "grapevine",
        "graptopetalum paragwajskie",
        "grass",
        "gray alder",
        "gray birch",
        "great ragweed",
        "green ash",
        "green berry nightshade",
        "green headed coneflower",
        "green honeysuckle",
        "green thistle",
        "groch zwyczajny 'sześciotygodniowy'pisum sativum sześciotygodniowy",
        "groszek / groch zwyczajny",
        "groszek pachnący",
        "groszek wiosenny",
        "groundberry",
        "grubosz / drzewko szczęścia",
        "grubosz radicans",
        "grujecznik japoński",
        "grusza pospolita",
        "grzybienie",
        "grążel żółty",
        "gunnera olbrzymia",
        "gutweed",
        "guzikowiec zachodni",
        "guzmania",
        "gwiazdnica pospolita",
        "gęsiówka kaukaska",
        "gęsiówka macedońska / gęsiówka wczesna",
        "głodek mrzygłód",
        "głogownik",
        "głogownik frasera",
        "głożyna pospolita / jujuba / chińskie daktyle",
        "głóg dwuszyjkowy",
        "głóg dwuszyjkowy 'paul's scarlet'crataegus media 'paul's scarlet'",
        "głóg jednoszyjkowy",
        "głóg szkarłatny",
        "hairy bittercress",
        "hairy thorn apple",
        "hakonechloa smukła / trawa bambusowa",
        "haldi",
        "hard thistle",
        "hare's colwort",
        "hare's thistle",
        "harlequin rock harlequin",
        "haworsja",
        "hay fever weed",
        "healing blade",
        "healing wolfsbane",
        "heath leaved honeysuckle",
        "hebe",
        "hedge plant",
        "heliotrop peruwiański",
        "hemlock",
        "hemp",
        "hemp dogbane",
        "hen plant",
        "henbit deadnettle",
        "henry's pine",
        "herb barbara",
        "hiacynt",
        "hiacynt wodny",
        "hiacyntowiec / endymion",
        "hibiskus bylinowy summerific™hibiscus moscheutos",
        "hindu datura",
        "hispid swamp blackberry",
        "hoary ragwort",
        "hogweed",
        "hoja",
        "hoja różowa",
        "holly leaved honeysuckle",
        "honesty",
        "honey flower",
        "honey mesquite",
        "horse cane",
        "horse nettle",
        "horseradish",
        "horsetail milkweed",
        "horseweed",
        "hortensja bukietowa",
        "hortensja bukietowa 'bobo'hydrangea paniculata",
        "hortensja bukietowa 'bombshell'hydrangea paniculata 'bombshell'",
        "hortensja bukietowa 'little quick fire'hydrangea paniculata",
        "hortensja bukietowa 'polar bear'hydrangea paniculata 'polar bear'",
        "hortensja bukietowa confettihydrangea paniculata 'confetti'",
        "hortensja bukietowa coussinehydrangea paniculata",
        "hortensja bukietowa diamant rougehydrangea paniculata 'diamant rouge'",
        "hortensja bukietowa fraise melbahydrangea paniculata fraise melba",
        "hortensja bukietowa graffitihydrangea paniculata 'graffiti'",
        "hortensja bukietowa groundbreaker blushhydrangea paniculata",
        "hortensja bukietowa little frescohydrangea paniculata 'little fresco'",
        "hortensja bukietowa little limehydrangea paniculata 'little lime'",
        "hortensja bukietowa little lime® punchhydrangea paniculata",
        "hortensja bukietowa little spookyhydrangea paniculata",
        "hortensja bukietowa little spookyhydrangea paniculata 'little spooky'",
        "hortensja bukietowa living little rosyhydrangea paniculata",
        "hortensja bukietowa mojitohydrangea paniculata 'mojito'",
        "hortensja bukietowa petite cherryhydrangea paniculata 'petite cherry'",
        "hortensja bukietowa petite lanternhydrangea paniculata",
        "hortensja bukietowa petite starhydrangea paniculata 'petite star'",
        "hortensja bukietowa pinky winkyhydrangea paniculata",
        "hortensja bukietowa skyfallhydrangea paniculata skyfall",
        "hortensja drzewiasta 'incrediball'hydrangea arborescens",
        "hortensja drzewiasta strong annabellehydrangea arborescens strong annabelle",
        "hortensja dębolistna",
        "hortensja dębolistna first editions® jetstream™hydrangea quercifolia",
        "hortensja krzewiasta",
        "hortensja krzewiasta 'annabelle'hydrangea arborescens 'annabelle'",
        "hortensja let's dance sky view®hydrangea macrophylla × serrata let's dance sky view®",
        "hortensja ogrodowa",
        "hortensja ogrodowa diva fiore",
        "hortensja ogrodowa pinky binderhydrangea macrophylla",
        "hortensja piłkowana",
        "hortensja pnąca 'silver lining'hydrangea petiolaris 'silver lining'",
        "hortensja runaway bridehydrangea hybrid",
        "hound's berry",
        "houseleek",
        "howenia słodka / drzewo rodzynkowe",
        "huangshan pine",
        "hurma wschodnia / kaki / persymona",
        "hydrangea",
        "hyzop lekarski",
        "ifejon",
        "ifejon 'alberto castillo'ifejon 'alberto castillo'",
        "iksja",
        "iksora szkarłatna",
        "indian apple",
        "indian arrowwood",
        "indian hemp",
        "indian paintbrush",
        "indian poke",
        "indian posy",
        "indian thorn apple",
        "indygowiec zwyczajny",
        "inkarwilla delavaya",
        "inkberry",
        "inkberry holly",
        "irga",
        "irga pozioma",
        "irga szwedzka 'coral beauty'cotoneaster × suecicus 'coral beauty'",
        "ironwood",
        "island oak",
        "isle of man cabbage",
        "itchweed",
        "itea wirginijska",
        "ivy",
        "jabłoń",
        "jabłoń 'royalty'malus x purpurea ‘royalty’",
        "jabłoń domowa",
        "jabłoń domowa 'kosztela'malus domestica 'kosztela'",
        "jabłoń domowa 'ligol'malus domestica 'ligol'",
        "jabłoń domowa 'lobo'malus domestica 'lobo'",
        "jabłoń domowa 'szampion'malus domestica 'szampion'",
        "jabłoń ozdobna",
        "jabłoń royal raindropsmalus",
        "jack by the hedge",
        "jack in the bush",
        "jagoda goji / kolcowój pospolity",
        "jane magnolia",
        "janowiec barwierski",
        "japanese flowering dogwood",
        "japanese red pine",
        "jarmuż",
        "jarzmianka większa",
        "jarząb brekinia",
        "jarząb koehnego",
        "jarząb mączny",
        "jarząb pospolity / jarzębina",
        "jarząb szwedzki",
        "jaskier",
        "jaskier azjatycki",
        "jaskier bulwkowy",
        "jaskier ostry",
        "jaskier polny / jaskier odłogowy",
        "jasmine",
        "jasnota plamista",
        "jałowiec chiński",
        "jałowiec chiński 'stricta'juniperus chinensis 'stricta'",
        "jałowiec nadbrzeżny 'sunflower' pbrjuniperus conferta",
        "jałowiec pospolity",
        "jałowiec pospolity 'repanda'juniperus communis 'repanda'",
        "jałowiec pośredni / jałowiec pfitzera",
        "jałowiec płożący",
        "jałowiec sabiński",
        "jałowiec skalny",
        "jałowiec wirginijski",
        "jałowiec łuskowaty",
        "jałowiec łuskowy 'blue carpet'juniperus squamata 'blue carpet'",
        "jaśmin lekarski",
        "jaśmin nagokwiatowy",
        "jaśmin wielokwiatowy",
        "jaśminowiec drobnolistny",
        "jaśminowiec wonny",
        "jaśminowiec wonny 'variegatus'philadelphus coronarius 'variegatus'",
        "jesion mannowy",
        "jesion wyniosły",
        "jewel orchid",
        "jeżotka rozpierzchła",
        "jeżyna 'purple opal'rubus fruticosus 'purple opal'",
        "jeżyna bezkolcowa",
        "jeżówka 'dark pink pearl'echinacea",
        "jeżówka 'sensation wild romance'echinacea",
        "jeżówka purpurowa",
        "jeżówka purpurowa 'lemon drop'echinacea purpurea",
        "jeżówka sunseekers sweet fuchsiaechinacea",
        "jodła balsamiczna",
        "jodła balsamiczna 'nana'abies balsamea 'nana'",
        "jodła biała / jodła pospolita",
        "jodła frasera",
        "jodła grecka",
        "jodła japońska",
        "jodła kalifornijska",
        "jodła kalifornijska 'compacta'abies concolor 'compacta'",
        "jodła kaukaska",
        "jodła koreańska",
        "jodła szlachetna",
        "jointed rush",
        "judas tree",
        "judaszowiec kanadyjski 'carolina sweetheart'cercis canadensis",
        "judaszowiec kanadyjski / drzewo judaszowe",
        "judaszowiec kanadyjski eternal flamecercis canadensis",
        "judaszowiec kanadyjski golden fallscercis canadensis 'golden falls'",
        "judaszowiec południowy",
        "jugflower",
        "juka gwatemalska",
        "juka ogrodowa / juka karolińska",
        "juneberry",
        "juniper",
        "języczka pomarańczowa",
        "języczka przewalskiego",
        "języcznik zwyczajny",
        'kaktus "małpi ogon" / kleistokaktus zimowy colademonis',
        "kaktus mamilaria",
        "kaladium 'lemon blush'caladium lemon blush",
        "kaladium dwubarwne",
        "kalafior",
        "kalaminta mniejsza",
        "kalamondyna / kalamondinx citrofortunella mitis",
        "kalanchoe beharensis",
        "kalanchoe blossfelda",
        "kalanchoe daigremonta",
        "kalanchoe wiechowate",
        "kalarepa",
        "kalatea / ostrzeszyn",
        "kalatea falistolistna",
        "kalatea makoyana",
        "kalibrachoa",
        "kalibrachoa million bells",
        "kalina amerykańska",
        "kalina angielska",
        "kalina bodnantska",
        "kalina burkwooda",
        "kalina dawida",
        "kalina hordowina",
        "kalina japońska",
        "kalina koralowa",
        "kalina koralowa 'roseum'viburnum opulus 'roseum'",
        "kalina koralowa 'sterile'viburnum opulus 'sterile'",
        "kalina koreańska",
        "kalina praska",
        "kalina sargenta",
        "kalina wonna",
        "kalmia szerokolistna",
        "kalmia wąskolistna",
        "kalocefalus browna",
        "kalopanaks siedmioklapowy",
        "kamasja",
        "kamelia japońska",
        "kapusta chińska / pak choi",
        "kapusta ozdobna",
        "kapusta pekińska",
        "kapusta sitowata / musztardowiec",
        "kapusta warzywna głowiasta",
        "kapusta właściwa / rzepa",
        "karagana syberyjska",
        "karczoch zwyczajny",
        "karmnik ościsty",
        "kasjopeja widłakowata",
        "kasztan jadalny",
        "kasztan jadalny 'aureomarginata'castanea sativa 'aureomarginata'",
        "kasztanowiec australijski",
        "kasztanowiec czerwony",
        "kasztanowiec drobnokwiatowy",
        "kasztanowiec krwisty",
        "kasztanowiec zwyczajny",
        "katleja",
        "kawa arabska",
        "kay parris magnolia",
        "keek",
        "ketmia bylinowa / hibiskus bagienny",
        "ketmia syryjska 'lavender chiffon'hibiscus syriacus lavender chiffon",
        "ketmia syryjska 'pink chiffon'hibiscus syriacus pink chiffon",
        "ketmia syryjska 'white chiffon'hibiscus syriacus white chiffon",
        "ketmia syryjska / hibiskus ogrodowy",
        "ketmia syryjska / hibiskus ogrodowy 'purple pillar'hibiscus syriacus purple pillar",
        "ketmia syryjska flower tower rubyhibiscus syriacus",
        "khasi pine",
        "kielisznik bluszczowaty",
        "kimberly queen fern",
        "king fern",
        "kinghead",
        "kinnikinnik",
        "kirengeszoma dłoniasta",
        "kittentail",
        "kiwano / ogórek kiwano",
        "kiwicha",
        "kiścień wawrzynowaty 'rainbow'leucothoe fontanesiana rainbow",
        "kiścień wawrzynowy",
        "klarkia / godecja / dzierotka",
        "kleome ciernista",
        "kliwia cynobrowa",
        "klon czerwony",
        "klon japoński",
        "klon jawor",
        "klon jawor 'brilliantissimum'acer pseudoplatanus 'brillantissimum'",
        "klon jesionolistny",
        "klon jesionolistny 'flamingo'acer negundo 'flamingo'",
        "klon palmowy",
        "klon palmowy 'dissectum'acer palmatum 'dissectum'",
        "klon pospolity 'fassen's black'acer platanoides 'fassen's black'",
        "klon pospolity 'warmia'acer platanoides 'warmia'",
        "klon srebrzysty",
        "klon strzępiastokory",
        "klon zielonokory",
        "klon zwyczajny 'drummondii'acer platanoides drummondii",
        "klon zwyczajny / klon pospolity",
        "klon ściętolistny 'volcano'acer truncatum 'volcano'",
        "kluzja / okrętnica",
        "kmin rzymski",
        "kminek zwyczajny / kminek lekarski",
        "knieć błotna / kaczeniec błotny",
        "knotweed (japanese)",
        "kobea pnąca",
        "kocanka piaskowa",
        "kocanka włochata",
        "kocanka włoska",
        "kocanki ogrodowe",
        "kocimiętka 'blue planet'nepeta hybrida 'blue planet'",
        "kocimiętka 'cats pajamas'nepeta",
        "kocimiętka faassena",
        "kocimiętka neptune 'bokratune'nepeta neptune 'bokratune'",
        "kokornak wielkolistny",
        "kokorycz paprociolistna",
        "kokorycz pełna",
        "kokorycz pogięta",
        "kokoryczka wielkokwiatowa",
        "kolcosił drzewiasty",
        "kolendra siewna",
        "komelina pospolita",
        "komonica zwyczajna",
        "komosa biała",
        "koniczyna biała",
        "koniczyna czerwona / koniczyna łąkowa",
        "konopie siewne / konopie włókniste",
        "konwalia majowa",
        "konwalnik",
        "koper ogrodowy",
        "koper włoski / fenkuł",
        "kopytnik pospolity",
        "kordylina",
        "kordylina australijska 'purpurea'cordyline australis 'purpurea'",
        "korean rock fern",
        "kosaciec / irys",
        "kosaciec bródkowy / irys bródkowy",
        "kosaciec niski / irys niski",
        "kosaciec syberyjski / irys syberyjski",
        "kosaciec żyłkowany / irys żyłkowany",
        "kosaciec żółty / irys żółty",
        "kosmatka olbrzymia",
        "kosmatka śnieżna",
        "kosmos czekoladowy",
        "kosmos podwójnie pierzasty",
        "kostrzewa 'miedzianobrody'festuca 'miedzianobrody'",
        "kostrzewa czerwona",
        "kostrzewa gautiera",
        "kostrzewa miotlasta / kostrzewa gautiera",
        "kostrzewa nitkowata",
        "kostrzewa popielata / kostrzewa sina",
        "kostrzewa pstra",
        "kousa",
        "kozieradka pospolita",
        "kozłek lekarski",
        "krasnodrzew pospolity / koka",
        "kraspedia kulista",
        "krokosmia ogrodowa / cynobrówka ogrodowa",
        "krokosz barwierski",
        "krokus wiosenny",
        "krokus złocisty",
        "kroton / trójskrzyn pstry",
        "kruszyna pospolita",
        "krwawnica pospolita",
        "krwawnik pospolity",
        "krwawnik wiązówkowaty",
        "krwiściąg lekarski",
        "krynka / ponętlin powela",
        "kryptomeria japońska",
        "krzewuszka cudowna",
        "krzewuszka cudowna 'magical rainbow'weigela florida 'magal rainbow'",
        "krzewuszka cudowna bubbly wineweigela florida bubbly wine",
        "krzewuszka cudowna wine & spirits",
        "kudrania / drzewo malinowe",
        "kudzu",
        "kufea ognista / lepnota",
        "kuflik / kalistemon",
        "kuflik cytrynowy",
        "kuklik",
        "kuklik 'bohema pink'geum 'bohema pink'",
        "kuklik trójkwiatowy",
        "kukurydza cukrowa",
        "kukurydza zwyczajna",
        "kukułka fuchsa",
        "kumarahou",
        "kąkol polny",
        "kłokoczka południowa",
        "kłosowiec pomarszczony",
        "lace aloe",
        "lace fern",
        "laceflower",
        "lady's mantle",
        "lady's smock",
        "lagerstremia indyjska",
        "lak pospolity / lak pachnący",
        "lamb's cress",
        "lamb's foot",
        "land cress",
        "lantana pospolita",
        "lasecznica trzcinowata",
        "latanier palm",
        "laurel magnolia",
        "laurencja",
        "laurowiśnia wschodnia",
        "laurowiśnia wschodnia 'miniredia'prunus laurocerasus 'miniredia'",
        "laurowiśnia wschodnia sofiaprunus laurocerasus",
        "lavender",
        "lawenda 'meerlo'lavandula × heterophylla 'meerlo'",
        "lawenda francuska",
        "lawenda pośrednia",
        "lawenda wąskolistna",
        "leatherleaf viburnum",
        "ledeburia kępiasta / cebulica srebrzysta",
        "leek",
        "leichhardt's datura",
        "lejcesteria piękna little lanternsleycesteria formosa",
        "lemon",
        "len",
        "leopard lily",
        "lepismium bolivianum",
        "lepnica nadmorska",
        "lesser sunflower",
        "leszczyna drzewiasta",
        "leszczyna pospolita",
        "leszczynowiec skąpokwiatowy",
        "lettuce",
        "lewizja liścieniowa",
        "lewkonia długopłatkowa (maciejka)matthiola longipetala",
        "lewkonia letnia",
        "liatra kłosowa",
        "ligustr jajolistny / ligustr jajowatolistny",
        "ligustr pospolity",
        "lilac summer lilac",
        "lilak drobnolistny",
        "lilak meyera",
        "lilak omszony",
        "lilak pospolity / bez lilak",
        "lilak rozpierzchły",
        "lilia",
        "lilia amazońska / eucharis",
        "lilia biała",
        "lilia grzywiasta / warkocznica / eukomis",
        "lilia himalajska / kardiokrinum olbrzymie",
        "lilia tygrysia",
        "lilia złotogłów",
        "liliowiec 'american revolution'hemerocallis 'american revolution'",
        "liliowiec 'diva's choice'hemerocallis 'diva's choice'",
        "liliowiec 'fooled me'hemerocallis 'fooled me'",
        "liliowiec 'pardon me'hemerocallis 'pardon me'",
        "liliowiec 'x factor'hemerocallis 'x factor'",
        "liliowiec creamy tongueshemerocallis",
        "liliowiec ogrodowy",
        "liliowiec rdzawy",
        "liliowiec żółty",
        "lily leek",
        "lily of the nile",
        "lipa drobnolistna",
        "lipa henry'ego",
        "lipa krymska",
        "lipa srebrzysta",
        "lipa szerokolistna",
        "liriope szafirkowata",
        "little gem magnolia",
        "little sunflower",
        "liwistona okrągłolistna",
        "lnica marokańska",
        "lnica pospolita",
        "lobelia czerwona",
        "lobelia przylądkowa",
        "loblolly pine",
        "lone fleabane",
        "long spined thorn apple",
        "loropetalum chińskie",
        "love lies bleeding",
        "love vine",
        "low rose",
        "lubczyk ogrodowy",
        "lucerna siewna",
        "luchu pine",
        "ludisia discolor",
        "lupin",
        "lwia paszcza / wyżlin większy",
        "macierzanka piaskowa",
        "macierzanka wczesna",
        "macierzanka wczesna 'coccineus'thymus praecox",
        "macierzanka wczesna 'pygmaeus'thymus praecox 'pygmaeus'",
        "macierzanka zwyczajna",
        "macodes petola",
        "maczek kalifornijski",
        "magnolia 'genie'magnolia 'genie'",
        "magnolia drzewiasta",
        "magnolia gwiaździsta",
        "magnolia japońska",
        "magnolia loebnera",
        "magnolia soulange'a / magnolia pośrednia",
        "magnolia wielkokwiatowa / magnolia zimozielona",
        "mahogany birch",
        "mahonia pospolita",
        "maize",
        "majeranek ogrodowy / lebiodka majeranek",
        "majówka groniasta",
        "mak nagołodygowy / mak syberyjski",
        "mak polny",
        "malina właściwa",
        "malwa różowa",
        "mango",
        "manitoba maple",
        "manna mielec",
        "many flowered honeysuckle",
        "maple ash",
        "maranta leuconeura",
        "marchew zwyczajna",
        "maritime pine",
        "marsh ragwort",
        "masson's pine",
        "meadow cabbage",
        "meadow holly",
        "medinilla wspaniała",
        "mekonops bukwicolistny",
        "melisa lekarska",
        "melon",
        "merkus pine",
        "mesquite",
        "metasekwoja chińska",
        "metasekwoja chińska 'marta'metasequoia glyptostroboides 'marta'",
        "mexican pistache",
        "michigan holly",
        "miechunka peruwiańska",
        "miechunka pomidorowa",
        "miechunka rozdęta",
        "mieczyk",
        "mieczyk nanus / mieczyk karłowy",
        "mieczyk pospolity",
        "miesiącznica roczna",
        "miesięcznik dahurski",
        "mietelnik żakula",
        "mietlica rozłogowa / bambus zwisający",
        "migdałek trójklapowy",
        "mikołajek alpejski",
        "mikołajek jukkolistny",
        "mikołajek nadmorski",
        "mikołajek olbrzymi",
        "mikołajek płaskolistny",
        "mikrobiota syberyjska",
        "milfoil",
        "milin amerykański",
        "milk thistle",
        "milky tassel",
        "mimoza wstydliwa / czułek wstydliwy",
        "miodunka",
        "mirbeck's oak",
        "mirt zwyczajny",
        "miskant chiński",
        "miskant chiński 'boucle'miscanthus sinensis 'boucle'",
        "miskant chiński 'polonus' pbrmiscanthus sinensis",
        "miskant chiński 'silver charm' pbrmiscanthus sinensis",
        "miskant chiński 'zebrinus'miscanthus sinensis 'zebrinus'",
        "miskant chiński ‘lady in red’ pbrmiscanthus sinensis 'lady in red'",
        "miskant cukrowy",
        "miskant małokłosowy",
        "miskant olbrzymi",
        "mizuna / kapusta japońska",
        "mięta jelenia",
        "mięta meksykańska",
        "mięta pieprzowa",
        "mięta wodna / mięta nadwodna",
        "mięta zielona / mięta marokańska",
        "miłek wiosenny",
        "miłka okazała",
        "miłka zakrzywiona",
        "miłorząb dwuklapowy gold flame 'desginb2'ginkgo biloba 'gold flame'",
        "miłorząb japoński / miłorząb dwuklapowy",
        "mlecz polny",
        "mniszek lekarski",
        "modrak morski",
        "modrzew europejski",
        "modrzew japoński",
        "modrzewnica zwyczajna / pospolita",
        "monstera dziurawa",
        "monstera variegata",
        "moonflower",
        "moonglow magnolia",
        "moose maple",
        "moosewood",
        "morela zwyczajna",
        "morelle verte",
        "morwa biała",
        "morwa czarnamorus nigra",
        "mosquito fern",
        "mosquito plant",
        "mossycup white oak",
        "mother of the evening",
        "mount connor wattle",
        "mountain devil",
        "mountain mahogany",
        "mountain pine",
        "mozga trzcinowata",
        "muchołówka amerykańska",
        "mulberry",
        "mulenbekia gęsta",
        "multiflora rose",
        "mydlnica bazyliowata",
        "mydlnica lekarska",
        "mącznica lekarska",
        "męczennica błękitna",
        "męczennica cielista",
        "nachyłek barwierski",
        "nachyłek okółkowy",
        "nachyłek wielkokwiatowy",
        "nagietek lekarski",
        "naparstnica purpurowa",
        "narcyz",
        "narcyz 'tête à tête'narcissus 'tete a tete'",
        "nasturcja większa",
        "native fuchsia",
        "nawłoć kanadyjska",
        "nawłoć pospolita",
        "necklace fern",
        "neem",
        "nefrolepis wyniosły / nefrolepis wysoki",
        "nemezja powabna",
        "nemofila plamista",
        "nerecznica samcza",
        "nertera płożąca",
        "new zealand flax",
        "niecierpek",
        "niecierpek gruczołowaty",
        "niecierpek nowogwinejski",
        "niecierpek walleriana",
        "niedośpian",
        "niekropień właściwy / adiantum właściwe",
        "niepokalanek pospolity",
        "nieszpułka zwyczajna",
        "niezapominajka alpejska",
        "niezapominajka błotna",
        "niezapominajka leśna",
        "night blooming cactus",
        "night scented gilliflower",
        "nikandra miechunkowa",
        "nodding onion",
        "nodding thistle",
        "nodding wakerobin",
        "northern moonwort",
        "northern red oak",
        "nosebleed",
        "oak leaved thorn apple",
        "obedient plant",
        "obiedka szerokolistna",
        "obrazek włoski",
        "obuwik",
        "obwojnik grecki",
        "oczar omszony",
        "oczar pośredni",
        "oczar wirginijski",
        "odętka wirginijska",
        "ognik szkarłatny",
        "ognik szkarłatny 'orange glow'pyracantha coccinea 'orange glow'",
        "ognik szkarłatny 'orange star' pbrpyracantha coccinea",
        "ognik szkarłatny 'red column'pyracantha coccinea 'red column'",
        "ogórecznik lekarski",
        "ogórek siewny",
        "olcha / olsza",
        "oleander pospolity",
        "olive",
        "oliwka europejska",
        "oliwnik baldaszkowy",
        "oliwnik wąskolistny",
        "olsza czarna",
        "oman wielki",
        "omieg wschodni",
        "onychium japońskie",
        "opuncja",
        "opuncja figowa",
        "orange",
        "orange coneflower",
        "orange milkweed",
        "orange root",
        "orange swallow wort",
        "oregano / lebiodka pospolita",
        "orlica pospolita 'kuhn'pteridium aquilinium kuhn",
        "orliczka kreteńska",
        "orlik alpejski",
        "orlik błękitny",
        "orlik ogrodowy",
        "orlik pełny",
        "orlik pospolity",
        "orlik wachlarzowaty",
        "orzech włoski",
        "orzech włoski 'jacek lubelski'juglans regia 'jacek lubelski'",
        "osage",
        "osage orange",
        "osier",
        "osteospermum / stokrotka afrykańska",
        "ostnica cieniutka",
        "ostrogowiec czerwony",
        "ostrokrzew gładki",
        "ostrokrzew karbowanolistny / ostrokrzew bukszpanowy",
        "ostrokrzew kolczasty",
        "ostrokrzew meservy",
        "ostrokrzew okółkowy",
        "ostropest plamisty",
        "ostryż długi / kurkuma długolistna",
        "ostryż żabieńcolistny / tulipan siam / kurkuma wąskolistna",
        "ostróżeczka ogrodowa",
        "ostróżka ogrodowa / ostróżka wyniosła",
        "ostróżka wyniosła 'new zealand mix'delphinium elatum 'new zealand mix'",
        "oxford ragwort",
        "ołownik uszkowaty",
        "ośmiał większy",
        "pachira nadwodna / pachira wodna / butelkowiec",
        "pachnotka zwyczajna",
        "pacific dogwood",
        "paciorecznik / kanna",
        "palczatka gerarda",
        "palczatka miotlasta",
        "palczatka miotlasta 'chameleon'schizachyrium scoparium",
        "pale corydalis",
        "palecznik chiński",
        "pandan amarylkolistny",
        "pantofelnik całolistny",
        "paper birch",
        "paprotka zwyczajna",
        "paprotnica krucha",
        "paprotnik kolczysty",
        "paproć krokodyla",
        "papryka",
        "papryka ozdobna / pieprzowiec roczny / pieprz turecki",
        "parocja perska",
        "parocja perska persian spireparrotia persica persian spire",
        "parsley",
        "parsnip",
        "parzydło leśne",
        "pasternak zwyczajny",
        "patison",
        "patyczak",
        "paulownia / pawłownia",
        "pawpaw",
        "pałczatka szorstkawa",
        "pałczycha",
        "pałka szerokolistna",
        "pałka wąskolistna",
        "pea",
        "peach",
        "peanut",
        "pear",
        "pedunculate oak",
        "pelargonia bluszczolistna",
        "pelargonia pachnąca / geranium pachnące / anginka",
        "pelargonia pasiasta",
        "pelargonia rabatowa",
        "pelargonia wielkokwiatowa",
        "pelea zielona",
        "pendant amaranth",
        "pennsylvania blackberry",
        "penny hedge",
        "penstemon",
        "peperomia srebrzysta",
        "peperomia tępolistna",
        "peperomia zwisająca",
        "pepino / psianka melonowa",
        "pepper root",
        "perennial ragweed",
        "perennial thistle",
        "perełkowiec drobnolistny / sofora",
        "perełkowiec japoński",
        "perowskia łobodolistna",
        "perowskia łobodolistna 'bluesette'perovskia atriplicifolia",
        "persian turpentine tree",
        "perska tarcza",
        "perukowiec 'grace'cotinus 'grace'",
        "perukowiec podolski",
        "perukowiec podolski 'dusky maiden'cotinus coggygria 'dusky maiden'",
        "perłówka orzęsiona",
        "petty morel",
        "petty spurge",
        "petunia ogrodowa",
        "petunia supertunia vista 'bubblegum'petunia × hybrida",
        "petunia supertunia vistapetunia x hybrida supertunia vista",
        "pełnik europejski",
        "phyla nodiflora / lippia repens",
        "piaskowiec górski",
        "piaskowiec górski 'blizzard compact'arenaria montana",
        "picklyburr",
        "pieprzyca siewna / rzeżucha",
        "pieris japoński",
        "pierwiosnek",
        "pierwiosnek bezłodygowy / pierwiosnek zwyczajny",
        "pierwiosnek kubkowaty",
        "pierwiosnek lekarski",
        "pierwiosnek wyniosły",
        "pietruszka korzeniowa",
        "pietruszka naciowa",
        "pietruszka zwyczajna",
        "pigeon berry",
        "pigwa pospolita",
        "pigwowiec japoński",
        "pigwowiec katajski / pigwowiec wąskolistny",
        "pigwowiec okazały",
        "pigwowiec pośredni",
        "pilea błyszcząca",
        "pilea peperomiowata / pieniążek",
        "pin oak",
        "pineapple",
        "pink corydalis",
        "pistachio",
        "pitanga / goździkowiec jednokwiatowy",
        "piwonia chińska",
        "piwonia drzewiasta",
        "piwonia koperkowa / piwonia delikatna",
        "piwonia lekarska",
        "pióropusznik strusi",
        "piątak lancetowaty",
        "pięciornik krzewiasty",
        "pięciornik nepalski",
        "pięciornik thurbera",
        "piżmian jadalny / okra",
        "plane (european sycamore)",
        "plantain",
        "platan klonolistny",
        "plejoblast pstry",
        "plektrantus koleusowaty / komarzyca",
        "pleurisy root",
        "plumeria",
        "pluskwica groniasta / świecznica",
        "poached egg plant",
        "pocan bush",
        "pochrzyn chiński",
        "podagrycznik pospolity",
        "podbiał pospolity",
        "podrzeń garbaty",
        "poinsecja nadobna / gwiazda betlejemska",
        "poison ivy",
        "poisonberry",
        "poisonflower",
        "poke",
        "pokeroot",
        "pokeweed",
        "pokrzywa zwyczajna",
        "pokrzywiec wilkes",
        "polecat weed",
        "polkweed",
        "polyscias",
        "pomidor zwyczajny",
        "poncyria trójlistkowa / pomarańcza trójlistkowa",
        "ponętlin / krynia / krynka",
        "poor annie",
        "poor man's mustard",
        "poorland daisy",
        "poplar",
        "poppy",
        "por",
        "portulaka pospolita",
        "portulaka umbraticola / portulaka zwisająca",
        "portulaka wielkokwiatowa",
        "porzeczka alpejska",
        "porzeczka biała",
        "porzeczka czarna",
        "porzeczka czerwona",
        "porzeczka krwista",
        "porzeczka złota",
        "possumhaw",
        "posłonek ogrodowy",
        "potato",
        "powojnik 'arabella'clematis 'arabella'",
        "powojnik 'diamond ball'clematis 'diamond ball'",
        "powojnik 'floral dance'clematis 'floral dance'",
        "powojnik 'generał sikorski'clematis 'generał sikorski'",
        "powojnik 'golden dream'clematis 'golden dream'",
        "powojnik 'jan iii sobieski'clematis 'jan iii sobieski'",
        "powojnik 'jan paweł ii'clematis jan paweł ii",
        "powojnik 'kaiser'clematis 'kaiser'",
        "powojnik 'królowa bona'clematis",
        "powojnik 'madame le coultre'clematis 'madame le coultre'",
        "powojnik 'nelly moser'clematis 'nelly moser'",
        "powojnik 'snow storm'clematis 'snow storm'",
        "powojnik / clematis",
        "powojnik alpejski",
        "powojnik jackmana",
        "powojnik jesienny",
        "powojnik pnący",
        "powojnik tangucki",
        "powojnik wąsaty",
        "poziomka attila",
        "poziomka pospolita",
        "poziomkówka indyjska",
        "pragnia kuklikowata",
        "pragnia syberyjska",
        "prairie rose",
        "prawoślaz lekarski",
        "prickly honeysuckle",
        "prickly thistle",
        "primrose",
        "proso rózgowate",
        "proso rózgowate 'nosferatu' pbrpanicum virgatum",
        "prosownica rozpierzchła",
        "prusznik niebieski / bez kalifornijski",
        "przebiśnieg / śnieżyczka",
        "przegorzan",
        "przetacznik kłosowy",
        "przetacznik kłosowy 'anniversary rose'veronica spicata 'anniversary rose'",
        "przetacznikowiec wirginijski",
        "przylaszczka pospolita",
        "przymiotno karwińskiego",
        "przymiotno ogrodowe",
        "przyostnia włosowata",
        "przypołudnik / kryształka",
        "przytulia wonna",
        "przywarka japońska",
        "przywrotnik",
        "przywrotnik alpejski",
        "psianka",
        "psianka słodkogórz",
        "psiząb liliowy",
        "psiząb ogrodowy / psiząb mieszańcowy",
        "pstrolistka sercowata",
        "pszonak lnolistny",
        "purple flowered toothwort",
        "purple raspberry",
        "pustynnik bungei",
        "pustynnik himalajski",
        "pustynnik olbrzymi",
        "puszkinia cebulicowata",
        "pysznogłówka dwoista",
        "pysznogłówka dęta",
        "pysznogłówka ogrodowa",
        "pęcherznica kalinolistna",
        "pęcherznica kalinolistna 'diabolo'physocarpus opulifolius diabolo",
        "pęcherznica kalinolistna magic ballphysocarpus opulifolius",
        "pęcherznica kalinolistna pantherphysocarpus opulifolius",
        "pęcherznica kalinolistna tiny wine goldphysocarpus opulifolius tiny wine gold",
        "qamasa",
        "queen anne's lace",
        "queen's gilliflower",
        "queensland bottle tree",
        "quercitron",
        "rabarbar ogrodowy",
        "radical weed",
        "rajgras wyniosły",
        "rambler rose",
        "rannik zimowy",
        "rantipole",
        "rapeseed",
        "raspberry",
        "rdest himalajski",
        "rdest pokrewny",
        "rdest wężownik",
        "rdestówka auberta / rdestówka bucharska",
        "recurved thorn apple",
        "red ash",
        "red birch",
        "red deadnettle",
        "red durian",
        "red ink plant",
        "red mulberry",
        "red oak",
        "red osier",
        "red osier dogwood",
        "red pine",
        "red river maple",
        "red willow",
        "redbrush",
        "redweed",
        "redwood sorrel",
        "reo meksykańskie",
        "rezeda wonna",
        "rheumatism root",
        "rhubarb",
        "ribwort",
        "rice asian rice",
        "river ash",
        "river birch",
        "river maple",
        "roadweed",
        "robinia akacjowa",
        "robinia akacjowa 'tortuosa'robinia pseudoacacia 'tortuosa'",
        "rock harlequin",
        "rocketcress",
        "rodgersja kasztanowcolistna",
        "rodgersja stopowcolistna",
        "rodochiton",
        "rogownica kutnerowata",
        "rogue's gilliflower",
        "rojnik",
        "rojnik murowy",
        "rojnik pajęczynowaty arctic whitesempervivum arachnoideum",
        "rojownik pospolity",
        "rokitnik wąskolistny",
        "roman wormwood",
        "rose milkweed",
        "rose willow",
        "rosemary",
        "rosiczka",
        "roskea",
        "roszpunka / roszponka",
        "round leaf honeysuckle",
        "royal star magnolia",
        "rozchodnik biały",
        "rozchodnik hiszpański",
        "rozchodnik kamczacki",
        "rozchodnik kaukaski",
        "rozchodnik okazały / rozchodnikowiec okazały",
        "rozchodnik ostry",
        "rozchodnik ościsty",
        "rozmaryn lekarski",
        "rozplenica japońska",
        "rozplenica perłowa / rozplenica purpurowa",
        "rozplenica słoniowa 'vertigo'pennisetum purpureum",
        "rozpław sercowaty",
        "rozwar wielkokwiatowy",
        "rudbekia błyskotliwa",
        "rudbekia naga",
        "rudbekia owłosiona",
        "rukola / rokietta siewna",
        "rum cherry",
        "rumianek pospolity",
        "runianka japońska",
        "running swamp blackberry",
        "russelia equisetiformis",
        "ruta zwyczajna",
        "rutewka delavay'a",
        "rutewka orlikolistna",
        "rye",
        "rzeżucha łąkowa",
        "rzodkiew czarna",
        "rzodkiewka",
        "rzęsa drobna",
        "róża 'abraham darby'rosa 'abraham darby'",
        "róża 'apple blossom'rosa 'apple blossom'",
        "róża 'cutie pie'rosa",
        "róża 'double delight'rosa 'double delight'",
        "róża 'duke of edinburgh' / róża książe edynburga",
        "róża 'gertrude jekyll'rosa gertrude jekyll",
        "róża 'graham thomas'rosa 'graham thomas'",
        "róża 'heidelberg'rosa 'heidelberg'",
        "róża 'incredible fruity'rosa 'incredible fruity'",
        "róża 'ingrid bergman'rosa 'ingrid bergman'",
        "róża 'jam a licious'rosa jam a licious",
        "róża 'księżna helena radziwiłłowa'rosa 'księżna helena radziwiłłowa'",
        "róża 'minerva'rosa 'minerva'",
        "róża 'new dawn'rosa 'new dawn'",
        "róża 'princess anne'rosa princess anne",
        "róża 'rosarium uetersen'rosa 'rosarium uetersen'",
        "róża 'whisky'rosa 'whisky'",
        "róża anisade 'wekvossutono'rosa 'anisade'",
        "róża borneo odore 'intercomgarf'rosa borneo odore 'intercomgarf'",
        "róża damasceńska",
        "róża girlandowa",
        "róża maja babylon eyes 'intereybabjam'rosa 'intereybabjam'",
        "róża ogrodowa",
        "róża oso easy peasy®rosa x",
        "róża pomarszczona",
        "róża pustyni",
        "róża sina",
        "róża stulistna / centyfolia",
        "róża suñorita",
        "róża zepeti 'meibenbino'rosa zepeti 'meibenbino'",
        "różanecznik 'devin'rhododendon 'devin'",
        "różanecznik 'praděd'rhododendron",
        "różanecznik / rododendron",
        "różanecznik jakuszimański",
        "różanecznik ostrokończysty",
        "różeniec górski",
        "rącznik pospolity",
        "sacred datura",
        "sacred thorn apple",
        "sadziec",
        "sadziec konopiasty",
        "sadziec purpurowy",
        "saffron crocus",
        "salvia elegans / szałwia ananasowa",
        "sand brier",
        "sand thorn apple",
        "saneskobaria kwietniowa",
        "sanguinary",
        "sansewieria gwinejska / wężownica gwinejska",
        "sansewieria parva",
        "sansewieria walcowata / sansewieria cylindryczna / wężownica walcowata",
        "sanwitalia rozesłana (polegnatka)sanvitalia procumbens",
        "sasanka zwyczajna",
        "saskatoon",
        "sauce alone",
        "sałata rzymska",
        "sałata siewna",
        "scarlet berry",
        "scarlet oak",
        "scewola",
        "scindapsus złoty / scindapsus pstry",
        "scoke",
        "scotch cap",
        "scots pine",
        "scrambled eggs",
        "screwbean mesquite",
        "scrub oak",
        "scurvy cress",
        "scurvy grass",
        "sea plantain",
        "seler naciowy",
        "seler zwyczajny",
        "serduszka okazała",
        "serendipity ruby magnolia",
        "sesleria jesienna",
        "sesleria lśniąca",
        "sessile oak",
        "shadblow",
        "shadblow serviceberry",
        "shadbush",
        "sharp fringed sow thistle",
        "shrubby mayweed",
        "sikang pine",
        "silkweed",
        "silky cornel",
        "silky dogwood",
        "silky swallow wort",
        "silver birch",
        "silver maple",
        "silver ragwort",
        "silverleaf maple",
        "sit spiralny / sit rozpierzchły 'spiralis'juncus effusus 'spiralis'",
        "skalnica arendsa",
        "skalnica cienista",
        "skalnica gronkowa",
        "skimia japońska",
        "skrzydlinka armeńska",
        "skrzydlinka naprzeciwlistna",
        "skrzydlinka wielkokwiatowa",
        "skrzydłokwiat / skrzydłolist",
        "skrzyp zimowy",
        "skrętnik",
        "skunk cabbage",
        "skunkweed",
        "smagliczka nadmorska / lobularia",
        "smagliczka skalna",
        "small flowered thistle",
        "smużyna",
        "snakeberry",
        "sneezeweed",
        "sneezewort",
        "sneezewort yarrow",
        "snowdrop",
        "soczewica jadalna",
        "soft maple",
        "soldier's woundwort",
        "soleirolia rozesłana / chłopięca główka",
        "soliród zielny",
        "sorgo",
        "sorrel",
        "sosna czarna",
        "sosna czarna 'merci'pinus nigra",
        "sosna czarna ‘brepo’pinus nigra ‘brepo’",
        "sosna górska 'winter gold'pinus mugo 'winter gold'",
        "sosna górska / kosodrzewina",
        "sosna gęstokwiatowa 'rainbow'pinus densiflora 'rainbow'",
        "sosna kosodrzewina 'tukan'pinus mugo subsp. uncinata 'tukan'",
        "sosna oścista",
        "sosna pospolita / sosna zwyczajna",
        "sosna thunberga",
        "sosna wejmutka",
        "sosna żółta",
        "southern magnolia",
        "sośnica",
        "sośnica japońska 'mr. bean'sciadopitys verticillata",
        "spanish oak",
        "spartyna grzebieniasta 'aureomarginata'spartina pectinata 'aureomarginata'",
        "speckled alder",
        "speedwell corn speedwell",
        "spice birch",
        "spigelia marilandica",
        "spikenard",
        "spiny leaved sow thistle",
        "spiny sow thistle",
        "spoolwood",
        "spotted deadnettle",
        "spotted oak",
        "spring cress",
        "squaw bush",
        "stag bush",
        "stammerwort",
        "stapelia",
        "star of persia",
        "starzec popielny / mróz",
        "starzec rowleya",
        "stefanotis bukietowy",
        "stellar ruby magnolia",
        "stephania erecta",
        "sternbergia żółta",
        "stewarcja kameliowata",
        "stewia",
        "stickweed",
        "stiff sunflower",
        "stinking corpse flower",
        "stinkweed",
        "stokrotka pospolita",
        "stone pine",
        "storczyk cymbidium",
        "storczyk dendrobium",
        "storczyk epidendrum",
        "storczyk falenopsis",
        "storczyk paphiopedilum / sabotek",
        "strawberry",
        "strawberry tree",
        "strawberry tree 'marina'",
        "strelicja biała",
        "strelicja królewska",
        "striped maple",
        "stromanthe",
        "strzałkowiec grzechotkowy",
        "suchlin różowy",
        "suchodrzew chiński",
        "suchodrzew tatarski / wiciokrzew tatarski",
        "suchokwiat roczny",
        "sugar maple",
        "sugarcane",
        "sugarplum",
        "sumak octowiec",
        "summer lilac",
        "sundari (bangladesh)",
        "sunflower",
        "surfinia",
        "surmia bignoniowa 'aurea'catalpa bignonioides 'aurea'",
        "surmia bignoniowa / katalpa zwyczajna",
        "surmia pośrednia / katalpa pośrednia",
        "surmia wielkokwiatowa / katalpa wielkokwiatowa",
        "swallow wort orange swallow wort",
        "swamp ash",
        "swamp cabbage",
        "swamp datura",
        "swamp dewberry",
        "swamp hellebore",
        "swamp holly",
        "swamp maple",
        "swamp milkweed",
        "swamp oak",
        "swamp silkweed",
        "swamp spanish oak",
        "swamp white oak",
        "sweet birch",
        "sweet orange",
        "sweet potato",
        "sweet potato vine",
        "sweet rocket",
        "sweetbay magnolia",
        "swine thistle",
        "swinies",
        "swiss cheese plant",
        "sword ferns",
        "sycamore (american)",
        "sycamore (arizona)",
        "sycamore (california)",
        "syngonium stopowcowe / zroślicha",
        "syningia okazała / gloksynia doniczkowa",
        "szachownica cesarska",
        "szachownica kostkowata",
        "szachownica perska",
        "szachownica sewerzowa / fritillaria sewerzowii",
        "szafirek armeński",
        "szafirek groniasty",
        "szafirek miękkolistny",
        "szakłak pospolity",
        "szalotka",
        "szanta zwyczajna",
        "szarobródek syberyjski",
        "szarotka alpejska",
        "szarłat zwisły",
        "szałwia błyszcząca / szałwia ogrodowa",
        "szałwia lekarska",
        "szałwia muszkatołowa",
        "szałwia okręgowa",
        "szałwia omszona",
        "szałwia omszona 'pink profusion'salvia nemorosa 'pink profusion'",
        "szałwia omszona blue marvel 'balsalarv'salvia nemorosa 'blue marvel'",
        "szałwia powabna",
        "szczaw zwyczajny",
        "szczawik czterolistny",
        "szczawik zajęczy",
        "szczeć pospolita",
        "szczypiorek / czosnek szczypiorek",
        "szczypiorek czosnkowy / czosnek bulwiasty",
        "szeflera drzewkowata",
        "szkarłatka amerykańska",
        "szlumbergera zimowa / kaktus bożonarodzeniowy / grudnik",
        "szorstkowiec fortunego",
        "szparag lekarski",
        "szparag pierzasty",
        "szparag sprengera",
        "szpinak",
        "szpinak malabarski / szpinak pnący",
        "szpinak musztardowy / komatsuna",
        "szpinak nowozelandzki",
        "sępota pnąca",
        "słonecznica / delosperma",
        "słoneczniczek zwyczajny / słoneczniczek szorstki",
        "słonecznik zwyczajny",
        "taiwan red pine",
        "tall ambrosia",
        "tall coneflower",
        "tall ragweed",
        "tamaryszek drobnokwiatowy / czteropręcikowy",
        "tamaryszek francuski",
        "tansy common tansy",
        "tassel flower",
        "tassel weed",
        "tatarak trawiasty",
        "tawlina jarzębolistna",
        "tawulec pogięty / stephanandra incisa 'crispa'stephanandra incisa",
        "tawuła",
        "tawuła brzozolistna",
        "tawuła douglasa",
        "tawuła gęstokwiatowa",
        "tawuła japońska",
        "tawuła japońska double play dooziespiraea japonica",
        "tawuła nippońska",
        "tawuła norweska / tawuła szara 'grefsheim'spiraea x cinerea",
        "tawuła thunberga",
        "tawuła van houtte'a",
        "tawuła wczesna",
        "tawuła wierzbolistna",
        "tawuła śliwolistna",
        "tawułka arendsa",
        "tawułka chińska",
        "tea",
        "tenasserim pine",
        "terebinth",
        "thimbleberry",
        "thimbleweed",
        "thin leaved coneflower",
        "thousand leaf",
        "thousand seal",
        "three leaf maple",
        "three leaved coneflower",
        "thyme",
        "tiarella sercolistna",
        "tickleweed",
        "tobacco plant",
        "tojad",
        "tojad sudecki",
        "tojeść kropkowana",
        "tojeść rozesłana",
        "tomato",
        "topinambur / słonecznik bulwiasty",
        "topola amerykańska",
        "topola czarna",
        "topola osika",
        "touch me not",
        "trailing bittersweet",
        "trailing red huckleberry",
        "trailing violet nightshade",
        "traveller's joy",
        "trawa cytrynowa / palczatka cytrynowa",
        "trawa pampasowa / kortaderia pampasowa",
        "tread softly",
        "tree onion",
        "tree sow thistle",
        "tree tobacco",
        "trojeść bulwiasta",
        "trojeść krwista",
        "tropical pine",
        "truskawka",
        "trybula ogrodowa",
        "trytoma ogrodowa / trytoma groniasta",
        "trzcina pospolita",
        "trzcinnik krótkowłosy",
        "trzcinnik ostrokwiatowy",
        "trzmielina fortune'a",
        "trzmielina fortune'a 'emerald n gold'euonymus fortunei 'emerald gold'",
        "trzmielina fortune'a 'kewensis'euonymus fortunei 'kewensis'",
        "trzmielina japońska golden quintentrzmielina japońska",
        "trzmielina niska",
        "trzmielina oskrzydlona",
        "trzykrotka andersona",
        "trzykrotka pasiasta / pasiatka",
        "trzykrotka purpurowa",
        "trzykrotka wężykowata",
        "trzykrotka wężykowata 'feeling flirty'tradescantia fluminensis 'feeling flirty'",
        "trzęślica",
        "trójlist wielkokwiatowy",
        "tuber root",
        "tuberoza bulwiasta / tuberoza wonna",
        "tulbagia fioletowa",
        "tulejnik kamczacki",
        "tulip",
        "tulipan",
        "tulipan 'fashion'tulipa kaufmanniana 'fashion'",
        "tulipan 'maria kaczyńska'tulipa 'maria kaczyńska'",
        "tulipan kaufmanna",
        "tulipanowiec amerykański",
        "tulipanowiec amerykański 'snowbird'liriodendron tulipifera",
        "tulsi",
        "tunbergia oskrzydlona",
        "tunbergia wielkokwiatowa",
        "turkish pine",
        "turzyca",
        "turzyca buchanana",
        "turzyca ceglasta",
        "turzyca sina",
        "turzyca włosista 'bronco'carex comans",
        "tygrysówka pawia",
        "tykwa pospolita",
        "tymianek pospolity / macierzanka tymianek",
        "tytoń oskrzydlony",
        "ubiorek gorzki",
        "ubiorek wiecznie zielony",
        "uczep",
        "uczep rózgowaty",
        "ugni molinae / chilijska guawa",
        "ukwap dwupienny",
        "umbrella palm",
        "umbrella papyrus",
        "upland cress",
        "urodlin trójłatkowy",
        "ułudka wiosenna",
        "valley oak",
        "vanilla orchid",
        "varnish tree",
        "velvet bean",
        "velvet flower",
        "viburnum",
        "violet bloom",
        "viper's grass",
        "virgin's bower",
        "virginia silkweed",
        "virginia virgin's bower",
        "virginia winterberry",
        "vizcaíno desert datura",
        "voodoo lily",
        "wall speedwell",
        "walnut",
        "waszyngtonia nitkowata",
        "water ash",
        "water birch",
        "water fern",
        "water maple",
        "waterlilly star magnolia",
        "wattle",
        "wawrzyn szlachetny / laur",
        "wawrzynek wilczełyko",
        "way thistle",
        "waybread",
        "weeping birch",
        "werbena cytrynowa / lippia trójlistna",
        "werbena ogrodowa",
        "werbena patagońska",
        "western jimsonweed",
        "western redbud",
        "western sword fern",
        "western trillium",
        "western wake robin",
        "wheat",
        "whiskey cherry",
        "white alder",
        "white ash",
        "white birch",
        "white cornel",
        "white dogwood",
        "white hellebore",
        "white indian hemp",
        "white man's foot",
        "white maple",
        "white mulberry",
        "white oak",
        "white root",
        "white tansy",
        "white trillium",
        "whorled milkweed",
        "wiciokrzew browna",
        "wiciokrzew browna 'mintrum'lonicera brownii 'mintrum'",
        "wiciokrzew henry'ego",
        "wiciokrzew pomorski",
        "wiciokrzew przewiercień",
        "widliczka apoda",
        "widliczka kraussa",
        "wieczornik damski",
        "wielkopączkowiec tłusty",
        "wielosił błękitny",
        "wierzba",
        "wierzba 'erythroflexuosa'salix 'erythroflexuosa'",
        "wierzba babilońska",
        "wierzba całolistna / wierzba japońska 'hakuro nishiki'salix integra 'hakuro nishiki'",
        "wierzba oszczepowata",
        "wierzba purpurowa",
        "wierzba płacząca 'chrysocoma' / wierzba żałobna",
        "wierzbówka kiprzyca",
        "wiesiołek dwuletni",
        "wiesiołek ozdobny",
        "wietlica japońska",
        "wietlica samicza",
        "wietrznica lessona",
        "wilczomlecz 'diamond frost'euphorbia hypericifolia",
        "wilczomlecz białounerwiony",
        "wilczomlecz groszkowy",
        "wilczomlecz migdałolistny",
        "wilczomlecz mirtowaty",
        "wilczomlecz ogrodowy",
        "wilczomlecz okazały / korona cierniowa",
        "wilczomlecz trójżebrowy",
        "wild black cherry",
        "wild carrot",
        "wild cherry",
        "wild cotton",
        "wild garlic",
        "wild hops",
        "wild onion",
        "wild orange",
        "wild pellitory",
        "wild rose",
        "wild tansy",
        "wilec purpurowy",
        "wilec ziemniaczany",
        "willow leaf sunflower",
        "windroot",
        "wineberry",
        "winnik tojadowaty",
        "winnik zmienny",
        "winobluszcz henry'ego",
        "winobluszcz pięciolistkowy",
        "winobluszcz trójklapowy",
        "winobluszcz zaroślowy",
        "winorośl japońska",
        "winorośl właściwa",
        "winter gilliflower",
        "winter rocket",
        "winterberry holly",
        "wintercress",
        "wiąz górski",
        "wiąz pospolity / wiąz polny",
        "wiąz syberyjski / wiąz turkiestanu",
        "wiąz szypułkowy",
        "wiązówka błotna",
        "wiśnia kosmata",
        "wiśnia osobliwa",
        "wiśnia piłkowana",
        "wiśnia pospolita",
        "wiśnia wonna / antypka",
        "wolfsbane chinese wolfsbane",
        "woodbine",
        "woody nightshade",
        "woolly morning glory",
        "woolly yarrow",
        "wormwood roman wormwood",
        "wound rocket",
        "wrotycz pospolity",
        "wrzos pospolity",
        "wrzos pospolity skyline 'stockholm'calluna vulgaris skyline 'stockholm'",
        "wrzos pospolity skyline 'sydney'calluna vulgaris skyline 'sydney'",
        "wrzosiec",
        "wrzosiec czerwony 'snow queen'erica carnea 'snow queen'",
        "wrzosiec czerwony 'vivelii'erica carnea 'vivelii'",
        "wrzosiec delikatny",
        "wrzosiec drzewiasty",
        "wyczyniec łąkowy",
        "wydmuchrzyca piaskowa",
        "wyka ptasia",
        "wyka siewna",
        "yam",
        "yellow birch",
        "yellow coneflower",
        "yellow corydalis",
        "yellow daisy",
        "yellow fieldcress",
        "yellow fumewort",
        "yellow harlequin",
        "yellow milkweed",
        "yellow ox eye daisy",
        "yellow rocket",
        "yellowbark oak",
        "yellowwood",
        "yunnan camellia",
        "yunnan pine",
        "zamia furfuracea / sagowiec jamajski",
        "zamiokulkas zamiolistny",
        "zanokcica gniazdowa",
        "zatrwian tatarski",
        "zatrwian wrębny",
        "zawciąg nadmorski 'rosea'armeria maritima 'rosea'",
        "zawciąg nadmorski / zawciąg pospolity",
        "zawilec 'garden breeze pink touch'anemone × hybrida",
        "zawilec 'summer breeze snow'anemone",
        "zawilec gajowy",
        "zawilec grecki / zawilec powabny",
        "zawilec japoński / zawilec chiński",
        "zawilec ogrodowy",
        "zawilec wielkokwiatowy",
        "zawilec wieńcowy",
        "zawilec żółty",
        "zaślaz mieszańcowy (klonik)abutilon hybridum",
        "zebrawood",
        "zedoary",
        "zefirant",
        "zielistka 'green orange' / chlorophytum orchidastrum",
        "zielistka czubiasta",
        "zielistka sternberga",
        "zimokwiat wczesny",
        "zimowit bizantyjski",
        "zimowit jesienny",
        "zombie cucumber",
        "zwartnica / hipeastrum",
        "złocień arktyczny",
        "złocień krzewiasty",
        "złocień trójbarwny",
        "złocień wielki / jastrun wielki",
        "złocień właściwy / jastrun właściwy / margerytka",
        "złociszek oskrzydlony / wiekuistka rozgałęziona",
        "złotlin japoński",
        "złotokap pospolity",
        "złotokap waterea 'vossii'laburnum x watereri (g. kirchn.) dippel 'vossii'",
        "łosie rogi / płaskla",
        "łubin ogrodowy",
        "łubin trwały",
        "ślaz dziki",
        "ślaz zaniedbany",
        "ślazówka letnia",
        "śliwa domowa",
        "śliwa mirabelka",
        "śliwa tarnina",
        "ślęzawa trójwrębna",
        "śmiałek darniowy",
        "śniedek",
        "śniedek wiechowaty",
        "śniedek wątpliwy",
        "śniegowiec wirginijski",
        "śnieguliczka biała",
        "śnieżnik",
        "śnieżnik lśniący",
        "śnieżnik sardeński",
        "śnieżyca wiosenna",
        "świdośliwa olcholistna",
        "świerk biały",
        "świerk brewera",
        "świerk czarny",
        "świerk czerwony",
        "świerk kaukaski",
        "świerk kłujący",
        "świerk kłujący 'szelest'picea pungens 'szelest'",
        "świerk pospolity",
        "świerk pospolity 'tabuliformis'picea abies 'tabuliformis'",
        "świerk serbski",
        "świerk serbski 'golden rain'picea omorika 'golden rain'",
        "świerzbnica macedońska",
        "świerzbnica polna",
        "żabieniec babka wodna",
        "żabieniec lancetowaty",
        "żagwin ogrodowy",
        "żarnowiec miotlasty",
        "żeleźniak kaszmirski",
        "żeleźniak krzewiasty",
        "żeleźniak russela / żeleźniak żółty",
        "żeniszek meksykański",
        "żmijowiec zwyczajny",
        "żuraweczka× heucherella",
        "żurawina błotna",
        "żurawina wielkoowocowa",
        "żurawka 'binoche'heuchera 'binoche'",
        "żurawka 'citronelle'heuchera 'citronelle'",
        "żurawka 'dolce wildberry'heuchera hybrid dolce wildberry",
        "żurawka 'rex black'heuchera 'rex black'",
        "żurawka 'world caffe™ vienna'heuchera",
        "żurawka drobnokwiatowa",
        "żurawka drżączkowata",
        "żurawka drżączkowata 'titania'heuchera x brizoides 'titania'",
        "żurawka ogrodowa",
        "żylistek szorstki",
        "żylistek szorstki 'candidissima'deutzia scabra 'candidissima'",
        "żylistek wysmukły",
        "żywokost lekarski",
        "żyworódka omszona",
        "żyworódka pierzasta",
        "żywotnik olbrzymi",
        "żywotnik olbrzymi 'golden whipcord'thuja plicata",
        "żywotnik wschodni / biota wschodnia",
        "żywotnik zachodni",
        "żywotnik zachodni 'smaragd'thuja occidentalis 'smaragd'",
        "żywotnik zachodni 'spiralis'thuja occidentalis 'spiralis'",
        "żywotnik zachodni 'sunkist'thuja occidentalis 'maria'",
        "żywotnik zachodni 'sunny smaragd'thuja occidentalis 'sunny smaragd'",
        "żywotnik zachodni 'totem smaragd'thuja occidentalis 'totem smaragd'",
        "żywotnik zachodni great starthuja occidentalis",
        "żywotnikowiec japoński",
        "żółtnica pomarańczowa",
    }
)
