"""Uzupełnienie flory z GBIF (Plantae, Fungi, Chromista; pole Roślina).

Wygenerowano skryptem ``scripts/build_fauna_flora_gbif_supplement.py``. Nie edytuj ręcznie — odtwórz skryptem.
"""

from __future__ import annotations

from typing import Final

PLANTS_GBIF_NORMS: Final[frozenset[str]] = frozenset(
    {
        "agapant baldaszkowy",
        "agapant wczesny",
        "agapant wąskolistny",
        "agapant łodygowy",
        "agawa parryi",
        "aksamitka lemmona",
        "aldrowanda pecherzykowata",
        "aminek większy",
        "amzonia palmera",
        "arizema griffitha",
        "arizema najbielsza",
        "arizema zgrabna",
        "bakopa okółkowa",
        "barszcz austriacki",
        "barszcz mantegazyjski",
        "barszcz rozcięty",
        "bezrąbek czterokanciasty",
        "bielistka skalna",
        "bieluń indiański",
        "bjarnarkló",
        "bliźniczka",
        "bluszcz himalajski",
        "bodziszek arabski",
        "bodziszek nepalski",
        "bokkonia krzewiasta",
        "borówka jajowata",
        "bożodrzew gruczołkowaty",
        "brzezyca jednokwiatowa",
        "brzostownica grabolistna",
        "brzostownica schneidera",
        "brzoza karlowata",
        "brzoza kulistokotkowa",
        "bylica estragon",
        "bylica szara",
        "bylica trójzębna",
        "błótnica",
        "cantedeskia elliotta",
        "cebulica maderska",
        "centuria czerwona",
        "centuria nadbrzezna",
        "chaber drobnoglówkowy",
        "chaber wielkoglówkowy",
        "chamedafne pólnocna",
        "chamedora allena",
        "chamedora kostarykańska",
        "choina chińska",
        "choina mertensa",
        "chwastnica pagórkowata",
        "cibora gładka",
        "cibora paskowana",
        "ciemiernik wonny",
        "cychória",
        "gwiazdosz chiński",
        "hórski putnik",
        "igława chilijska",
        "igława wyniosła",
        "kariopteris mongolski",
        "kariopteris szary",
        "kisałe jahodki",
        "kisały ćerń",
        "kącicierń gładki",
        "lepnica dwupienna",
        "lilia afrykańska",
        "małka bozanka",
        "mały barbjenk",
        "mjetelowy bóz",
        "omżyn (budleja) dawida",
        "papel moras",
        "pitallón",
        "pitallón de la cuaresma",
        "pitallón negru",
        "prawa wjelezłotowka",
        "psia trawka",
        "psiząb palczasty",
        "smjerźecy kichac",
        "soplica kauri",
        "trawa bermudzka",
        "tzólich",
        "wopowańska jagoda",
        "wspięga pospolita",
        "złotogłów gałęzisty",
    }
)
